### ISSUE TITLE
2017-12-06 Adaptec.cz

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#1]
Date: Wed, 6 Dec 2017 08:50:25 +0100
From: Petr Řehák 
Subject: [Shim-review] Adaptech Shim for review

Hello,

As part of the Shim signing proces as requested by Microsoft, I am kindly
asking you to approve our Shim on behalf of Adaptech s.r.o. in order to get
it signed by Microsoft. You can download the package at:
https://www.adaptech.cz/bin/shim.tar.gz

Thanks,

Petr Řehák
--
Adaptech s.r.o.

**Comment by cyphermox** [comment]
I've reviewed the shim build for this (and reproduced it fine). It
looks fine, but I am a little concerned about grub.

The submission mentions patches applied on top of grub and the Secure Boot
patches. Do these affect the Secure Boot behavior? If so, how? Is
there any good reason to not have these patches available publicly?

**Comment by cyphermox** [comment]
Reviewed grub patches and the shim, looks fine to me.

@vathpela @mjg59 , this looks fine to you?
