### ISSUE TITLE
Process for SHIM review in light of BootHole?

### ISSUE THREAD

**Issue by panburana** [rhboot/shim-review#100]
In light of the public announcement of BootHole, how does it affect the process of getting a SHIM reviewed?
Is Microsoft still signing SHIMS? If so, with what cert? 

Thanks,

Peter

**Comment by julian-klode** [comment]
I've already updated the questions for new submissions, but I want to add a Dockerfile template so people have a guide on how to provide shim review requests that can be reviewed comparatively quickly.

**Comment by panburana** [comment]
Hey Julian, thanks for the reply, sorry for my delayed response as I started thinking this question was lost in the noise. 
I see reviews have started back and coupled with your new questions it sounds like the review process on this end is addressed. I take it Microsoft is now signing shims that have been reviewed with your questions?

**Comment by julian-klode** [comment]
If the review is successful, yes, it should be signed. To get a successful review, make sure to include a Dockerfile for rebuilding your shim, otherwise it's a lot more effort and people might review easier ones instead.
