### ISSUE TITLE
Question: Is it acceptable to create custom Grub modules?

### ISSUE THREAD

**Issue by jc-lab** [rhboot/shim-review#127]
If I create a Grub Module to use a feature that Grub does not have—for example, pressing the Fn key—is it a Shim review rejection?

If so, is there a way to validate the Custom Grub module?

Thank you.

**Comment by julian-klode** [comment]
I think we do already have grubs with custom modules or functions; and you can explain those changes. If they are sensible to review during shim review, it should not be an issue.
