### ISSUE TITLE
Question: Is it required to protect private keys with hardware cryptography module?

### ISSUE THREAD

**Issue by tSU-RooT** [rhboot/shim-review#131]
Hello.

I am working to submit for shim-review.
For allow booting onw shim, grub2, kernel and fwupd in secureboot enabled environment.  

I have looked up that submitted issues by third person.  
According to review comment to SUSE's form,  
The private key **must be protected with hardware cryptography module.**
https://github.com/rhboot/shim-review/issues/114#issuecomment-698376446

>MS says:
>The private key must be protected with a hardware cryptography module.
>This includes but is not limited to HSMs, smart cards, smart card–like USB tokens, and TPMs.

Is this means that reviewee must to protect private keys with hardware cryptography module?

If so, I think this should be noticed at README.md or ISSUE_TEMPLATE.md.  
(Document the recommended method is more desirable)  

Regards,

**Comment by Doncuppjr** [comment]
If I recall, you can use an hardware aes256 flashdrive for storing your CA offline.

**Comment by julian-klode** [comment]
The questions are a bit more veiled precisely so that you can't just answer yes to them. There are various levels of correct answers, e.g. in Ubuntu our CA key is distributed amongst people and we have a networked signing service, not a hardware module (the signing key is wrapped by one I think, though, but it's still present outside a crypto module).

**Comment by tSU-RooT** [comment]
Hi, thank you for reply.  

>There are various levels of correct answers,
 
I understand it.
I am considering to use Yubikey's 9a slot as smartcard.

Last week, I have confirmed yubikey is usable for such digital sign via "pesign-client".

**Comment by Doncuppjr** [comment]
That should be fine. sbsign also works with smartcards.
