### ISSUE TITLE
SHIM 15.3 for Deepin

### ISSUE THREAD

**Issue by deepin-secureboot** [rhboot/shim-review#144]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 https://github.com/deepin-secureboot/shim-review/tree/deepin-shim
 - [x] completed README.md file with the necessary information
 https://github.com/deepin-secureboot/shim-review/blob/deepin-shim/README.md
 - [x] shim.efi to be signed
 https://github.com/deepin-secureboot/shim-review/blob/deepin-shim/shimx64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 https://github.com/deepin-secureboot/shim-review/blob/deepin-shim/deepin-uefi-ca.der
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 Not used
 - [x] any extra patches to shim via your own git tree or as files
 N/A
 - [x] any extra patches to grub via your own git tree or as files
 N/A
 - [x] build logs
https://github.com/deepin-secureboot/shim-review/blob/deepin-shim/logs.txt

###### What organization or people are asking to have this signed:

Deepin: https://www.deepin.org/en/

###### What product or service is this for:

Deepin V20.

###### Please confirm this as the origin your shim.

Yes, we are using the source from https://github.com/rhboot/shim/releases/download/15.3/shim-15.3.tar.bz2

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:

Deepin is yet another linux distribution based on Debian GNU/Linux. It has been actively maintained since 2011. Deepin has kept in the top 20 on distrowatch for last few years. It is an amazing distribution, and for compatible reason, we here submit our siging request for shim.

###### How do you manage and protect the keys used in your SHIM?

The key is stored in isolated standalone server which is placed in secure area with limited access.

###### Do you use EV certificates as embedded certificates in the SHIM?

No.

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?

No.

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?

Yes, we use kernel 5.10 with this patch included

###### fixed ?

Yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

We keep all upstream SBAT entries and also append Deepin specific.
Since most packages in Deepin are based on Debian we also keep Debian specific entries.

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.04,https://www.gnu.org/software/grub/
grub.deepin,1,Deepin,grub2,2.04-17,mail:secureboot@deepin.com
```

```
sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd,1,Firmware update daemon,fwupd,1.5.7,https://github.com/fwupd/fwupd
fwupd-deepin,1,Deepin,fwupd,1.5.7-3,mail:secureboot@deepin.com
```

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.deepin,1,Deepin,shim,15.3,mail:secureboot@deepin.com
```

All new UEFI binaries that are yet to be built with SBAT support will
follow the agreed SBAT variable pattern and we will add Deepin specific
entries for them.

##### Were your old SHIM hashes provided to Microsoft ?

This is the first submission

##### grub2 bootloaders can not be verified ?

New grub2 builds with CVE fix will be signed with new signing EV certificate.

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?

Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?

upstream Debian Bullseye 2.04 version

###### If your SHIM launches any other components, please provide further details on what is launched

It will load fwupdate, fwupd as already mentioned above.

###### please provide further details on what is launched and how it enforces Secureboot lockdown

grub2 launches Linux kernel

###### apply. Please describe your strategy.

Not applicable, grub2 leaf certificate rotated in Deepin  shim

###### How do the launched components prevent execution of unauthenticated code?

Will not start unsigned programs

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?

 5.10 with secure boot supported.

###### What changes were made since your SHIM was last signed?

No.

###### What is the SHA256 hash of your final SHIM binary?

9f0d91956750b9ef48a5996ef99c2bdafe3cf0681899d39808db256dd19988ce shimx64.efi

**Comment by aburmash** [comment]
Hello. 2 comments:
* resubmit with update to 15.4, which includes necessary SBAT fixes
* 
* I see that to reproduce your build it is required to install system using ISO image.
I understand that you may not have the docker images that can be used to reproduce your build, but could you please think about maybe providing a tarball with a chroot environment, that can be used for build purposes ? It just makes it much easier and faster to reproduce the build itself.

**Comment by deepin-secureboot** [comment]
Thank you for review.
