### ISSUE TITLE
Smoothing out the process for non GIT experts.

### ISSUE THREAD

**Issue by TBOpen** [rhboot/shim-review#15]
Hi,  I told MS that I would provide some feedback that would hopefully smooth out the process for us non GIT experts.    The instructions for ISSUE_TEMPLATE.md (below) and the ones in README.md (which I also put below) are a little confusing.   Example, I figured out how to clone the repo (using tortoise git in windows),  So then I updated the .md files,  I copied in the shimx64.efi file,  I saw something about commit on the right click menu so I did that, then I saw some tag option, did that, then I tried to push it and nothing but access denied.    Another thing was how to create a git repo of the files used to compile.  Okay, I fumbled through that and got it to work, but still not clear on the whole thing.  

I would suggest creating a tutorial webpage (even if here in the git) on how to do things from linux and windows.  I'd suggest having a new folder under shim-review called something like shim-for-review/source and shim-for-review/patches, have people branch shim-review, then they clone or pull down the branched copy, then they update the .md files, add the shim binary and build-instructions.txt under shim-for-review, the source files under shim-for-review/source and any patches to shim-for-review/patches (explain in instructions how to add the files and new subdirs and commit), then have them push that, (they could then put an issue either on the main shim-review or the newly branched version that it's ready for review) you could then just manage the branched version with everything in once place and everything consistent.  People would be able to follow the process via the tutorial webpage.  

Make sure you have provided the following information:

 - [ ] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
Huh?
 - [ ] completed README.md file with the necessary information
 - [ ] shim.efi to be signed
 - [ ] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [ ] any extra patches to shim via your own git tree or as files
 - [ ] any extra patches to grub via your own git tree or as files
 - [ ] build logs
Why build logs?  Some people may have already built before even knowing about this process. Ask for gcc version, openssl version, os version.

Here's the ones from README.md:

- clone this repo
- edit the template below
- add the shim.efi to be signed
- add build logs
- commit all of that
- tag it with a tag of the form "myorg-shim-arch-YYYYMMDD"
- push that to github
access denied.
- file an issue at https://github.com/rhboot/shim-review/issues with a link to your tag

**Comment by julian-klode** [comment]
This bug has been open for 2 years, and I think git has achieved complete world domination by now, so everyone should be familiar, or learn it with ease. It's certainly easier than getting a proper shim setup, and hence also serves as a useful barrier to entry.
