### ISSUE TITLE
Shim 15.4 for Deepin

### ISSUE THREAD

**Issue by deepin-secureboot** [rhboot/shim-review#151]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
   https://github.com/deepin-secureboot/shim-review/tree/deepin-shim-15.4
 - [x] completed README.md file with the necessary information
   https://github.com/deepin-secureboot/shim-review/blob/deepin-shim-15.4/README.md
 - [x] shim.efi to be signed
   https://github.com/deepin-secureboot/shim-review/blob/deepin-shim-15.4/shimx64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
   https://github.com/deepin-secureboot/shim-review/blob/deepin-shim-15.4/deepin-uefi-ca.der
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
   Not used
 - [x] any extra patches to shim via your own git tree or as files
   N/A
 - [x] any extra patches to grub via your own git tree or as files
   N/A
 - [x] build logs
   https://github.com/deepin-secureboot/shim-review/blob/deepin-shim-15.4/logs.txt

###### What organization or people are asking to have this signed:
Deepin: https://www.deepin.org/en/

###### What product or service is this for:
Deepin V20.

###### Please confirm this as the origin your shim.
Yes, we are using the source from https://github.com/rhboot/shim/releases/download/15.4/shim-15.4.tar.bz2

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Deepin is yet another linux distribution based on Debian GNU/Linux. It has been actively maintained since 2011. Deepin has kept in the top 20 on distrowatch for last few years. It is an amazing distribution, and for compatible reason, we here submit our siging request for shim.

###### How do you manage and protect the keys used in your SHIM?
The key is stored in isolated standalone server which is placed in secure area with limited access.

###### Do you use EV certificates as embedded certificates in the SHIM?
No.

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
No.

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
Yes, we use kernel 5.10 with this patch included

###### fixed ?
Yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
We keep all upstream SBAT entries and also append Deepin specific.
Since most packages in Deepin are based on Debian we also keep Debian specific entries.

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.04,https://www.gnu.org/software/grub/
grub.debian,1,Debian,grub2,2.04-17,https://tracker.debian.org/pkg/grub2
grub.deepin,1,Deepin,grub2,2.04-17,https://www.deepin.org/en/
```
```
sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd,1,Firmware update daemon,fwupd,1.5.7,https://github.com/fwupd/fwupd
fwupd-debian,1,Debian,fwupd,1.5.7-3,https://tracker.debian.org/pkg/fwupd
fwupd-deepin,1,Deepin,fwupd,1.5.7-3,https://www.deepin.org/en/
```
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.debian,1,Debian,shim,15.4,https://tracker.debian.org/pkg/shim
shim.deepin,1,Deepin,shim,15.4,https://www.deepin.org/en/
```
All new UEFI binaries that are yet to be built with SBAT support will
follow the agreed SBAT variable pattern and we will add Deepin specific
entries for them.

##### Were your old SHIM hashes provided to Microsoft ?
This is the first submission

##### grub2 bootloaders can not be verified ?
New grub2 builds with CVE fix will be signed with new signing EV certificate.

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?

Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?

upstream grub2 2.04-17 , from Debian bullseye

###### If your SHIM launches any other components, please provide further details on what is launched

It will load fwupdate, fwupd as already mentioned above.

###### please provide further details on what is launched and how it enforces Secureboot lockdown

grub2 launches Linux kernel

###### apply. Please describe your strategy.

Not applicable, grub2 leaf certificate rotated in Deepin  shim

###### How do the launched components prevent execution of unauthenticated code?

Will not start unsigned programs

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?

 5.10 with secure boot supported.

###### What changes were made since your SHIM was last signed?

No.

###### What is the SHA256 hash of your final SHIM binary?

fb250586f3f3079fd45e3e673f564e06f70a3ea98b710238428ff3641dcc348c shimx64.efi

**Comment by deepin-secureboot** [comment]
Can the submission be reviewed

**Comment by miray-tf** [comment]
Looking at this issue and the commit 824902aa38fb2252a93d1f1d170534c90385faf4 https://github.com/deepin-secureboot/shim-review/tree/deepin-shim-15.4 

Please use a tag to reference the commit in the review tree. 
Please add the full version number of Debian Grub you use.
You mentioned that you keep Debian specific sbat entries. This is not this does not match with the sbat sections specified.

README.md:
Please use the latest Readme.md file and answer all questions in it.
Please add PGP keys to your security contacts.
The shim repo and commit hash do not reference Shim 15.4.
The referenced build log is different and seems to point to a shim 15.3 build

**Comment by deepin-secureboot** [comment]
Thanks for your review, README.md has been updated.

**Comment by deepin-secureboot** [comment]
Thanks for your review, README.md has been updated.

**Comment by deepin-secureboot** [comment]
Thanks for your review, README.md has been updated.

We use grub2 2.04-17 , from Debian bullseye

We use Shim 15.4 to build

**Comment by steve-mcintyre** [comment]
Build reproduces fine here.

SBAT looks good in the shim binary, *without* the debian entry (good, I think it's better to stay separate).

Embedded CA cert looks OK, I think. Most people tend to use 2K RSA keys here but I don't *expect* problems with a 4K key. Have you tested this shim build to make sure things work OK?

You don't have any patches applied on top of 15.4, which is probably OK. But I'd recommend you review the list linked in #165 and double-check you're happy with that. You're only building for amd64, so the ia32 and aarch64 issues won't bother you. But you might care more about:

- booting on older EFI versions (e.g. older Macs)
- mokutil --disable-validation
- the BootServicesData tweak (#361)

**Comment by steve-mcintyre** [comment]
oh, minor nit - your README.md says "Debian buster" but you're clearly using Bullseye. :-)

**Comment by deepin-secureboot** [comment]
Thank you for your review, I will update the submission and README.md

**Comment by haobinnan** [comment]
New issue: #172

**Comment by steve-mcintyre** [comment]
Superseded y #172
