### ISSUE TITLE
SHIM 15.4 for UOS

### ISSUE THREAD

**Issue by uos-secureboot** [rhboot/shim-review#153]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
   https://github.com/uos-secureboot/shim-review/tree/uos-shim-15.4
 - [x] completed README.md file with the necessary information
   https://github.com/uos-secureboot/shim-review/blob/uos-shim-15.4/README.md
 - [x] shim.efi to be signed
   https://github.com/uos-secureboot/shim-review/blob/uos-shim-15.4/shimx64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
   https://github.com/uos-secureboot/shim-review/blob/uos-shim-15.4/UOS-UEFI-RSA.cer
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
   Not used
 - [x] any extra patches to shim via your own git tree or as files
   N/A
 - [x] any extra patches to grub via your own git tree or as files
   N/A
 - [x] build logs
   https://github.com/uos-secureboot/shim-review/blob/uos-shim-15.4/logs.txt

###### What organization or people are asking to have this signed:

UOS Plum V20：https://www.chinauos.com/resource/download-personal

###### What product or service is this for:

UOS Plum V20.

###### Please confirm this as the origin your shim.

Yes, we are using the source from https://github.com/rhboot/shim/releases/download/15.4/shim-15.4.tar.bz2

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:

What's the justification that this really does need to be signed for the whole world to be able to boot it:
UOS Plum is yet another linux distribution based on Debian GNU/Linux. It has been actively maintained since 2020 It is an amazing distribution, and for compatible reason, we here submit our siging request for shim.

###### How do you manage and protect the keys used in your SHIM?

The key is stored in isolated standalone server which is placed in secure area with limited access.

###### Do you use EV certificates as embedded certificates in the SHIM?

No.

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?

No.

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?

Yes, we use kernel 5.7.7 with this patch included

###### fixed ?

Yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

We keep all upstream SBAT entries and also append Uos specific.
Since most packages in Uos are based on Debian we also keep Debian specific entries.

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.04,https://www.gnu.org/software/grub/
grub.uos,1,Uos,grub2,2.04-17,mail:secureboot@uniontech.com
```

```
sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd,1,Firmware update daemon,fwupd,1.5.7,https://github.com/fwupd/fwupd
fwupd-uos,1,Uos,fwupd,1.5.7-3,mail:secureboot@uniontech.com
```

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.uos,1,Uos,shim,15.4,mail:secureboot@uniontech.com
```

All new UEFI binaries that are yet to be built with SBAT support will
follow the agreed SBAT variable pattern and we will add Uos specific
entries for them.

##### Were your old SHIM hashes provided to Microsoft ?

This is the first submission

##### grub2 bootloaders can not be verified ?

New grub2 builds with CVE fix will be signed with new signing EV certificate.

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?

Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?

upstream Debian Bullseye 2.04 version

###### If your SHIM launches any other components, please provide further details on what is launched

It will load fwupdate, fwupd as already mentioned above.

###### please provide further details on what is launched and how it enforces Secureboot lockdown

grub2 launches Linux kernel

###### apply. Please describe your strategy.

Not applicable, grub2 leaf certificate rotated in Uos  shim

###### How do the launched components prevent execution of unauthenticated code?

Will not start unsigned programs

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?

 5.7 with secure boot supported.

###### What changes were made since your SHIM was last signed?

No.

###### What is the SHA256 hash of your final SHIM binary?

86f8bcb62e652abf6c87417611543c5d469cce333973c7d5dfb3749bf503b55f shimx64.efi

**Comment by julian-klode** [comment]
This shouldn't be using deepin SBAT entries I'd say.

**Comment by uos-secureboot** [comment]
Thanks for your review, I will revise the SBAT entry

**Comment by steve-mcintyre** [comment]
> This shouldn't be using deepin SBAT entries I'd say.

deepin? Do you mean Debian?

**Comment by steve-mcintyre** [comment]
otherwise: shim builds and reproduces fine here

**Comment by steve-mcintyre** [comment]
Can you clarify exactly which grub version you're using please? I understand you're basing on the Debian package from bullseye - just checking.

**Comment by uos-secureboot** [comment]
We use grub2 2.04-17 , from Debian bullseye

**Comment by steve-mcintyre** [comment]
You mention in the README.md:

"Upstream commit a4a1fbe7."

I'm guessing that's just you're using an out-of-date template here, so I'm not going to complain about that :-)

**Comment by steve-mcintyre** [comment]
I think this looks good overall. I'd like another reviewer to check and confirm, then happy to approve.

**Comment by uos-secureboot** [comment]
Yes, I used an outdated template, I will update README.md

**Comment by christopherco** [comment]
- [x] shim reproducible? *Yes*
```
root@cf9daaab221f:/build# sha256sum shim/shimx64.efi
86f8bcb62e652abf6c87417611543c5d469cce333973c7d5dfb3749bf503b55f  shim/shimx64.efi

shim-review$ sha256sum shimx64.efi
86f8bcb62e652abf6c87417611543c5d469cce333973c7d5dfb3749bf503b55f  shimx64.efi
```
- [x] shim .sbat contents accurate? *Yes (with nit)*
```
shim-review$ objdump -s -j .sbat shimx64.efi

shimx64.efi:     file format pei-x86-64

Contents of section .sbat:
 cc000 73626174 2c312c53 42415420 56657273  sbat,1,SBAT Vers
 cc010 696f6e2c 73626174 2c312c68 74747073  ion,sbat,1,https
 cc020 3a2f2f67 69746875 622e636f 6d2f7268  ://github.com/rh
 cc030 626f6f74 2f736869 6d2f626c 6f622f6d  boot/shim/blob/m
 cc040 61696e2f 53424154 2e6d640a 7368696d  ain/SBAT.md.shim
 cc050 2c312c55 45464920 7368696d 2c736869  ,1,UEFI shim,shi
 cc060 6d2c312c 68747470 733a2f2f 67697468  m,1,https://gith
 cc070 75622e63 6f6d2f72 68626f6f 742f7368  ub.com/rhboot/sh
 cc080 696d0a73 68696d2e 756f732c 312c556f  im.shim.uos,1,Uo
 cc090 732c7368 696d2c31 352e342d 312c6d61  s,shim,15.4-1,ma
 cc0a0 696c3a73 65637572 65626f6f 7440756e  il:secureboot@un
 cc0b0 696f6e74 6563682e 636f6d0a           iontech.com.
```
nit: your issue submission lists your shim vendor sbat as `shim.uos,1,Uos,shim,15.4,mail:secureboot@uniontech.com` but the vendor sbat in the shim binary is `shim.uos,1,Uos,shim,15.4-1,mail:secureboot@uniontech.com`. Recommend updating the issue submission so the vendor sbat matches.

**Comment by uos-secureboot** [comment]
Thanks for your review, I will initiate a new submission

**Comment by christopherco** [comment]
> Thanks for your review, I will initiate a new submission

I think It is sufficient to edit your issue template with the correct vendor sbat that matches your shim binary's vendor sbat `shim.uos,1,Uos,shim,15.4-1,mail:secureboot@uniontech.com`.

Everything else looked good.
