### ISSUE TITLE
Shim 15.4 for SUSE

### ISSUE THREAD

**Issue by jsegitz** [rhboot/shim-review#155]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/jsegitz/shim-review/tree/SUSE-SLES15.3-shim-20210329
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

###### What organization or people are asking to have this signed:
SUSE, https://suse.com/

###### What product or service is this for:
SUSE Linux Enterprice Server 15 SP3

###### Please confirm this as the origin your shim.
We use 15.4 shim + 
- shim-arch-independent-names.patch: use the Arch-independent names.
- shim-bsc1177315-verify-eku-codesign.patch: Check CodeSign in the signer's EKU
- shim-bsc1177789-fix-null-pointer-deref-AuthenticodeVerify.patch: fix NULL pointer dereference in AuthenticodeVerify
- shim-change-debug-file-path.patch: change path of debug file
- remove_build_id.patch: don't add the build id from the resulting binaries
- shim-bsc1184454-allocate-mok-config-table-BS.patch: Handle 'Failed to lookup EFI memory descriptor' errors

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Major linux distribution

###### How do you manage and protect the keys used in your SHIM?
The key is installed in a machine with restricted physical and system access.
Shim binaries do not include private portions of the key.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
n/a

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
yes

###### fixed ?
yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
We use this pattern:
shim.${distro_id},${distro_sbat},${distro_name},%{name},%{version},mail:security-team@suse.de

So for this shim:
shim.sle,1,SUSE Linux Enterprise,shim,15.4,mail:security-team@suse.de

##### Were your old SHIM hashes provided to Microsoft ?
yes

##### grub2 bootloaders can not be verified ?
yes (rotated signing key, old shims are blacklisted)

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?
upstream grub-2.04 with patches for all currently discussed security issues

###### If your SHIM launches any other components, please provide further details on what is launched
it doesn't

###### please provide further details on what is launched and how it enforces Secureboot lockdown
n/a

###### apply. Please describe your strategy.
We switched to a new certificate

###### How do the launched components prevent execution of unauthenticated code?
GRUB and kernel are patched to enforce Secure Boot.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
no

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
5.3.18 +
# Module signing / secure boot
patches.suse/KEYS-Make-use-of-platform-keyring-for-module-signatu.patch

# Lock down functions for UEFI secure boot
patches.suse/0001-security-lockdown-expose-a-hook-to-lock-the-kernel-down.patch
patches.suse/0002-efi-Add-an-EFI_SECURE_BOOT-flag-to-indicate-secure-boot-mode.patch
patches.suse/0003-efi-Lock-down-the-kernel-if-booted-in-secure-boot-mode.patch
patches.suse/0004-efi-Lock-down-the-kernel-at-the-integrity-level-if-b.patch

# Using the hash in MOKx to blacklist kernel module, FATE#316531
patches.suse/0001-MODSIGN-do-not-load-mok-when-secure-boot-disabled.patch
patches.suse/0001-efi-add-a-function-to-convert-the-status-code-to-a-s.patch
patches.suse/0002-efi-show-error-messages-only-when-loading-certificat.patch
patches.suse/0003-MODSIGN-load-blacklist-from-MOKx.patch
patches.suse/0004-MODSIGN-checking-the-blacklisted-hash-before-loading.patch

# Hibernation Signature Verification FATE#316350
patches.suse/0001-security-create-hidden-area-to-keep-sensitive-data.patch
patches.suse/0002-hibernate-avoid-the-data-in-hidden-area-to-be-snapsh.patch
patches.suse/0003-x86-KASLR-public-the-function-for-getting-random-lon.patch
patches.suse/0005-efi-generate-secret-key-in-EFI-boot-environment.patch
patches.suse/0006-efi-allow-user-to-regenerate-secret-key.patch
patches.suse/0007-PM-hibernate-encrypt-hidden-area.patch
patches.suse/0008-PM-hibernate-Generate-and-verify-signature-for-snaps.patch
patches.suse/0009-PM-hibernate-prevent-EFI-secret-key-to-be-regenerate.patch
patches.suse/0010-PM-hibernate-a-option-to-request-that-snapshot-image.patch
patches.suse/0011-PM-hibernate-require-hibernate-snapshot-image-to-be-.patch

###### What changes were made since your SHIM was last signed?
Signing key was changed to ensure no old grub/kernel can not be booted

###### What is the SHA256 hash of your final SHIM binary?
x86_64:
sh-4.4# pesign --hash --padding --in=usr/share/efi/x86_64/shim-sles.efi
hash: cf376dd1772694b2223fd56aa97c90ca34bbc1a68eafe34aaeb14b4b9e387320
sh-4.4# sha256sum usr/share/efi/x86_64/shim-sles.efi
fa63816b0e0cc6e2cdce94bd389a8b155000a93d0182d2f8874f3b0d7753bb7a  usr/share/efi/x86_64/shim-sles.efi

aarch64:
sh-4.4# pesign --hash --padding --in=usr/share/efi/aarch64/shim-sles.efi
hash: c362c260109e9f35305dc332b5ef57295133362188558d49c653f372bda1cb6d
sh-4.4# sha256sum usr/share/efi/aarch64/shim-sles.efi
a995353bb2bb43d8ff62375789c71a66d5d2151be89c292dfc8414bef01424e2  usr/share/efi/aarch64/shim-sles.efi

**Comment by jsetje** [comment]
I've hit a couple of technical hurdles trying to reproduce the build, someone on a non-rh-like system may have an easier time.

**Comment by jsegitz** [comment]
Thanks for trying. Maybe I can help out in fixing these technical hurdles? I went through the instructions on an openSUSE Tumbleweed system and it worked. I'll retry it on Fedora to ensure that it also works there, but the more details I have the better

**Comment by jsegitz** [comment]
I've retried it on Fedora 33 and it worked for me. Can you share what goes wrong for you?

**Comment by jsetje** [comment]
Oh, I see, the dockerfile won't actually work outside of your network. That makes it a a bit harder to sort through where the pieces come from.

**Comment by jsegitz** [comment]
yes, I know :( we've done it like this before, but if that's not acceptable anymore I can try to setup a repo that only contains the few packages that need to be installed additionally or upload them somewhere and modify the docker file to install the rpms directly

**Comment by jsetje** [comment]
We can sort through the image, I did it for Mariner. It's just slower work. :)

**Comment by jsegitz** [comment]
I just created 
https://github.com/jsegitz/shim-review/tree/SUSE-openSUSE15.3-shim-20210329_standalone
which is identical to this submission but includes all the necessary additional rpms to build the (modified) Dockerfile. I created a new tag since I didn't want to risk interrupting an already running review. 
With this you should be able to rebuild the image without using the provided images (which still are available if needed)

**Comment by martinezjavier** [comment]
> I just created
> https://github.com/jsegitz/shim-review/tree/SUSE-openSUSE15.3-shim-20210329_standalone

I used this but when building the SHA256 hashes don't match the ones listed in the `ISSUE_TEMPLATE.md`, not sure what I'm doing wrong:

```
$ podman build -f Dockerfile --build-arg ARCHITECTURE=x86_64
....
STEP 12: RUN cd /shim/ && unrpm /usr/src/packages/RPMS/$ARCHITECTURE/shim-*.$ARCHITECTURE.rpm
/usr/src/packages/RPMS/x86_64/shim-15.4-0.x86_64.rpm:   5487 blocks
/usr/src/packages/RPMS/x86_64/shim-debuginfo-15.4-0.x86_64.rpm: 31208 blocks
/usr/src/packages/RPMS/x86_64/shim-debugsource-15.4-0.x86_64.rpm:       16845 blocks
--> d64ca7eff1c
STEP 13: RUN pesign --hash --padding --in=/shim/usr/share/efi/$ARCHITECTURE/shim-sles.efi
hash: 17066c81bf4c73fb1c72bc582a7e3aad6ab5cdbca0a02684f2e4d575650d4322
--> b513f02869f
STEP 14: RUN sha256sum /shim/usr/share/efi/$ARCHITECTURE/shim-sles.efi
ef96e8c759f5ab0a23b842eafc21f46550f5bd04973f6d1154d7f7fbecf35c5a  /shim/usr/share/efi/x86_64/shim-sles.efi
STEP 15: COMMIT
--> e70171a5afa
e70171a5afa0896cd68d15420494d4345886716cafb9897a1d170ca814407851
```

**Comment by martinezjavier** [comment]
> shim.sle,1,SUSE Linux Enterprise,shim,15.4,mail:[security-team@suse.de](mailto:security-team@suse.de)

I think there is a typo here and should instead be `shim.sles` ?

**Comment by jsegitz** [comment]
that is intentional. SLE == SUSE Linux Enterprise. The "S" stands for Server, but he have other products. We use this to some extend interchangeable, but here SLE is more apropriate

**Comment by martinezjavier** [comment]
@jsegitz thanks for the clarification. I got confused since this review request was for product "SUSE Linux Enterprise Server" but I guess the other products use the same shim source (and signed binary) so SLE is more appropriate indeed.

**Comment by jsegitz** [comment]
> I used this but when building the SHA256 hashes don't match the ones listed in the ISSUE_TEMPLATE.md

I'll try to recreate it with the command you provided and will get back to you

**Comment by jsegitz** [comment]
> I just created
> https://github.com/jsegitz/shim-review/tree/SUSE-openSUSE15.3-shim-20210329_standalone

well that should have been 
SUSE-SUSE15.3-shim-20210329_standalone
the content in the repo is correct, but the tag is wrong. I pushed this tag to prevent confusion for other reviewers

**Comment by jsegitz** [comment]
I can confirm that these are the hashes when I use podman. I used docker to create test these images. Interesting that this makes a difference. I'll dig into this and comment here. Sorry for the additional effort :(

**Comment by jsegitz** [comment]
That was my error, sorry. The shim sources in this tag were not current
https://github.com/jsegitz/shim-review/tree/SUSE-SUSE15.3-shim-20210329_standalone
contains the updated shim sources + a minor additional fix (for me there was one more rpm missing).
I tried it with the command you used and get the hashes specified in the README

**Comment by martinezjavier** [comment]
@jsegitz hmm, I'm getting the same hashes than before with `SUSE-SUSE15.3-shim-20210329_standalone`, unless I'm doing something wrong...

```
$ git lg
35c16c3244c (HEAD -> suse-review, tag: SUSE-SUSE15.3-shim-20210329_standalone) Included additional rpms for building the image, modified Dockerfile to reflect this

$ podman -f Dockerfile build --build-arg ARCHITECTURE=x86_64 -t sles_shim:15.4 --no-cache
...
STEP 13: RUN pesign --hash --padding --in=/shim/usr/share/efi/$ARCHITECTURE/shim-sles.efi
hash: 17066c81bf4c73fb1c72bc582a7e3aad6ab5cdbca0a02684f2e4d575650d4322
--> 80d14808c7b
STEP 14: RUN sha256sum /shim/usr/share/efi/$ARCHITECTURE/shim-sles.efi
ef96e8c759f5ab0a23b842eafc21f46550f5bd04973f6d1154d7f7fbecf35c5a  /shim/usr/share/efi/x86_64/shim-sles.efi
STEP 15: COMMIT sles_shim:15.4
--> 062fba23c80
062fba23c8095f8c57489bc9cc9df7a4bcdc29407948109afe38bfb9fe224778
```

**Comment by jsegitz** [comment]
@martinezjavier did you pull the repo to refresh the tag? 35c16c3244c is the old, broken version. You should be on f10ce456129. I just retried on a fresh VM to ensure that everything is okay and for me it works:
# podman images
REPOSITORY  TAG     IMAGE ID  CREATED  SIZE

# git clone https://github.com/jsegitz/shim-review.git review && cd review

# git checkout SUSE-SUSE15.3-shim-20210329_standalone

# git log -1 | head -1
commit f10ce456129e691ebabeda28c37645a850d4eb62

# podman build -f Dockerfile --build-arg ARCHITECTURE=x86_64 -t sles_shim:15.4 --no-cache
<snip>
STEP 13: RUN pesign --hash --padding --in=/shim/usr/share/efi/$ARCHITECTURE/shim-sles.efi
hash: cf376dd1772694b2223fd56aa97c90ca34bbc1a68eafe34aaeb14b4b9e387320
--> 1fd9a7e0ae0
STEP 14: RUN sha256sum /shim/usr/share/efi/$ARCHITECTURE/shim-sles.efi
fa63816b0e0cc6e2cdce94bd389a8b155000a93d0182d2f8874f3b0d7753bb7a  /shim/usr/share/efi/x86_64/shim-sles.efi

**Comment by martinezjavier** [comment]
Strange, I did a git remote update but probably the tag didn’t refresh. I’ll have time to re-test in an hour or so. Thanks

**Comment by martinezjavier** [comment]
@jsegitz It does match now, thanks and sorry for the noise!

```
STEP 13: RUN pesign --hash --padding --in=/shim/usr/share/efi/$ARCHITECTURE/shim-sles.efi
hash: cf376dd1772694b2223fd56aa97c90ca34bbc1a68eafe34aaeb14b4b9e387320
--> 5bfbc71c335
STEP 14: RUN sha256sum /shim/usr/share/efi/$ARCHITECTURE/shim-sles.efi
fa63816b0e0cc6e2cdce94bd389a8b155000a93d0182d2f8874f3b0d7753bb7a  /shim/usr/share/efi/x86_64/shim-sles.efi
STEP 15: COMMIT
```

**Comment by martinezjavier** [comment]
@jsegitz this looks good to me.

I was able to reproduce the binaries, their SBAT section are correct and I believe the answers to the questions are good.

**Comment by jsegitz** [comment]
Thank you very much for the review. I'll improve my process so next time I'll directly submit a podman file that build from scratch :)

**Comment by steve-mcintyre** [comment]
I can reproduce both binaries here fine, and the SBAT data looks good

**Comment by steve-mcintyre** [comment]
shim patches all look sane enough AFAICS

**Comment by steve-mcintyre** [comment]
kernel and grub look sane
approving...

**Comment by jsegitz** [comment]
great. Thank you all three for your work on the review!
