### ISSUE TITLE
Shim 15.4 for openSUSE

### ISSUE THREAD

**Issue by jsegitz** [rhboot/shim-review#157]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 https://github.com/jsegitz/shim-review/tree/openSUSE-shim-x86_20210409
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

###### What organization or people are asking to have this signed:
SUSE, https://suse.com/

###### What product or service is this for:
openSUSE 15.3

###### Please confirm this as the origin your shim.
We use 15.4 shim + 
- shim-arch-independent-names.patch: use the Arch-independent names.
- shim-bsc1177315-verify-eku-codesign.patch: Check CodeSign in the signer's EKU
- shim-bsc1177789-fix-null-pointer-deref-AuthenticodeVerify.patch: fix NULL pointer dereference in AuthenticodeVerify
- shim-change-debug-file-path.patch: change path of debug file
- remove_build_id.patch: don't add the build id from the resulting binaries
- shim-bsc1184454-allocate-mok-config-table-BS.patch: Handle 'Failed to lookup EFI memory descriptor' errors

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Major linux distribution

###### How do you manage and protect the keys used in your SHIM?
The key is installed in a machine with restricted physical and system access.
Shim binaries do not include private portions of the key.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
n/a

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
yes

###### fixed ?
yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
We use this pattern:
shim.${distro_id},${distro_sbat},${distro_name},%{name},%{version},mail:security-team@suse.de

So for this shim:
shim.opensuse,1,The openSUSE project,shim,15.4,mail:security-team@suse.de

##### Were your old SHIM hashes provided to Microsoft ?
yes

##### grub2 bootloaders can not be verified ?
yes (rotated signing key, old shims are blacklisted)

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?
upstream grub-2.04 with patches for all currently discussed security issues

###### If your SHIM launches any other components, please provide further details on what is launched
it doesn't

###### please provide further details on what is launched and how it enforces Secureboot lockdown
n/a

###### apply. Please describe your strategy.
We switched to a new certificate

###### How do the launched components prevent execution of unauthenticated code?
GRUB and kernel are patched to enforce Secure Boot.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
no

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
5.3.18 +
# Module signing / secure boot
patches.suse/KEYS-Make-use-of-platform-keyring-for-module-signatu.patch

# Lock down functions for UEFI secure boot
patches.suse/0001-security-lockdown-expose-a-hook-to-lock-the-kernel-down.patch
patches.suse/0002-efi-Add-an-EFI_SECURE_BOOT-flag-to-indicate-secure-boot-mode.patch
patches.suse/0003-efi-Lock-down-the-kernel-if-booted-in-secure-boot-mode.patch
patches.suse/0004-efi-Lock-down-the-kernel-at-the-integrity-level-if-b.patch

# Using the hash in MOKx to blacklist kernel module, FATE#316531
patches.suse/0001-MODSIGN-do-not-load-mok-when-secure-boot-disabled.patch
patches.suse/0001-efi-add-a-function-to-convert-the-status-code-to-a-s.patch
patches.suse/0002-efi-show-error-messages-only-when-loading-certificat.patch
patches.suse/0003-MODSIGN-load-blacklist-from-MOKx.patch
patches.suse/0004-MODSIGN-checking-the-blacklisted-hash-before-loading.patch

# Hibernation Signature Verification FATE#316350
patches.suse/0001-security-create-hidden-area-to-keep-sensitive-data.patch
patches.suse/0002-hibernate-avoid-the-data-in-hidden-area-to-be-snapsh.patch
patches.suse/0003-x86-KASLR-public-the-function-for-getting-random-lon.patch
patches.suse/0005-efi-generate-secret-key-in-EFI-boot-environment.patch
patches.suse/0006-efi-allow-user-to-regenerate-secret-key.patch
patches.suse/0007-PM-hibernate-encrypt-hidden-area.patch
patches.suse/0008-PM-hibernate-Generate-and-verify-signature-for-snaps.patch
patches.suse/0009-PM-hibernate-prevent-EFI-secret-key-to-be-regenerate.patch
patches.suse/0010-PM-hibernate-a-option-to-request-that-snapshot-image.patch
patches.suse/0011-PM-hibernate-require-hibernate-snapshot-image-to-be-.patch

###### What changes were made since your SHIM was last signed?
Signing key was changed to ensure no old grub/kernel can not be booted

###### What is the SHA256 hash of your final SHIM binary?
pesign --hash --padding --in=usr/share/efi/x86_64/shim-opensuse.efi
hash: dbb4eba9d114c4db02e9f8da1d98179f842ef324052439e197b130dc3e7b1cd5
usr/share/efi/x86_64/shim-opensuse.efi
a1514bf4b73a8be4d4f0cb4c6954e495f6c831951acfe38133e8316ec43eeda1  usr/share/efi/x86_64/shim-opensuse.efi

**Comment by julian-klode** [comment]
Are there seriously no public opensuse docker images that we have to resort to these image file shenanigans?

**Comment by jsegitz** [comment]
There are, the dockerfile is included and you can use it to build it. The image was included for your convenience since for SLES I had to do it this way anyway

**Comment by martinezjavier** [comment]
This looks good to me.

* The checksum of the built binary matches the one listed in the issue template [0]
* SBAT section matches what's listed in the issue template.
* Answers to the questions are good.

[0]
```
$ podman build -f Dockerfile --no-cache
...
STEP 9: RUN pesign --hash --padding --in=/shim/usr/share/efi/x86_64/shim-opensuse.efi
hash: dbb4eba9d114c4db02e9f8da1d98179f842ef324052439e197b130dc3e7b1cd5
--> f77ab47c9cf
STEP 10: RUN sha256sum /shim/usr/share/efi/x86_64/shim-opensuse.efi
a1514bf4b73a8be4d4f0cb4c6954e495f6c831951acfe38133e8316ec43eeda1  /shim/usr/share/efi/x86_64/shim-opensuse.efi
STEP 11: COMMIT
--> 40e1fb32002
```

**Comment by jsetje** [comment]
I don't see any additional issues.

**Comment by jsegitz** [comment]
thank you very much for the review

**Comment by julian-klode** [comment]
Closing since accepted.
