### ISSUE TITLE
shim for Fedora 28

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#16]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/rhboot/shim/tree/15
 - [x] completed README.md file with the necessary information
https://github.com/vathpela/shim-review/blob/fedora-28/README.md
 - [x] shim.efi to be signed
https://github.com/vathpela/shim-review/blob/fedora-28/shimia32.efi
https://github.com/vathpela/shim-review/blob/fedora-28/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/vathpela/shim-review/blob/fedora-28/fedora-ca.cer
 - [x] any extra patches to shim via your own git tree or as files
None.
 - [x] any extra patches to grub via your own git tree or as files
So, so many.  They include the well-known Secure Boot patchset.
https://github.com/rhboot/grub2/tree/fedora-28
 - [x] build logs
https://github.com/vathpela/shim-review/blob/fedora-28/build.log

###### What organization or people are asking to have this signed:
`Peter Jones for Fedora Linux`

###### Version of shim:
`shim 15`

###### Sysdev Submission ID:
`2216411 and 2216412`

###### What product or service is this for:
`This is for Fedora Linux`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`We're a major linux distro`

**Comment by haobinnan** [comment]
Why should your shim be reviewed? Am I eligible for censorship?

**Comment by XuShaohua** [comment]
@vathpela Hi Peter.

The Fedora 28-beta ISO link provided in README.md, http://download.fedoraproject.org/fedora/linux/development/28/Server/x86_64/iso/Fedora-Server-dvd-x86_64-28-20180409.n.0.iso,  cannot be accessed any more. Any advice?

**Comment by cyphermox** [comment]
I installed from Fedora-Server-netinst-x86_64-28-20180411.n.0.iso; system is fully up to date (AFAIK), I installed updated gnu-efi* packages provided.

However, the instructions were missing make, gcc from the install, those did not get pulled by 'dnf builddep'.

There's lots of differences between the binaries provided in the submission and the binaries built here; so I suspect there are other differences in the build dependencies.

**Comment by cyphermox** [comment]
I reviewed this and I can fully reproduce the builds now:

[root@fedora26 ~]# sha256sum /home/mtrudel/shim-review/shimx64.efi /builddir/build/RPMS/x86_64/usr/share/shim/15-1.fc28/x64/shimx64.efi 
dee13a19cda89d84c96c18816d65109bef23ff1773302fd51adec5db4eeadff9  /home/mtrudel/shim-review/shimx64.efi
dee13a19cda89d84c96c18816d65109bef23ff1773302fd51adec5db4eeadff9  /builddir/build/RPMS/x86_64/usr/share/shim/15-1.fc28/x64/shimx64.efi
[root@fedora26 ~]# sha256sum /home/mtrudel/shim-review/shimia32.efi /builddir/build/RPMS/x86_64/usr/share/shim/15-1.fc28/ia32/shimia32.efi 
0c6ea16c12d7bd77fbfadf2b6be467dbcf634568ef2356bd6a3b1531f9e4b0bb  /home/mtrudel/shim-review/shimia32.efi
0c6ea16c12d7bd77fbfadf2b6be467dbcf634568ef2356bd6a3b1531f9e4b0bb  /builddir/build/RPMS/x86_64/usr/share/shim/15-1.fc28/ia32/shimia32.efi
[root@fedora26 ~]# 

I find the submissions 2216411 and 2216412 acceptable for signing.
