### ISSUE TITLE
2018-04-25 Isoo

### ISSUE THREAD

**Issue by haobinnan** [rhboot/shim-review#17]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/rhboot/shim/tree/15
 - [x] completed README.md file with the necessary information
https://github.com/haobinnan/shim-review/blob/isoo-shim-20180609/README.md
 - [x] shim.efi to be signed
https://github.com/haobinnan/shim-review/blob/isoo-shim-20180609/shim/shimia32.efi
https://github.com/haobinnan/shim-review/blob/isoo-shim-20180609/shim/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/haobinnan/shim-review/blob/isoo-shim-20180609/Isoo.cer
 - [x] any extra patches to shim via your own git tree or as files
None.
 - [x] any extra patches to grub via your own git tree or as files
None.
 - [x] build logs
https://github.com/haobinnan/shim-review/blob/isoo-shim-20180609/shim%20build%20logs/shim_build_ia32.log
https://github.com/haobinnan/shim-review/blob/isoo-shim-20180609/shim%20build%20logs/shim_build_x64.log

###### What organization or people are asking to have this signed:
秦皇岛易之数软件开发有限公司
Isoo (Qinhuangdao) software development Co., Ltd.
Qinhuangdao, Hebei, China
Isoo is a software developer for data recovery, disk utilities and system backup.
Managing Director: Hao Binnan

###### Version of shim:
https://github.com/rhboot/shim/tree/15
Version: 15

###### Sysdev Submission ID:
ID: 2313431 (Name: shimx64_v15)
ID: 2313430 (Name: shimia32_v15)

###### What product or service is this for:
This is Isoo’s Linux-based operating system. We are going to develop some function based on the OS, such as resize partition, back up & restore operating system, etc.

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Isoo wants to employ Secure Boot for building a trusted operating system from Shim to GRUB to the kernel to signed filesystem partitions. Secure Boot is the first step for this.
Isoo would like customers to be able to run Isoo’s Linux-based system on any amd64(64Bit) and x86(32Bit) device without disabling Secure Boot.

https://github.com/haobinnan/shim-review/tree/isoo-shim-20180609

**Comment by haobinnan** [comment]
@vathpela
Hi Peter,
Can you please help review this new submission? If there is any issue about it, please let me know.

**Comment by haobinnan** [comment]
Hello, @vathpela @cyphermox @mjg59
Could you please review my shim 15? I’ve done the Pre-submission testing in line with the steps here: https://blogs.msdn.microsoft.com/windows_hardware_certification/2013/12/03/pre-submission-testing-for-uefi-submissions/

Thanks!
Best regards,
Hao Binnan

**Comment by haobinnan** [comment]
Hello, @vathpela @cyphermox @mjg59
Could you please review my shim 15? I’ve done the Pre-submission testing in line with the steps here: https://blogs.msdn.microsoft.com/windows_hardware_certification/2013/12/03/pre-submission-testing-for-uefi-submissions/

Thanks!
Best regards,
Hao Binnan

**Comment by cyphermox** [comment]
I have been able to rebuild shimx64.efi:
149b73a02a4890d6f04718cf26a4a5d08420ab6d9b93f2666e046fac368e470e  shimx64.efi

However, I am for now unable to rebuild shimia32.efi -- gnuefi is not found, and I'm a little concerned with how you do the cross building for gnu-efi as a build-dependency of shim. It looks like you're trying to build it on amd64, but you're not listing exactly which compilers and libraries you use for that (libc6-dev-i386-cross?) or if you're building this directly on an i386 system.

Furthermore, the grub binaries look smaller than they should be; but I have not yet looked into rebuilding them to check.

**Comment by haobinnan** [comment]
That can only examine the 64-bit shim, and 32 bits are not taken into account for the time being, because the Microsoft dashboard was submitted separately, resulting in 2 id numbers.@cyphermox

**Comment by haobinnan** [comment]
Allow the ID first: 2313431 (Name: shimx64_v15) @cyphermox

**Comment by haobinnan** [comment]
Hello,
Thank you for your response @cyphermox
Could you please inform Microsoft to approve signing my file if the reviewing of shimx64.efi(ID:2313431 (Name: shimx64_v15)) is approved? We can review shimia32.efi sometime in the future.
The binaries of shimia32.efi is built on Ubuntu 18.04 LTS (amd64). And a deploying building environment of sh file is provided (BuildDeployment.sh), which is in the following link: https://github.com/haobinnan/shim-review/tree/isoo-shim-20180609
Furthermore, it has been taken too long to review my issue, could you please deal with it as soon as possible? Thanks a million! @cyphermox 
BTW, I'd like to join the review board if possible, as I want to make a little contribution for your work. :)
Best regards,
Hao Binnan

**Comment by cyphermox** [comment]
Ok, I have been able to succesfully rebuild both shimia32 and shimx64. The grub binaries have been clarified as well (seems to be exactly the same code as in Debian, modulo fewer modules installed in the Isoo binaries, has fallback to unsigned kernel) -- .text and .data look to be the same size / offsets at least.

I have had a quick look at the kernel patches provided as well, but I have less experience reviewing those, but nothing jumped out as obviously wrong.

root@artistic-marmot:/isoo/shim# sha256sum shim*.efi
1594af28cb86b5a1c8834a31fd08e6c1452ade63c3a1326d036258c908af666e  shimia32.efi
149b73a02a4890d6f04718cf26a4a5d08420ab6d9b93f2666e046fac368e470e  shimx64.efi

**Comment by haobinnan** [comment]
Hello, has the censorship passed

**Comment by haobinnan** [comment]
One more question. May I know what I should do next? Do I need to contact Microsoft to sign my submission by myself? Or you will do that for me?

**Comment by haobinnan** [comment]
One more question. May I know what I should do next? Do I need to contact Microsoft to sign my submission by myself? Or you will do that for me?
@cyphermox
