### ISSUE TITLE
Shim 15.4 + bugfixes for Deepin

### ISSUE THREAD

**Issue by deepin-secureboot** [rhboot/shim-review#172]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
   https://github.com/deepin-secureboot/shim-review/tree/deepin-shim-15.4
 - [x] completed README.md file with the necessary information
   https://github.com/deepin-secureboot/shim-review/blob/deepin-shim-15.4/README.md
 - [x] shim.efi to be signed
   https://github.com/deepin-secureboot/shim-review/blob/deepin-shim-15.4/shimx64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
   https://github.com/deepin-secureboot/shim-review/blob/deepin-shim-15.4/deepin-uefi-ca.der
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
   Not used
 - [x] any extra patches to shim via your own git tree or as files
   N/A
 - [x] any extra patches to grub via your own git tree or as files
   N/A
 - [x] build logs
   https://github.com/deepin-secureboot/shim-review/blob/deepin-shim-15.4/logs.txt

###### What organization or people are asking to have this signed:
Deepin: https://www.deepin.org/en/

###### What product or service is this for:
Deepin V20.

###### Please confirm this as the origin your shim.
Yes, we are using the source from https://github.com/rhboot/shim/releases/download/15.4/shim-15.4.tar.bz2

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Deepin is yet another linux distribution based on Debian GNU/Linux. It has been actively maintained since 2011. Deepin has kept in the top 20 on distrowatch for last few years. It is an amazing distribution, and for compatible reason, we here submit our siging request for shim.

###### How do you manage and protect the keys used in your SHIM?
The key is stored in isolated standalone server which is placed in secure area with limited access.

###### Do you use EV certificates as embedded certificates in the SHIM?
No.

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
No.

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
Yes, we use kernel 5.10 with this patch included

###### fixed ?
Yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.04,https://www.gnu.org/software/grub/
grub.deepin,1,Deepin,grub2,2.04-17,https://www.deepin.org/en/
```
```
sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd,1,Firmware update daemon,fwupd,1.5.7,https://github.com/fwupd/fwupd
fwupd-deepin,1,Deepin,fwupd,1.5.7-3,https://www.deepin.org/en/
```
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.deepin,1,Deepin,shim,15.4-1,https://www.deepin.org/en/
```
All new UEFI binaries that are yet to be built with SBAT support will
follow the agreed SBAT variable pattern and we will add Deepin specific
entries for them.

##### Were your old SHIM hashes provided to Microsoft ?
This is the first submission

##### grub2 bootloaders can not be verified ?
New grub2 builds with CVE fix will be signed with new signing EV certificate.

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?

Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?

upstream grub2 2.04-17 , from Debian bullseye

###### If your SHIM launches any other components, please provide further details on what is launched

It will load fwupdate, fwupd as already mentioned above.

###### please provide further details on what is launched and how it enforces Secureboot lockdown

grub2 launches Linux kernel

###### apply. Please describe your strategy.

Not applicable, grub2 leaf certificate rotated in Deepin  shim

###### How do the launched components prevent execution of unauthenticated code?

Will not start unsigned programs

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?

 5.10 with secure boot supported.

###### What changes were made since your SHIM was last signed?

Bug and security fixes.
Changelog (since version 15-4).
Don-t-call-QueryVariableInfo-on-EFI-1.10-machines.patch
fix-broken-ia32-reloc.patch
fix-import_one_mok_state.patch
MOK-BootServicesData.patch

###### What is the SHA256 hash of your final SHIM binary?

55c8267a5e1f427a00abae043d07e6228c8807889850e5a03260ba384ce3ee2a shimx64.efi

**Comment by christopherco** [comment]
- [x] shim reproducible? *Yes*
```
root@d30a84e8b6c1:/build# sha256sum shim/shimx64.efi
55c8267a5e1f427a00abae043d07e6228c8807889850e5a03260ba384ce3ee2a  shim/shimx64.efi

shim-review$ sha256sum shimx64.efi
55c8267a5e1f427a00abae043d07e6228c8807889850e5a03260ba384ce3ee2a  shimx64.efi
```
- [x] shim .sbat contents accurate? *Yes (with nit)*
```
shim-review$ objdump -s -j .sbat shimx64.efi

shimx64.efi:     file format pei-x86-64

Contents of section .sbat:
 cd000 73626174 2c312c53 42415420 56657273  sbat,1,SBAT Vers
 cd010 696f6e2c 73626174 2c312c68 74747073  ion,sbat,1,https
 cd020 3a2f2f67 69746875 622e636f 6d2f7268  ://github.com/rh
 cd030 626f6f74 2f736869 6d2f626c 6f622f6d  boot/shim/blob/m
 cd040 61696e2f 53424154 2e6d640a 7368696d  ain/SBAT.md.shim
 cd050 2c312c55 45464920 7368696d 2c736869  ,1,UEFI shim,shi
 cd060 6d2c312c 68747470 733a2f2f 67697468  m,1,https://gith
 cd070 75622e63 6f6d2f72 68626f6f 742f7368  ub.com/rhboot/sh
 cd080 696d0a73 68696d2e 64656570 696e2c31  im.shim.deepin,1
 cd090 2c446565 70696e2c 7368696d 2c31352e  ,Deepin,shim,15.
 cd0a0 342d312c 68747470 733a2f2f 7777772e  4-1,https://www.
 cd0b0 64656570 696e2e6f 72672f65 6e2f0a    deepin.org/en/.
```
nit: issue submission lists your vendor sbat as `shim.deepin,1,Deepin,shim,15.4,https://www.deepin.org/en/` while the vendor sbat in the binary is `shim.deepin,1,Deepin,shim,15.4-1,https://www.deepin.org/en/`.

**Comment by deepin-secureboot** [comment]
Thanks for your review, I will update SBAT

**Comment by deepin-secureboot** [comment]
@christopherco  Please review the submission again

**Comment by steve-mcintyre** [comment]
Things reproduce here fine, and all the shim patches look sane. Everything else I've already reviewed and found good in #151.

Let's approve this.

(Warning - you'll want to update your fwupd package to 1.5.9+ for a fix in the SBAT data it produces)

Finally: I'm trying to steer shim development discussions into being more open, and we have a mailing list now: https://lists.einval.com/cgi-bin/mailman/listinfo/efi

**Comment by christopherco** [comment]
> @christopherco Please review the submission again

LGTM.

**Comment by haobinnan** [comment]
We noticed that you created a new email list, may I know if the old email list (https://lists.freedesktop.org/mailman/listinfo/shim-review) will continue to be used?
@steve-mcintyre
