### ISSUE TITLE
Shim 15.4 for SUSE expanded support

### ISSUE THREAD

**Issue by jsegitz** [rhboot/shim-review#174]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
   https://github.com/jsegitz/shim-review/tree/SUSE-Expanded_Support_platform_8-shim-20210510
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

###### What organization or people are asking to have this signed:
SUSE, https://suse.com/

###### What product or service is this for:
SLES Expanded Support platform 8, provided within the 
"SUSE Linux Enterprise Server with Expanded Support" program,
https://www.suse.com/products/expandedsupport/

###### Please confirm this as the origin your shim.

Shim-15.4 is used, with the following patches on top:
0001-Fix-a-broken-file-header-on-ia32.patch: Fix a broken file header on ia32
Don-t-call-QueryVariableInfo-on-EFI-1.10-machines.patch: Don't call QueryVariableInfo() on EFI 1.10 machines
MOK-BootServicesData.patch: mok: allocate MOK config table as BootServicesData
fix-import_one_mok_state.patch: Fix handling of ignore_db and user_insecure_mode
They're in the src.rpm and additionally in shim_patches.tar

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
SLES ES is a publicly offered product.

###### How do you manage and protect the keys used in your SHIM?
The key is installed in a machine with restricted physical and system access.
Shim binaries do not include private portions of the key.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
N/A

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
Yes

###### fixed ?
Yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

This is the entry that was added for shim:
shim.sles_es,1,SLES Expanded Support platform,shim,15.4-4,security@suse.com

All other components will follow the same convention:
shim.${distro_id},${distro_sbat},${distro_name},%{name},%{version},security@suse.com

##### Were your old SHIM hashes provided to Microsoft ?
Yes

##### grub2 bootloaders can not be verified ?
Yes (rotated signing key, old key is revoked via dbx).

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?
Upstream grub2-2.02+ patched up to address above mentioned security issues, among others:
grub2-2.02-90.el8

grub2-2.02-90.el8_3.1.src.rpm is included in extra-srpms.tar with all of the patches. For an easier review this
is identical to the RH submissions

###### If your SHIM launches any other components, please provide further details on what is launched
It additionally launches fwupd.

###### please provide further details on what is launched and how it enforces Secureboot lockdown
N/A

###### apply. Please describe your strategy.
Switch to a new key has been made, and old key has been revoked via dbx.

###### How do the launched components prevent execution of unauthenticated code?
GRUB and kernel are patched to enforce Secure Boot.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
kernel-4.18.0+ with lockdown patches (recently, kernel-4.18.0-240.22.1.el8_3)

###### What changes were made since your SHIM was last signed?
Signing key was changed, old key was revoked to ensure no old grub/kernel can be booted.
Shim version updated to upstream 15.4+additional patches.

###### What is the SHA256 hash of your final SHIM binary?
shimia32.efi hash: 53accd2cbe376d0186a128fbafba1a304258f609778fdfc01a50d59cd321f1ee
shimia32.efi sha256: fc91dd873f7a93c8a23c447e27bdf72150caf486c769d0f983226cb3345c955c

shimx64.efi hash: 6efcd62a89ea9f6faab73acac4abefe3693d2904a539788864a767e203375036
shimx64.efi sha256: 2e5ef8470ee09ebd3fb05cb365511a113968fdd748232e7f7f19a91cbdc1c4f3

**Comment by jsegitz** [comment]
I'm sorry that there's no official source for the container image. I know this makes reviewing it harder for you, but for this product we don't have it :(

**Comment by YustasSwamp** [comment]
Can it be built on another SLES container image which is available?

**Comment by jsegitz** [comment]
We'll give it a try but it's unlikely to work since these systems are very different. I doubt we'll get to a bit identical built, but lets see

**Comment by jsegitz** [comment]
We likely found a way to build this on a public image. I'll update this issue as soon as we have tested this. Please don't spent time on reviewing this until then. Than you

**Comment by jsegitz** [comment]
I updated my submission (to be found under the linked tag): 

Build instructions for a CentOS 8 image (for use with sudo or root user and default podman setup):

- Have shim*.efi files and shim-unsigned-x64-15.4-4.el8.1.src.rpm from this submission in the current directory.
- Run the build. Note that Podman will attempt copying a SRPM and prebuilt shims for comparison from a current directory on the host:
  `podman build -f Dockerfile.with-centos8`

**Comment by steve-mcintyre** [comment]
> I updated my submission (to be found under the linked tag):
> 
> Build instructions for a CentOS 8 image (for use with sudo or root user and default podman setup):
> 
>     * Have shim*.efi files and shim-unsigned-x64-15.4-4.el8.1.src.rpm from this submission in the current directory.
> 
>     * Run the build. Note that Podman will attempt copying a SRPM and prebuilt shims for comparison from a current directory on the host:
>       `podman build -f Dockerfile.with-centos8`

Do you mean something like:

```
Step 10/30 : COPY shimia32.efi /
COPY failed: stat /var/lib/docker/tmp/docker-builder968959145/shimia32.efi: no such file or directory
```

I don't know what I'm meant to be looking at here. That's not helping me review things...

**Comment by jsegitz** [comment]
Sorry for the trouble. I retried on openSUSE Tumbleweed and Fedora 33 and I can't recreate the problem. My steps
```
git clone https://github.com/jsegitz/shim-review
cd shim-review/
git checkout SUSE-Expanded_Support_platform_8-shim-20210510
podman build -f Dockerfile.with-centos8
```
result in the desired result on both systems. Can you please tell me your steps so I can try to recreate it?

**Comment by julian-klode** [comment]
We really ought to have GitHub actions for this, I think some submissions had, but we need to build a sample one I suppose.

**Comment by steve-mcintyre** [comment]
OK, so I've started again from scratch and things have worked fine this time. Looks like it might have been a local problem - apologies :-/

**Comment by steve-mcintyre** [comment]
- Builds reproduce here now fine
- SBAT looks ok
- shim patches look ok
- quick skim of grub and kernel looks ok

Things look good to me, but I'd like a second reviewer to take a look too.

**Comment by jsegitz** [comment]
Thank you very much for your review!

**Comment by martinezjavier** [comment]
I've reviewed this and it looks good to me:

* Could reproduce the builds using the instructions from comment https://github.com/rhboot/shim-review/issues/174#issuecomment-845032952.
* The answers to the questions and SBAT entry are good for me.
* Components and patches are what's expected.

**Comment by jsegitz** [comment]
thank you very much for the review
