### ISSUE TITLE
Securaze SHIM sign request - securaze-shim-x64-20210601

### ISSUE THREAD

**Issue by richiesecuraze** [rhboot/shim-review#177]
Make sure you have provided the following information:

 - [X] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 https://github.com/securaze/shim-review/releases/tag/securaze-shim-x64-20210601
 
 - [x] completed README.md file with the necessary information
https://github.com/securaze/shim-review/blob/securaze-shim-x64-20210601/README.md

 - [x] shim.efi to be signed
https://github.com/securaze/shim-review/blob/securaze-shim-x64-20210601/shimx64.efi

 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/securaze/shim-review/blob/securaze-shim-x64-20210601/certificate/codesign_ev_2021.cer

 - [x] any extra patches to shim via your own git tree or as files
Shim 15.4 with upstream patches only
https://github.com/richiesecuraze/shim/releases/tag/15.4.sec1

 - [x] build logs
https://github.com/securaze/shim-review/blob/securaze-shim-x64-20210601/buildlog.txt

 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries
https://github.com/securaze/shim-review/blob/securaze-shim-x64-20210601/docker/Dockerfile

###### What organization or people are asking to have this signed:
SECURAZE GmbH based in Vienna, Austria

###### What product or service is this for:
SECURAZE Work & Command

###### Please confirm this as the origin your shim.
We used the 15.4 repo with the latest upstream patches

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
SECURAZE offers SW solutions for secure data erasure on x86_64 and ARM based machines as well as smartphones - in order to properly sanitize data Securaze needs to be either locally or PXE booted on the machines to erase, as those typically come with Secureboot enabled as default it makes the process much easier for the end user.

###### How do you manage and protect the keys used in your SHIM?
Certificate is stored on a HW token in secure storage at the office with keyphrase only know to 3 members of the team

###### Do you use EV certificates as embedded certificates in the SHIM?
yes

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
n/a

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
Yes, we are using Kernel 5.12.8 that has commit 75b0cea7bf307f362057cc778efe89af4c615354 embedded

###### fixed ?
Yes, we are using Debian downstream GRUB2

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

sbat 1 SBAT Version sbat 1 https://github.com/rhboot/shim/blob/main/SBAT.md 
shim 1 UEFI shim shim 1 https://github.com/rhboot/shim 
shim.securaze 1 Securaze shim 15.4 https://www.securaze.com/shim

##### Were your old SHIM hashes provided to Microsoft ?
`[your text here]`

##### grub2 bootloaders can not be verified ?
No, this is our first submission.

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
Downstream Debian like implementation.

###### What is the origin and full version number of your bootloader (GRUB or other)?
GRUB2 2.04-17 from Debian sid http://deb.debian.org/debian/pool/main/g/grub2/grub2_2.04-17.debian.tar.xz

###### If your SHIM launches any other components, please provide further details on what is launched
Only GRUB2 is launched from SHIM

###### please provide further details on what is launched and how it enforces Secureboot lockdown
N/A - only launching the Linux kernel.

###### apply. Please describe your strategy.
N/A first submission

###### How do the launched components prevent execution of unauthenticated code?
Stock Debian GRUB2 and Upstream Kernel with all relevant patches enabled

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No, only GRUB2 used.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Stock Linux Kernel 5.12.8 with all required Secure Boot patches

###### What changes were made since your SHIM was last signed?
N/A - first submission

###### What is the SHA256 hash of your final SHIM binary?
b3a877887a3965483aa9bcc267f5b9e1ae9eb25986ec99d57ca40efd5234ee48

**Comment by steve-mcintyre** [comment]
- amd64 build reproduces ok
- no patches applied, just adding SBAT data to upstream git HEAD 05875f3aed1c90fe071c66de05744ca2bcbc2b9e
- SBAT data looks fine
- embedded EV cert looks fine
- kernel and grub sound ok

**Comment by steve-mcintyre** [comment]
Last thing: I don't have any link to confirm this shim is from Securaze.

To check that, I've just sent mails to Markus and Richie, each containing a set of random words. Please copy those word lists here to confirm that you at least have control of those email addresses.

**Comment by devhem** [comment]
Hello Steve,
please find attached the words i received from you.

====
spotlessness starvings Kurd inspire adjudicates consummations introspective 
====

**Comment by richiesecuraze** [comment]
Hello Steve,

here you go with the sent words:

====
forbiddings disinclination sojourning bumble blinders indistinct docketed 
====

Cheers,
 Richie

**Comment by steve-mcintyre** [comment]
Thanks guys, all good!

**Comment by richiesecuraze** [comment]
Thank you very much @steve-mcintyre 

Highly appreciated!
