### ISSUE TITLE
shim for Solaris

### ISSUE THREAD

**Issue by mattroisang** [rhboot/shim-review#18]
Make sure you have provided the following information:

 - [ ] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/rhboot/shim/tree/0.9
 - [ ] completed README.md file with the necessary information
https://github.com/mattroisang/shim-review/blob/Solaris-shim-amd64-2018-05-24/README.md
 - [ ] shim.efi to be signed
https://github.com/mattroisang/shim-review/blob/Solaris-shim-amd64-2018-05-24/shim.efi
 - [ ] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/mattroisang/shim-review/blob/Solaris-shim-amd64-2018-05-24/public.cer
 - [ ] any extra patches to shim via your own git tree or as files
Yes
 - [ ] any extra patches to grub via your own git tree or as files
Yes
 - [ ] build logs
https://github.com/mattroisang/shim-review/blob/Solaris-shim-amd64-2018-05-24/build.log

###### What organization or people are asking to have this signed:
Oracle Solaris

###### Version of shim:
Version 0.9

###### Sysdev Submission ID:
2291429

###### What product or service is this for:
Oracle Solaris OS

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
To secure boot solaris OS.

**Comment by haobinnan** [comment]
Is the version of shim 0.9 a bit dated?

**Comment by mattroisang** [comment]
Yes :) our security team doesn't see a need to upgrade yet.

**Comment by haobinnan** [comment]
Need to send a review via shim-review@lists.freedesktop.org?

**Comment by haobinnan** [comment]
My review request has been issued for one month. Shim review board members did not help me to review. I did not know which part was wrong and I felt that work efficiency was slightly lower.

**Comment by mattroisang** [comment]
Really, did you finally get it reviewed via shim-review@lists.freedesktop.org?  Thanks for the heads up.

**Comment by haobinnan** [comment]
Hi, your shim review, have the latest news yet?

**Comment by cyphermox** [comment]
Do you have clear instructions on how one can reproduce this build? We have the packages, but how are you building the binaries?

I've downloaded Solaris 11.4 beta ISO / USB but I am currently blocked due to KVM issues with EHCI.

**Comment by haobinnan** [comment]
@cyphermox Is it possible to review my shim? Thank you.
https://github.com/rhboot/shim-review/issues/17

**Comment by mattroisang** [comment]
@cyphermox Hi Mathieu, I am not sure what you mean by clear instructions, the build should be straightforward.  You just need to download shim 0.9 and apply all my patches in order to build on Solaris systems.  Thanks.

**Comment by cyphermox** [comment]
The point is; I haven't touched Solaris in years. Are you building the shim by extracting each seperate build dependency locally and running make, make install, or are these packaged somewhere already?

What patches are applied on top of the upstream GRUB2 tree to support Secure Boot?

**Comment by cyphermox** [comment]
Reviewed the shim patches.

Nothing looks crazy, build infra changes are expected for the differences between SunOS and GNU.

The only thing I'm noting is 03-netboot.patch reminds me of an issue with dots that IIRC was due to an old version of gnu-efi, but maybe I'm dreaming things -- in any case, not an issue to block review.

All that will be left for me is to rebuild the binaries.

**Comment by mattroisang** [comment]
@cyphermox Hi, we extract the build locally, apply the patch, run make. 

Because our unix kernel is not in efi format, we cannot validate using the shim's function.  We made changes in GRUB2 to verify the unix kernel.

**Comment by mattroisang** [comment]
@cyphermox Hi, were you able to rebuild the binaries?  Thanks.

**Comment by vathpela** [comment]
> Because our unix kernel is not in efi format, we cannot validate using the shim's function. We made changes in GRUB2 to verify the unix kernel.

Please show us those patches as well.

**Comment by mattroisang** [comment]
Our code for GRUB2 is at http://www.oracle.com/technetwork/opensource/systems-solaris-1562786.html.  Download the zip file and look under osnet\usr\src\grub\.  To build the shim, you should not need the GRUB2 patches.

**Comment by julian-klode** [comment]
Closing this review requests as it is from before 2019, and likely not valid anymore. Also note that we just added some new questions, and if you submit a new review request with the current question set, also include a Dockerfile to build the shim to not slow down review.
