### ISSUE TITLE
Shim 15.4+patches for PuzzleOS

### ISSUE THREAD

**Issue by pcmoore** [rhboot/shim-review#182]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
> https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20210615

 - [x] completed README.md file with the necessary information
> https://github.com/puzzleos/uefi-shim_review/blob/puzzleos-shim-x86_64-20210615/README.md

 - [x] shim.efi to be signed
> https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20210615/artifacts.20210615183313
> See the file `shimx64.efi`.

 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
> https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20210615/config/certs
> A copy of our vendor db can be seen in the file `vendor_db.esl` file in the artifacts directory.

 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
> We have not added any hashes to the vendor db, only the certificates mentioned above.

 - [x] any extra patches to shim via your own git tree or as files
> The Dockerfile has information on the source of the included patches and the `shim-git_commit_extra.log` file in the artifacts directory contains the output of `git log -p 15.4..HEAD` after all of the patches have been applied.

 - [x] any extra patches to grub via your own git tree or as files
 > We do not use GRUB, we boot directly into the Linux Kernel from shim using a stripped down systemd-boot EFI stub.  More information can be found in our README.md file.

 - [x] build logs
>  https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20210615/artifacts.20210615183313
> See the file `build.log`.

 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries
> https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20210615
> See the file `Dockerfile`.

###### What organization or people are asking to have this signed:
`Cisco Systems, Inc.`

###### What product or service is this for:
`PuzzleOS, a Linux based appliance OS used in a number of Cisco products.`

###### Please confirm this as the origin your shim.
`The included Dockerfile uses the 15.4 tag as a base after verifying the GPG signature, all patches are applied on top of this base.`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`PuzzleOS is designed to run on any platform that supports UEFI Secure Boot and the easiest way to support the largest number of systems is to have a shim bootloader signed by Microsoft.`

###### How do you manage and protect the keys used in your SHIM?
`The certificates included in our shim build are built from keys stored in Cisco's corporate key management system.  Access to this system is tightly controlled and operations are restricted to authorized individuals.`

###### Do you use EV certificates as embedded certificates in the SHIM?
`No.`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`No, only certificates are stored in the vendor db file.`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
`We do not currently plan to sign Linux Kernels prior to v5.10 which contains 75b0cea7bf30 ("ACPI: configfs: Disallow loading ACPI tables when locked down").`

###### fixed ?
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.`
`The "stubby" EFI shim: https://github.com/puzzleos/stubby`

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
`Our shim build uses the SBAT information below:`
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.puzzleos,1,PuzzleOS,shim,15.4-202106-1,https://github.com/puzzleos
```
`As we only plan on booting Linux Kernels directly from shim using stubby, I expect that we would adopt the following pattern for our kernel EFI binaries:`
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
stubby.puzzleos,1,PuzzleOS,stubby,%{stubby_version},https://github.com/puzzleos/stubby
linux.puzzleos,1,PuzzleOS,linux,%{kernel_version},https://github.com/puzzleos
```

##### Were your old SHIM hashes provided to Microsoft ?
`This is a new vendor submission, there are no old hashes to submit.`

##### grub2 bootloaders can not be verified ?
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.`
`The "stubby" EFI shim: https://github.com/puzzleos/stubby`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.`
`The "stubby" EFI shim: https://github.com/puzzleos/stubby`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.`
`The "stubby" EFI shim: https://github.com/puzzleos/stubby`

###### If your SHIM launches any other components, please provide further details on what is launched
`We only plan to use our shim build to launch the Linux Kernel.`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.`
`The "stubby" EFI shim: https://github.com/puzzleos/stubby`

###### apply. Please describe your strategy.
`This is a new vendor submission, complete with new CA certificates.  Further, we have no plans to boot GRUB with our shim build.`

###### How do the launched components prevent execution of unauthenticated code?
`We rely on the existing Linux Kernel mechanisms to prevent the execution of unwanted code.`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`No.  We do not use our shim to load any additional bootloaders.`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`We do not currently plan to sign Linux Kernels prior to v5.10.`

###### What changes were made since your SHIM was last signed?
`This is a new vendor submission, we have not previously signed any shim builds.`

###### What is the SHA256 hash of your final SHIM binary?
```
% sha256sum *
70dc3beb4286d3340951dc9acdb35e181b62c0928db6f2d6a8cab1f015513114  build.log
529fc0875c8977188e026243c4a21135f27ed3906c18c83fa7503deafb5255b0  fbx64.efi
901996120d2b0203f34511cff88f583b561972a73ce6634d3ce24c46d62dfa80  mmx64.efi
4016498a09d68e0f9f98a792aeca3902e6cbffe4063445116656ee63b4947bf9  shim-git_commit_extra.log
20a8950afd167faf959b98f946adcbb997d7cedebc7ce18b108757e4a2072e43  shimx64.efi
0950f70d1dce96ac227a09f4885356df2527de75891b6ca5c703a0af800bbccb  vendor_db.esl
```

**Comment by steve-mcintyre** [comment]
shimx64.efi doesn't reproduce here:
 ---> Running in 3488540f1b66
529fc0875c8977188e026243c4a21135f27ed3906c18c83fa7503deafb5255b0  fbx64.efi
901996120d2b0203f34511cff88f583b561972a73ce6634d3ce24c46d62dfa80  mmx64.efi
0726f4e91e52e82506bebcf00637c96743fd2f92c3b071a1db6d6fe2bbb755e1  shimx64.efi

(already had to tweak the Dockerfile to get it to run here :-()

**Comment by pcmoore** [comment]
> shimx64.efi doesn't reproduce here:
> ---> Running in 3488540f1b66
> 529fc0875c8977188e026243c4a21135f27ed3906c18c83fa7503deafb5255b0 fbx64.efi
> 901996120d2b0203f34511cff88f583b561972a73ce6634d3ce24c46d62dfa80 mmx64.efi
> 0726f4e91e52e82506bebcf00637c96743fd2f92c3b071a1db6d6fe2bbb755e1 shimx64.efi

I suspect that is due to the known reproducible build problem (patch from main below); I saw other shim-review submissions that were approved with this problem so I didn't cherry-pick the patch, I'll go ahead and do that.
 
https://github.com/rhboot/shim/commit/05875f3aed1c90fe071c66de05744ca2bcbc2b9e

> (already had to tweak the Dockerfile to get it to run here :-()

Can you elaborate on what you had to tweak?  It works without problem on the systems I've tried it on (using `podman` as a `docker` replacement).  I'm happy to adjust the Dockerfile if you give me a clue on what broke for you.

**Comment by steve-mcintyre** [comment]
two things:

1. the keyservers are not working reliably for me here, so it won't verify the tag (meh, I can check the source so I commented that bit)

2. I guess podman is less picky in syntax terms than docker is; docker failed with:
```
 ---> b2bdbcd0e64c
Step 16/22 : COPY config/* /shim
When using COPY with more than one source file, the destination must be a directory and end with a /
```

(adding the trailing / made it work)

**Comment by steve-mcintyre** [comment]
(yes, I detest docker for this kind of crap :-/)

**Comment by pcmoore** [comment]
> two things:
> 
> 1. the keyservers are not working reliably for me here, so it won't verify the tag (meh, I can check the source so I commented that bit)

Ah, okay, that's fair.  I didn't really want to use the sks-keyservers.net pool, but it was the only keyserver that worked when I was editing the Dockerfile.  @vathpela do you have your rhboot/shim tag signing GPG key available anywhere else in a format that is suitable for use with `git verify-tag X`?

> 2. I guess podman is less picky in syntax terms than docker is; docker failed with:
> 
> ```
>  ---> b2bdbcd0e64c
> Step 16/22 : COPY config/* /shim
> When using COPY with more than one source file, the destination must be a directory and end with a /
> ```
> 
> (adding the trailing / made it work)

Sorry about that, I just adjusted the Dockerfile.

**Comment by pcmoore** [comment]
> @vathpela do you have your rhboot/shim tag signing GPG key available anywhere else in a format that is suitable for use with `git verify-tag X`?

Answering my own questions, oddly enough it looks like the Ubuntu keyserver has pjones@redhat GPG key with a user ID attached.  I'm also going to edit the repo/Dockerfile to include an offline copy of the GPG key to avoid keyserver problems.

**Comment by vathpela** [comment]
If that fails, https://pjones.fedorapeople.org/pjones.gpg can be treated as a canonical (if not necessarily up to date) copy.

**Comment by pcmoore** [comment]
Hmm, even with the post-processing patch I'm still not getting a reproducible build with a F34 base for the container.  That's not good.  I'll start hunting around, but does this sound familiar to anyone?

**Comment by pcmoore** [comment]
Switching to Ubuntu as a base doesn't appear to work either, I've built against 21.04, 20.04, and 18.04 and I'm not getting a reproducible build.  Maddening.

**Comment by pcmoore** [comment]
Interestingly, both `fbx64.efi` and `mmx64.efi` build bit-for-bit identical copies each time, it is just `shimx64.efi` which is problematic.

**Comment by steve-mcintyre** [comment]
Probably worth looking at hexdumps to compare - see what's changing

**Comment by steve-mcintyre** [comment]
Doing that here, I see:

```
--- /shim/prebuilt-shimx64.dump 2021-06-28 22:45:06.000000000 +0000
+++ /shim/shimx64.dump  2021-06-28 22:45:04.000000000 +0000
@@ -11,7 +11,7 @@
 000000a0  00 58 06 00 00 00 00 00  00 20 02 00 00 20 02 00  |.X....... ... ..|
 000000b0  00 00 00 00 00 00 00 00  00 10 00 00 00 02 00 00  |................|
 000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
-000000d0  00 d0 0c 00 00 04 00 00  9d f3 0e 00 0a 00 00 00  |................|
+000000d0  00 d0 0c 00 00 04 00 00  de ea 0e 00 0a 00 00 00  |................|
 000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000100  00 00 00 00 10 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -31139,10 +31139,10 @@
 00079a20  64 4d 61 63 68 69 6e 65  3a 20 4c 69 6e 75 78 20  |dMachine: Linux |
 00079a30  78 38 36 5f 36 34 20 78  38 36 5f 36 34 20 78 38  |x86_64 x86_64 x8|
 00079a40  36 5f 36 34 20 47 4e 55  2f 4c 69 6e 75 78 20 24  |6_64 GNU/Linux $|
-00079a50  0a 24 43 6f 6d 6d 69 74  3a 20 30 36 30 32 61 66  |.$Commit: 0602af|
-00079a60  30 61 65 34 36 38 37 66  38 35 34 64 61 36 63 62  |0ae4687f854da6cb|
-00079a70  61 63 38 36 65 35 39 64  36 65 63 32 61 34 35 64  |ac86e59d6ec2a45d|
-00079a80  35 64 20 24 0a 00 00 00  00 00 00 00 00 00 00 00  |5d $............|
+00079a50  0a 24 43 6f 6d 6d 69 74  3a 20 37 30 30 36 33 35  |.$Commit: 700635|
+00079a60  34 30 37 33 33 34 37 32  37 62 31 33 30 38 39 37  |407334727b130897|
+00079a70  64 30 32 61 34 33 36 31  63 30 31 61 66 66 30 64  |d02a4361c01aff0d|
+00079a80  66 37 20 24 0a 00 00 00  00 00 00 00 00 00 00 00  |f7 $............|
 00079a90  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00079aa0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00079ab0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

**Comment by steve-mcintyre** [comment]
You can fix the second diff by just defining "COMMIT_ID" in your make command line

**Comment by steve-mcintyre** [comment]
In fact, doing that gives me a consistent build from one attempt to the next

**Comment by steve-mcintyre** [comment]
OK, so the reason for your differences is **just** the way you do the cherry-picking. Git doesn't guarantee a consistent git SHA hash each time you do that. On 6 equivalent runs I've just done I get a HEAD commit hash of:

```
fe7b7a4e8793a17e4005c69b3f52f3e38c62f132
b68bbe9ab6a85160f901e18d1608a50017200aca
ccbc3509e3dd6703192aabbccdb521ee12aaf717
b4e95cd9daa950f6d5c148f39efb32b6644edfae
8192abace764c0f290cc088f91367defc6af742b
69d396ad8762317c670cd0f29a087ed08d3e1577
```

Rather than mess around with the cherry-picking, just maintain your own tree on github and apply the patches you need there. Then you'll get a consistent set of git hashes and we can move on here.

**Comment by pcmoore** [comment]
Thanks for the help/diagnosis Steve!  It looks like all I need to do is set the `$GIT_COMMITTER_DATE` to a fixed value to ensure that the git log/HEAD is consistent from build to build.

The change is pretty much just a one-liner addition to the Dockerfile (e.g. `ARG GIT_COMMITTER_DATE="..."`) are you okay with that or do you still want me to fork and setup our own tree on GitHub?

**Comment by steve-mcintyre** [comment]
That's up to you, I was thinking it would be clearer and probably less effort in the long run. But so long as you end up with a reproducible build that's what matters.

**Comment by pcmoore** [comment]
Okay, I'll re-test the new build and update the branch/tag in this PR.

Thanks again for the help.

**Comment by steve-mcintyre** [comment]
you're welcome!

**Comment by pcmoore** [comment]
Let's try this again :)

I added a new patch to the branch taking into account the discussion thus far in this thread, and force pushed the existing tag to point to this new review HEAD (all the links above should work and point to the new build, Dockerfile, etc.).  If you notice anything awry, or have any more concerns, please let me know.

Thanks for your patience!

**Comment by steve-mcintyre** [comment]
OK, build reproduces for me \o/

**Comment by steve-mcintyre** [comment]
- shim patches all look ok to me
- 3 embedded CA certs seems a little OTT, but you've explained that. Each looks OK to me
- no grub, so lots of questions there are moot
- only very recent Linux, so ditto
- Looking at stubby now

**Comment by steve-mcintyre** [comment]
I **think** it looks OK, but I'm not 100% confident reviewing this alone so I'm afraid I'm going to have to flag your submission to ask for another reviewer to take a second look as well.

In the meantime, I've just sent mail to both of the Cisco email addresses listed in your README file. Please paste the word lists in each here to confirm.

**Comment by pcmoore** [comment]
> I **think** it looks OK, but I'm not 100% confident reviewing this alone so I'm afraid I'm going to have to flag your submission to ask for another reviewer to take a second look as well.

Thanks Steve.  The extra review makes sense to me considering the different approach we are taking.  If there is anything I can do to help answer any questions or make all of you more comfortable with our usage just let me know.

> In the meantime, I've just sent mail to both of the Cisco email addresses listed in your README file. Please paste the word lists in each here to confirm.

Tada!
```
====
meres tracheae derailing harpoon walker author stodgier
====
```

**Comment by hallyn** [comment]
+1
====
taros instills pebbles baronet Everett gist consisting
====

**Comment by pcmoore** [comment]
A gentle poke to keep this issue active and check to see if there are any estimates on how many additional reviews are required and how long we might expect that to take?

I understand this is almost exclusively volunteer run so please don't take this as a "WHY AREN"T YOU REVIEWING MY SUBMISSION NOW?!?!?" post - I get that you folks have a lot of work and little support - I just need to make sure the appropriate expectations are set here with product management.

Thanks.

**Comment by Doncuppjr** [comment]
I would expect stubby needs an sbat entry, not just sbat support. It's for sure gonna take some additional testing to confirm that your stubby correctly supports secureboot and sbat protections. Why didn't you just grub?

**Comment by pcmoore** [comment]
> I would expect stubby needs an sbat entry, not just sbat support. It's for sure gonna take some additional testing to confirm that your stubby correctly supports secureboot and sbat protections.

It is important to remember that stubby, just like systemd-boot upon which it is based, is not responsible for performing any UEFI SB enforcement.  The stubby EFI stub is combined with the kernel image, initramfs, and kernel command line to form a single EFI binary which is in turn executed directly by the UEFI shim.  The stubby stub is not a traditional bootloader, in fact it is not a bootloader at all, it is simply some bits of EFI code which are combined to form a self-contained EFI bootable Linux kernel (+initramfs +cmdline) that which can be signed and thus protected by UEFI SB.

From a UEFI SB security enforcement perspective the UEFI shim verifies the stubby composed kernel image, both the signature and the SBAT section, and then executes the stubby composed kernel and your system is up and running.

> Why didn't you just use grub? I am not aware of anything that systemd-boot can do, that grub can't.

Two main reasons:

1. We wanted to leverage the UEFI SB authentication mechanisms to protect the kernel+initramfs+cmdline; while GRUB would allow us to authenticate the initramfs (and cmdline?) it is a separate mechanism from UEFI SB.
2. Reducing the amount of code executed between the UEFI firmware and the kernel was seen as a positive.  Boothole and friends seem to confirm that this is a worthy goal.

**Comment by Doncuppjr** [comment]
So why even have stubby at all? You can boot the kernel directly from the shim without it.......

**Comment by julian-klode** [comment]
@Doncuppjr They already explained that they want to embed an initramfs and the kernel command line in the binary; that is the standard way to do it (in Ubuntu we use the systemd stub directly for Ubuntu core)

**Comment by Doncuppjr** [comment]
@julian-klode I did read that. I was just pointing out that the systemd-boot is not necessary to achieve those goals. He also said he was after minimal code between the shim and kernel. So why have any at all?

**Comment by julian-klode** [comment]
@Doncuppjr But it _is_ necessary. You're just wasting everyone's time right now

**Comment by Doncuppjr** [comment]
@julian-klode I am certainly not trying to waste anybody's time. The kernel supports embedded cmdline with attached initramfs and efi stub without any additional code, so what does this approach actually yield?

**Comment by pcmoore** [comment]
For a variety of product reasons beyond the scope of this discussion it is not desirable for us to build the initramfs or kernel cmdline into the kernel image, the systemd-boot/stubby based approach is more more appealing to us and when we discussed this earlier with the UEFI shim developers they were supportive of the idea.

**Comment by Doncuppjr** [comment]
@pcmoore So then I guess your saying this is not technically required, but convenient?

**Comment by pcmoore** [comment]
The systemd-boot/stubby based approach is ***required*** for our solution.

**Comment by Doncuppjr** [comment]
After reviewing your README.md, it appears to me that you only intend to use this on Cisco products, and or internally. According to the Microsoft UEFI Signing requirements, this disqualifies your shim. You should instead sign it with your private key and add the certificate to Secure Boot database of any products or other systems you wish to run this OS.

**Comment by pcmoore** [comment]
We plan to use this build of shim in a variety of Cisco appliance products, some of these appliance products are software appliances that run on generic x86_64 systems produced by a variety of hardware vendors, not just Cisco.  In order to successfully run on these systems with UEFI SB enabled we need a UEFI shim signed by Microsoft.

@Doncuppjr while I appreciate the extra review, it is safe to assume we are not total idiots :)

**Comment by Doncuppjr** [comment]
@pcmoore I never make an assumption one way or the other on such subjects. I am just doing my part to protect this ecosystem and keep it from descending into the chaos.

I am unable to find any publicly available references to PuzzleOS. It's not clear how you intend to distribute this OS, and to whom. It's also not clear to me why such a private OS would need general access to any machine with an MS SB database.

**Comment by pcmoore** [comment]
> I am unable to find any publicly available references to PuzzleOS.

We are in the process of generalizing our base platform and we plan to release that as an Open Source project, hence the https://github.com/puzzleos GH org.

> It's not clear how you intend to distribute this OS, and to whom. It's also not clear to me why such a private OS would need general access to any machine with an MS SB database.

*"We plan to use this build of shim in a variety of Cisco appliance products, some of these appliance products are software appliances that run on generic x86_64 systems produced by a variety of hardware vendors, not just Cisco. In order to successfully run on these systems with UEFI SB enabled we need a UEFI shim signed by Microsoft."*

**Comment by Doncuppjr** [comment]
I was able to compile the stubby.efi binary, but when I used stubby-smash.2.sh to join the vmlinuz initrd cmdline and sbat files, I did not end up with a working EFI application. I get the following error(s).

Section 0 is inside image headers
Failed to load image: Unsupported
start_image() returned Unsupported

**Comment by pcmoore** [comment]
That is because stubby is currently using a simple, and likely incorrect way of adding a SBAT section.  Taken from the "stubby-smash.2.sh" script:
```sh
exec objcopy \
	"--add-section=.cmdline=$arg_cmdline" \
		"--change-section-vma=.cmdline=0x30000" \
	"--add-section=.linux=$arg_kernel" \
		"--change-section-vma=.linux=0x2000000" \
	"--add-section=.initrd=$arg_initrd" \
		"--change-section-vma=.initrd=0x3000000" \
	"--add-section=.sbat=$arg_sbat" \
		"--set-section-alignment=.sbat=512" \
	"$STUBBY" "$arg_output"
```

... while these looked reasonable given some of the early SBAT guidance, experience has shown that it simply does not work.  This is why I have yet to tag a stubby release with SBAT support.  We will likely solve this in stubby the same way we handle it in our [QEMU+OVMF+SWTPM development environment](https://github.com/puzzleos/uefi-dev) with our ["hello world" test binaries](https://github.com/puzzleos/uefi-dev/blob/main/utils/Makefile):
```Makefile
%.sbat.o: %.sbat.csv
	${CC} -x c -c -o $@ /dev/null
	objcopy \
		--add-section .sbat=$< \
		--set-section-flags .sbat=contents,alloc,load,readonly,data \
		$@
```

... this is similar to how shim does it's own SBAT section.

However, regardless of what the actual stubby SBAT solution ends up being, it is important to remember that our approach does not rely on stubby performing any SBAT enforcement, or really any UEFI Secure Boot enforcement for that matter.  If stubby gets it "wrong", as it does currently, shim will correctly fail to execute it - which is the right thing to do! :)

We will correct the SBAT implementation in stubby, it is critical to our solution, but considering that stubby is not asked to perform any UEFI SB enforcement actions as well as the lengthy shim review and signing delays we wanted to get our shim submitted for review as soon as possible.

**Comment by pcmoore** [comment]
A small but important update to our submission's [README.md](https://github.com/puzzleos/uefi-shim_review/blob/puzzleos-shim-x86_64-20210615/README.md), I am leaving Cisco on Wednesday, July 14th so I have promoted @hallyn to the primary security contact (he was previously the secondary contact) and added @tych0 as the new secondary contact.

In order to make the change I added another commit to the submission branch and updated the tag so all of the links above should continue to work; the commit in question, https://github.com/puzzleos/uefi-shim_review/commit/ab5ee112c9f8ad09409d526893e0368e04fc464d, changed only the README.md and none of the submission's shim code or build artifacts.

**Comment by joylatten** [comment]
Hi. We are deciding to replace one of the commits in our shim.  (For further detail see the PR#381 referenced just above.) Would this require a new submission in a new issue? I am not sure how to proceed.

**Comment by julian-klode** [comment]
I think that would be for the best as you can't edit this one.

**Comment by joylatten** [comment]
@julian-klode thanks! I will re-submit. For my clarity, when we need to update shim in future, we would go thru this process again?

**Comment by julian-klode** [comment]
Yes!
