### ISSUE TITLE
SBAT revoke process?

### ISSUE THREAD

**Issue by TBOpen** [rhboot/shim-review#186]
Hello,

I needed to move from Ubuntu grub2 to grub2-unsigned so need to revoke a given SBAT.  What is the process to do that?  

Thanks.

**Comment by Thinstation** [comment]
Report the SBAT to MS.

**Comment by TBOpen** [comment]
Sounds like a plan, but where/how?  I looked in the control panel for signing and nothing there to report SBAT to revoke.

**Comment by Thinstation** [comment]
Why would a grub2 sbat need to be revoked? What did you do?

**Comment by TBOpen** [comment]
has partial updates due to Ubuntu changing to -unsigned

**Comment by Thinstation** [comment]
So.....Just make a new grub image and sign with your sbat and key.

**Comment by TBOpen** [comment]
I have a new one and a new SBAT, I just need to have the old SBAT for it revoked.   I already have a back channel to MS that I asked before here, so I'm sure they will get back to me at some point if that is on them.

**Comment by Thinstation** [comment]
Why does a grub-image need to be revoked? What is the security risk of allowing the sbat entry?
