### ISSUE TITLE
Cumulus Linux

### ISSUE THREAD

**Issue by cbrune** [rhboot/shim-review#19]
Make sure you have provided the following information:

 - [X] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/CumulusNetworks/shim-review/tree/cumulus-shim-x64-20180612
 - [X] completed README.md file with the necessary information
https://github.com/CumulusNetworks/shim-review/blob/cumulus/README.md
 - [X] shim.efi to be signed
https://github.com/CumulusNetworks/shim-review/blob/cumulus/shimx64.efi
 - [X] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/CumulusNetworks/shim-review/blob/cumulus/cumulus-uefi-cert.der
 - [X] any extra patches to shim via your own git tree or as files
https://github.com/CumulusNetworks/shim-review/blob/cumulus/0001-CUMULUS-add-initial-debian-directory.patch
 - [X] any extra patches to grub via your own git tree or as files
The bootloader is the version of grub2 shipping with Ubuntu 18.04 with the secure-boot patchset. Here's the source repo: https://git.launchpad.net/~ubuntu-core-dev/grub/+git/ubuntu/tag/?id=debian/2.02-2ubuntu8
 - [X] build logs
https://github.com/CumulusNetworks/shim-review/blob/cumulus/shim-build.log

###### What organization or people are asking to have this signed:
`Cumulus Networks, Inc.`
IANA Enterprise Number 40310

###### Version of shim:
`https://github.com/rhboot/shim/releases/tag/15`

###### Sysdev Submission ID:
Note: Sysdev is deprecated as of June 2018.  The new MS UEFI File signing service is located here:
https://developer.microsoft.com/en-us/dashboard/hardware/filesign/

Using the new service, our sub-mission ID is `13813503929849373`.

###### What product or service is this for:
`Cumulus Linux`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`Cumulus Linux is a Linux distribution for white box network switches. Secure Boot must be enabled going forward, as such we need a signed shim binary.`

**Comment by cbrune** [comment]
Hello -- checking to see if anyone has started looking at this request yet.

**Comment by vathpela** [comment]
The (noble) attempt to make this easy to verify actually makes it *harder* to verify - it makes it easy to produce the same .efi file and check the sha256sum, but makes that fairly opaque.  So I wind up just re-creating the steps manually.  Also, just pointing to a git repo with a branch that has the debianization patch added would be easier to verify; that way we don't need to verify the contents of the shim tarball.

All that said, I have recreated this build exactly, and this submission looks to be in good order.

**Comment by cbrune** [comment]
Sorry for the extra hassle -- I thought it would help :)

Super thanks for the review!!
