### ISSUE TITLE
shim 15.4 + patch for Trusted Disk

### ISSUE THREAD

**Issue by ifankner** [rhboot/shim-review#191]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag  
https://github.com/Rohde-Schwarz/shim-review/tree/rohdeschwarz-shim-x64-20210711
 - [x] completed README.md file with the necessary information  
https://github.com/Rohde-Schwarz/shim-review/blob/rohdeschwarz-shim-x64-20210711/README.md
 - [x] shim.efi to be signed  
https://github.com/Rohde-Schwarz/shim-review/blob/rohdeschwarz-shim-x64-20210711/shimx64.efi
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)  
https://github.com/Rohde-Schwarz/shim-review/blob/rohdeschwarz-shim-x64-20210711/rs-uefi-cs.der
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )  
No vendor_db is used.
 - [x] any extra patches to shim via your own git tree or as files  
https://github.com/Rohde-Schwarz/shim-review/blob/rohdeschwarz-shim-x64-20210711/patches/msabi.patch  
https://github.com/Rohde-Schwarz/shim-review/blob/rohdeschwarz-shim-x64-20210711/patches/bypass_bootoptions.patch 
 - [x] any extra patches to grub via your own git tree or as files  
N/A 
 - [x] build logs  
https://github.com/Rohde-Schwarz/shim-review/blob/rohdeschwarz-shim-x64-20210711/build.log

###### What organization or people are asking to have this signed:
`Rohde & Schwarz Cybersecurity GmbH`

###### What product or service is this for:
`Trusted Disk full-disk encryption`

###### Please confirm this as the origin your shim.
Yes, we are using `https://github.com/rhboot/shim/releases/download/15.4/shim-15.4.tar.bz2`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`Trusted Disk provides full-disk encryption for internal and external storage devices and protects data from unauthorized access. With a signed SHIM bootloader we are able to use the secure boot feature to ensure that each of the files in the boot chain are unmodified.`

###### How do you manage and protect the keys used in your SHIM?
`The private key is stored on hardware token with restricted access.`

###### Do you use EV certificates as embedded certificates in the SHIM?
`No.`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`No vendor_db is used.`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
`No Linux kernel is used.`

###### fixed ?
`No GRUB bootloader is used.`

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

**shim**

    sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
    shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
    shim.rscs,1,Rohde & Schwarz Cybersecurity GmbH,shim,15.4,https://www.rohde-schwarz.com/cybersecurity

**trusted disk**

    sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
    tdisk.rscs,1,Rohde & Schwarz Cybersecurity GmbH,tdisk,1,https://www.rohde-schwarz.com/cybersecurity

##### Were your old SHIM hashes provided to Microsoft ?
`This is just a patched version of our first SHIM submission.`

##### grub2 bootloaders can not be verified ?
`No GRUB bootloader is used.`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`No GRUB bootloader is used.`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`No GRUB bootloader is used.`

###### If your SHIM launches any other components, please provide further details on what is launched
`The SHIM launches our pre-boot authentication component that decrypts the system and boots a Windows operating system.`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`No GRUB bootloader is used.`

###### apply. Please describe your strategy.
`This is just a patched version of our first SHIM submission.`

###### How do the launched components prevent execution of unauthenticated code?
`The integrity of each file in our boot chain is verified by checking the validity of the digital signature when using the LoadImage/StartImage functions.`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`No.`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`No Linux kernel is used.`

###### What changes were made since your SHIM was last signed?
`Added a patch to bypass the bootoption parsing and second stage loader name assembly. This code failed on some systems and produced a non-bootable name for the second stage loader. Because we are using a hardcoded path and filename for the second stage loader, we just bypass this code with this patch.`

###### What is the SHA256 hash of your final SHIM binary?
`BD62EE850723B2EFDE4C413900BA117E881CB5AA2F45D0F03F87389737577F0F`

**Comment by ifankner** [comment]
This request is the same code as the previously approved request [#148](https://github.com/rhboot/shim-review/issues/148). We just needed to add an additional patch to bypass the bootoption parsing and second stage loader name assembly. This code failed on some systems and produced a non-bootable name for the second stage loader (same as issue [#370](https://github.com/rhboot/shim/issues/370)). Due to the fact that we are using a hardcoded path and filename for the second stage loader, we just bypass this code with this patch.

To verify our shim bootloader, please use the following command:

`docker build https://github.com/Rohde-Schwarz/shim-review.git`

**Comment by julian-klode** [comment]
Accepted.
