### ISSUE TITLE
Shim 15.4 + critical patches for CloudReady

### ISSUE THREAD

**Issue by pnardini** [rhboot/shim-review#193]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
[neverware/shim-review@google-shim-20210713](https://github.com/neverware/shim-review/tree/google-shim-20210713)
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

###### What organization or people are asking to have this signed:
Google

###### What product or service is this for:
CloudReady

###### Please confirm this as the origin your shim.
We can confirm that all of our shim binaries are built from the referenced tarball.

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
CloudReady is a Linux distribution, forked from Chromium OS. We want to enable (and encourage) our user base to boot our OS with secure boot enabled.

###### How do you manage and protect the keys used in your SHIM?
Our keys are stored on a SafeNet eToken 5110 HSM that is under physical access control.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
We do not use this functionality

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
Yes, this commit is applied in our kernel but appears as 824d0b6225f3fa2992704478a8df520537cfcb56 https://github.com/neverware/kernel/commit/824d0b6225f3fa2992704478a8df520537cfcb56

###### fixed ?
All of the referenced CVEs are fixed in our GRUB2 fork

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
**shim SBAT** (https://raw.githubusercontent.com/neverware/shim-build/v6/sbat.csv)
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.cloudready,1,CloudReady,shim,15.4,https://github.com/neverware/shim-build
```
**grub2 SBAT** (https://raw.githubusercontent.com/neverware/grub2-build/main/container/sbat.csv)
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.06~rc1,https://www.gnu.org/software/grub/
grub.cloudready,1,CloudReady,grub2,2.06~rc1-1,https://github.com/neverware/grub2-build
```
We do not currently support fwupd / fwupdate.

##### Were your old SHIM hashes provided to Microsoft ?
Yes, our old vulnerable hashes have been sent to Microsoft for verification via email to ueficamanualreview@microsoft.com.

##### grub2 bootloaders can not be verified ?
This shim embeds a new certificate that has not yet been used to sign any released versions of our bootloader, effectively revoking all bootloader releases to date.

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?
The version of grub2 we build is based off of the RedHat fork:
https://github.com/rhboot/grub2/tree/fedora-34

We require a few additional changes on top of that, so we have our own
fork, currently based on the fedora-34 branch of RedHat's fork:
https://github.com/neverware/grub2

The tools that we use to build our fork of grub2 can be found here:
https://github.com/neverware/grub2-build

Here is a list of the changes we apply:

Two patches from the master branch of the upstream GNU repo
(http://git.savannah.gnu.org/gitweb/?p=grub.git) to fix warnings:

`bdf170d1018a500a7fea8d43677c5b4fc8812c74 (mdraid1x_linux: Fix gcc10 error -Werror=array-bounds)`
`68006d173291c6e972c4882d4fa40dc91a9c1d45 (zfs: Fix gcc10 error -Werror=zero-length-bounds)`

Two patches from ChromiumOS:
https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/3d20670d426f9e1864e8d87fe2344770ff09614a/sys-boot/grub/files/

`0001-Forward-port-ChromeOS-specific-GRUB-environment-vari.patch`
`0002-Forward-port-gptpriority-command-to-GRUB-2.00.patch`

A patch to fix compilation with rpm-sort disabled:

`Fix disabling gnus-rpm-sort grub2#46`

And a couple Neverware-authored patches to fix warnings:

`fbbdb83a8874cf808faae7a62643cb936986dd08 (Fix a sign-compare warning)`
`e37e9ced05e7406b60ef8df401126f0c65de4399 (Fix compilation warnings on 32-bit)`

###### If your SHIM launches any other components, please provide further details on what is launched
N/A

###### please provide further details on what is launched and how it enforces Secureboot lockdown
N/A

###### apply. Please describe your strategy.
We are changing to a new certificate.

###### How do the launched components prevent execution of unauthenticated code?
Our shim launches grub2 built with secure-boot support.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Our kernel is based on v5.4 and has secure boot enabled.

###### What changes were made since your SHIM was last signed?
1) We've updated to shim 15.4 with the following critical patches:
* https://github.com/rhboot/shim/pull/364
* https://github.com/rhboot/shim/pull/362
* https://github.com/rhboot/shim/pull/357
* https://github.com/rhboot/shim/pull/361

2) Our embedded EV code signing cert has been updated with a renewed version. The new cert now expires on 2022/09/22

###### What is the SHA256 hash of your final SHIM binary?
`f8c896b379dde11974324cd6b4920b6bce7e12d5a6ecef1fd2f0ea7ab570e4a1  shimia32.efi`
`eb0b333b209c59ae96aad58d1b8417a71a9f0653ed1133479b9da772601a3f9f  shimx64.efi`

**Comment by julian-klode** [comment]
Questions look OK, build reproduces, everything looks sensible.

I want to note that while the signing request is made as Google, the certificate is still issued to Neverware, but I guess that's fine.
