### ISSUE TITLE
Shim 15.4 for Rocky Linux 8

### ISSUE THREAD

**Issue by SherifNagy** [rhboot/shim-review#194]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

###### What organization or people are asking to have this signed:
`Rocky Enterprise Software Foundation`

###### What product or service is this for:
`Rocky Linux 8`

###### Please confirm this as the origin your shim.
`Yes, we are using shim 15.4 release tarball`

Review repo located at: [rocky-linux/shim-review@rockylinux-8-shim-x86_64-20210806](https://github.com/rocky-linux/shim-review/tree/rockylinux-8-shim-x86_64-20210806), which includes `README.md`, both `shim EFI binaries`, `rocky-root-ca.der` cert, `root.log` and `build.log`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`Rocky Linux is a community enterprise operating system designed to be 100% bug-for-bug compatible with RHEL and replacing CentOS 8 since it will be EOL this year`

###### How do you manage and protect the keys used in your SHIM?
`FIPS-140-2 level 2 certified HSM`

###### Do you use EV certificates as embedded certificates in the SHIM?
`No`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`We don't use vendor_db functionality in this build`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
We have validated that all those commits present:
```
475fb4e8b2f4444d1d7b406ff3a7d21bc89a1e6f
1957a85b0032a81e6482ca4aab883643b8dae06e
612bd01fc6e04c3ce9eb59587b4a7e4ebd6aff35
75b0cea7bf307f362057cc778efe89af4c615354
435d1a471598752446a72ad1201b3c980526d869
```
And the configuration setting `CONFIG_EFI_CUSTOM_SSDT_OVERLAYS` is disabled.

###### fixed ?
All those exists and the signed bootloaders are derived from grub 2.02 with all of the relevant patches.

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

On shim, we have:
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.rocky,1,Rocky Linux,shim,15.4-4,security@rockylinux.org

```

On grub2, we have:
```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.02,https://www.gnu.org/software/grub/
grub.rhel8,1,Red Hat Enterprise Linux 8,grub2,1:2.02-99.el8.1,mail:secalert@redhat.com
grub.rocky8,1,Rocky Linux 8,grub2,1:2.02-99.el8.1,mail:security@rockylinux.org

```

On fwupd, we have:
```
sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd,1,Firmware update daemon,fwupd,1.5.9,https://github.com/fwupd/fwupd
fwupd.rocky,1,Rocky Linux,fwupd,1.5.9,mail:security@rockylinux.org
```

##### Were your old SHIM hashes provided to Microsoft ?
`This is our first submission`

##### grub2 bootloaders can not be verified ?
`This is our first sumission`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`RHEL like implementationi`

###### What is the origin and full version number of your bootloader (GRUB or other)?
Same version as RHEL and code is here https://git.rockylinux.org/staging/rpms/grub2.git added our `certs` and `sbat` entry, this will build `grub2-2.02-99`

###### If your SHIM launches any other components, please provide further details on what is launched
We also have `fwupd`, which will have similar `.sbat provisions to grub2`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`None, only linux`

###### apply. Please describe your strategy.
`We are not reusing any previously used CA, this is our first submission`

###### How do the launched components prevent execution of unauthenticated code?
`Everything validates signatures using shim's protocol.`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`No`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
RHEL kernel and all signed kernels are all patched for the kernel boothole CVEs and have the `CONFIG_EFI_CUSTOM_SSDT_OVERLAYS` config option disabled.

###### What changes were made since your SHIM was last signed?
`This is our first submission`

###### What is the SHA256 hash of your final SHIM binary?
```
315ec4b433dedc218974cd24b290e7533da79fcd465329b7b387828506ba6bef  shimx64.efi
8d717005c7688fcc240d6975d5b4ffe5663e1607dfc4f432cf543a8c236f5fc4  shimia32.efi
```

**Comment by julian-klode** [comment]
We can review this, but please note that it will not boot on a variety of platforms #165. I guess RHEL hasn't build a new shim yet either, i don't recall?

**Comment by julian-klode** [comment]
Please also preserve the `.rhel8` SBAT entries such that your rebuild does not need to be revoked separately when there is a bug in the RHEL8 patch set.

**Comment by SherifNagy** [comment]
> We can review this, but please note that it will not boot on a variety of platforms #165. I guess RHEL hasn't build a new shim yet either, i don't recall? The list might be incomplete, I should try and sync it with the last Ubuntu and SUSE shims.

Thank you so much, I did look at the ticket, I will have a chat this evening with the rest of the team here and see if we can just import those patches, we won't be 1:1 with RHEL but will have to check that.

> Please also preserve the `.rhel8` SBAT entries such that your rebuild does not need to be revoked separately when there is a bug in the RHEL8 patch set.

For any package that uses SBAT? I can do that, I did notice some other RHEL based distros didn't preserve RHEL8 entries, but what you are saying does make sense.

I will update the shim-review repo with the changes and report back here

**Comment by julian-klode** [comment]
> For any package that uses SBAT? I can do that, I did notice some other RHEL based distros didn't preserve RHEL8 entries, but what you are saying does make sense.

Yeah, I just realized this today. If there's a bug in the RHEL patch sets for those components (mostly grub), someone will have to hunt down all derivatives and revoke them which could be messy, so doing it like Oracle Linux and including the RHEL lines simplifies that a lot.

**Comment by SherifNagy** [comment]
Will do that for grub2 then and see if it can be done with fwupd as well

**Comment by SherifNagy** [comment]
We cherry-picked the commits that has been merged to shim and fixed the grub2 `rhel8` sbat entry, I also updated the issue body with the new information and a path to the new shim-review repo

**Comment by SherifNagy** [comment]
Since this patch https://github.com/rhboot/shim/pull/379 just got merged, we updated our shim and our shim-review ticket, I assume this is the our "final" release being submitted for review, hope it didn't cause any troubles.

**Comment by julian-klode** [comment]
We noticed that install media fail to boot on some machines with rhboot/shim#379 applied, depending on what garbage the firmware puts into the automatically generated boot entries. rhboot/shim#393 adds a workaround for that, and rhboot/shim#399 is the big hammer.

**Comment by SherifNagy** [comment]
> We noticed that install media fail to boot on some machines with [rhboot/shim#379](https://github.com/rhboot/shim/pull/379) applied, depending on what garbage the firmware puts into the automatically generated boot entries. [rhboot/shim#393](https://github.com/rhboot/shim/pull/393) adds a workaround for that, and [rhboot/shim#399](https://github.com/rhboot/shim/pull/399) is the big hammer.

A new tag has been pushed with the mentioned patches along with the latest patches that merged into shim source code. we updated the main issue with the new hashes and tag that reflect the new changes

**Comment by SherifNagy** [comment]
@julian-klode is there anything else needed from our side to start the reviewing process?

**Comment by julian-klode** [comment]
I think right now it's complete, but can't say for sure, we'll know when somebody is free to review it

**Comment by SherifNagy** [comment]
Thanks @julian-klode

**Comment by SherifNagy** [comment]
Any time estimates regarding this review?

**Comment by 6sossomons** [comment]
Is there any update on the ETA for this to be implemented?

**Comment by lillolollo** [comment]
@julian-klode any news on this?

**Comment by julian-klode** [comment]
Accepted.

- This is a RHEL rebuild
- SBAT looks good
- Answers to questions look good
- shims build reproducibly

For future reviews, we'd prefer to use a docker image that's not specialized for shim, but used by normal users. I have verified that the image is derived from the public one by inspecting the layers.

**Comment by SherifNagy** [comment]
@julian-klode noted! thanks :)

**Comment by julian-klode** [comment]
@SherifNagy Did you get a signed shim back from MS? If so, please close the issue.

**Comment by SherifNagy** [comment]
@julian-klode yes, just last night actually :) will close the ticket now
