### ISSUE TITLE
Shim 15.4 + extra patch for EgoSecure

### ISSUE THREAD

**Issue by EgoSecure** [rhboot/shim-review#199]
Make sure you have provided the following information:

 - [X] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag  
 [EgoSecure/shim-review@egosecure-shim-x64-20211014](https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014)
 - [X] completed README.md file with the necessary information  
 https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/README.md
 - [X] shim.efi to be signed  
 https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/shim.efi
 - [X] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)  
 https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/egosecure.public.cer
 - [X] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )  
Not used
 - [X] any extra patches to shim via your own git tree or as files  
  Some patches from shim upstream (shim 15.4 critical regressions)  
  [Don't call QueryVariableInfo() on EFI 1.10 machines](https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/patches/0004-Don-t-call-QueryVariableInfo-on-EFI-1.10-machines.patch)  
  [Fix a broken file header on ia32 ](https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/patches/0002-Fix-a-broken-file-header-on-ia32.patch)  
  [Fix handling of ignore_db and user_insecure_mode](https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/patches/0001-Fix-handling-of-ignore_db-and-user_insecure_mode.patch)  
  [mok: allocate MOK config table as BootServicesData](https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/patches/0003-mok-allocate-MOK-config-table-as-BootServicesData.patch)  
  [Bypass boot options](https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/patches/0005-Bypass-boot-options.patch)  
 - [X] any extra patches to grub via your own git tree or as files  
 GRUB bootloader is not used
 - [X] build logs  
  https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/build.log
 - [X] a Dockerfile to reproduce the build of the provided shim EFI binaries  
  https://github.com/EgoSecure/shim-review/tree/egosecure-shim-x64-20211014/Dockerfile

###### What organization or people are asking to have this signed:
`EgoSecure is European software vendor developing Data Security products`  
`https://egosecure.com`

###### What product or service is this for:
`EgoSecure Full Disk Encryption`

###### Please confirm this as the origin your shim.
`Yes, we use 15.4 shim release https://github.com/rhboot/shim/releases/download/15.4/shim-15.4.tar.bz2`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`EgoSecure Full Disk Encryption secures data on laptops by applying sector level encryption with Pre-boot authentication.
We need to be signed because we want to distribute our product to our end users across the world. Our Pre-boot authentication has to support Secure Boot.
We have used a Microsoft SecureBoot signed Shim since 2018`

###### How do you manage and protect the keys used in your SHIM?
`The private key is stored on hardware token with restricted access`

###### Do you use EV certificates as embedded certificates in the SHIM?
`No`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`Not used`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
`Yes, this patch is included and applied`

###### fixed ?
`GRUB bootloader is not used`

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
`shim:`  
`shim.egosecure,1,EgoSecure GmbH a Matrix42 Company,shim,15.4,https://egosecure.com`

##### Were your old SHIM hashes provided to Microsoft ?
`Yes`

##### grub2 bootloaders can not be verified ?
`GRUB bootloader is not used`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`GRUB bootloader is not used`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`GRUB bootloader is not used`

###### If your SHIM launches any other components, please provide further details on what is launched
`The SHIM launches our pre-boot authentication component (custom second-state loader) that can perform user verification, system decryption actions, and boot a Windows OS or Linux kernel.`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`GRUB bootloader is not used`

###### apply. Please describe your strategy.
`GRUB bootloader is not used`

###### How do the launched components prevent execution of unauthenticated code?
`The integrity of each file in our boot chain is verified by checking the validity of the digital signature using shim's protocol.
All our componets have digital signature`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`No`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`Linux kernel 5.5.7, which has the all the required patches to enforce the secure boot`

###### What changes were made since your SHIM was last signed?
`We have added only one patch to fix boot on some systems`  
`Added a patch to bypass the boot option parsing. This code failed on some systems and produced a non-bootable name for the second stage loader. Because we are using custom filename for the second stage loader, we just bypass this code with this patch.`  

###### What is the SHA256 hash of your final SHIM binary?
`677a9a828a1f20db92d4e6d1d75ad17321db1dc5c3ce4504d75715c828275ed1  `

**Comment by EgoSecure** [comment]
Our previous shim review issue - Shim 15.4 for EgoSecure #169

**Comment by EgoSecure** [comment]
@steve-mcintyre @julian-klode
Can the submission be reviewed? We need new fixes to solve the problem of our customers.

**Comment by EgoSecure** [comment]
@pnardini 
we updated the build log file
thank you a lot
sorry for this error

**Comment by julian-klode** [comment]
I concur with @pnardini, this is accepted.
