### ISSUE TITLE
2017-11-16 Univention

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#2]
Date: Thu, 16 Nov 2017 12:27:08 +0100
Subject: [Shim-review] Request for review of SHIM-13 for Univention     Corporate Server

Hello,

I request our SHIM for Univention Corporate Server to be reviewed.
I followed <https://pjones.fedorapeople.org/shim-signing-procedure.html>.
The requested data is available from our download server:
<http://updates.software-univention.de/download/shim-13/>

The corresponding request at Microsoft is
<https://sysdev.microsoft.com/de-DE/Hardware/member/SubmissionCenter/UefiSubmissionDetails.aspx?SubmissionID=1970446>

If you have any questions, just contact me.

Thank you in advance.

Philipp

**Comment by cyphermox** [comment]
I think this one is affected by the shim 13 bug with sections:

```
└─[0] <> objdump -h shimx64.efi.FROM_CAB 

shimx64.efi.FROM_CAB:     file format pei-x86-64

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .eh_frame     00018498  0000000000005000  0000000000005000  00000400  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  1 .text         00093e96  000000000001e000  000000000001e000  00018a00  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  2 .reloc        0000000a  00000000000b2000  00000000000b2000  000aca00  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .data.ident   000000b8  00000000000b4000  00000000000b4000  000acc00  2**6
                  CONTENTS, ALLOC, LOAD, DATA
  4 .data         00029f68  00000000000b5000  00000000000b5000  000ace00  2**6
                  CONTENTS, ALLOC, LOAD, DATA
  5 .vendor_cert  00000340  00000000000df000  00000000000df000  000d6e00  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .dynamic      00000130  00000000000e0000  00000000000e0000  000d7200  2**3
                  CONTENTS, ALLOC, LOAD, DATA
  7 .rela         0001adc0  00000000000e1000  00000000000e1000  000d7400  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  8 .rela.plt     00000018  00000000000fbdc0  00000000000fbdc0  000f23c0  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  9 .dynsym       0000efe8  00000000000fc000  00000000000fc000  000f2600  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA

```

**Comment by julian-klode** [comment]
Closing this review requests as it is from before 2019, and likely not valid anymore. Also note that we just added some new questions, and if you submit a new review request with the current question set, also include a Dockerfile to build the shim to not slow down review.
