### ISSUE TITLE
shim 15.4-6 for Uos

### ISSUE THREAD

**Issue by Zeno-sole** [rhboot/shim-review#201]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 https://github.com/linuxdeepin/shim-review/tree/uos-shim-15.4-amd64-and-ia32
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

###### What organization or people are asking to have this signed:
UOS  V20：https://www.chinauos.com/resource/download-personal

###### What product or service is this for:
UOS  V20.

###### Please confirm this as the origin your shim.
Yes, we are using the source from https://github.com/rhboot/shim/releases/download/15.4/shim-15.4.tar.bz2

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
What's the justification that this really does need to be signed for the whole world to be able to boot it:
UOS  is yet another linux distribution based on Debian GNU/Linux. It has been actively maintained since 2019 It is an amazing distribution, and for compatible reason, we here submit our siging request for shim.

###### How do you manage and protect the keys used in your SHIM?
The key is stored in isolated standalone server which is placed in secure area with limited access.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes, we use kernel 4.19 with this patch included

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
No.

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
Yes, we use kernel 4.19 with this patch included

###### fixed ?
Yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.04,https://www.gnu.org/software/grub/
grub.uos,1,Uos,grub2,2.04-17,mail:secureboot@uniontech.com
```

```
sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd,1,Firmware update daemon,fwupd,1.5.7,https://github.com/fwupd/fwupd
fwupd-uos,1,Uos,fwupd,1.5.7-3,mail:secureboot@uniontech.com
```

```
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.uos,1,Uos,shim,15.4-6,mail:secureboot@uniontech.com
```

##### Were your old SHIM hashes provided to Microsoft ?
Yes

##### grub2 bootloaders can not be verified ?
New grub2 builds with CVE fix will be signed with new signing EV certificate.

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?
upstream grub2 2.04-17 , from Debian bullseye

###### If your SHIM launches any other components, please provide further details on what is launched
It will load fwupdate, fwupd as already mentioned above.

###### please provide further details on what is launched and how it enforces Secureboot lockdown
grub2 launches Linux kernel

###### apply. Please describe your strategy.
Not applicable, grub2 leaf certificate rotated in Uos  shim

###### How do the launched components prevent execution of unauthenticated code?
Will not start unsigned programs

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### 

4. 19 with secure boot supported.

###### What changes were made since your SHIM was last signed?
Bug and security fixes.
Changelog (since version 15-4).
Don-t-call-QueryVariableInfo-on-EFI-1.10-machines.patch
fix-broken-ia32-reloc.patch
fix-import_one_mok_state.patch
MOK-BootServicesData.patch
relax_check_for_import_mok_state.patch
fix_arm64_rela_sections.patch

###### What is the SHA256 hash of your final SHIM binary?
4a57e3345da3e48b18a1bbddfe6c5593cb983566d125b23191ee93e987dda377  shimia32.efi
f906983aeb3bc47ce73be5ef0543beb42715b5e80eaf83e6d6d9e9cda4a29bf3  shimx64.efi

**Comment by Zeno-sole** [comment]
My previously accepted SHIM    https://github.com/rhboot/shim-review/issues/173

**Comment by Zeno-sole** [comment]
Can the submission be reviewed
@steve-mcintyre

**Comment by julian-klode** [comment]
Please provide a tag as required. I see the previous submission did not have a tag either, please tag the right commit retroactively (hopefully it still reproduces) such that we can compare the submission against the previous ones.

**Comment by Zeno-sole** [comment]
Thank you for your review, I will resubmit based on your comments
