### ISSUE TITLE
shim-15.4 + fixes1 (ia32, x64) for OS ALT (Bazalt Svobodnoe Programmnoe Obespechenie, OOO)

### ISSUE THREAD

**Issue by realnickel** [rhboot/shim-review#205]
Make sure you have provided the following information:
   - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag

https://github.com/realnickel/shim-review/tree/BaseALT-shim15.4-ia32-x64-20211215
 - [x] completed README.md file with the necessary information

https://github.com/realnickel/shim-review/tree/BaseALT-shim15.4-ia32-x64-20211215/README.md
 - [x] shim.efi to be signed

https://github.com/realnickel/shim-review/blob/BaseALT-shim15.4-ia32-x64-20211215/shimia32.efi

https://github.com/realnickel/shim-review/blob/BaseALT-shim15.4-ia32-x64-20211215/shimx64.efi

 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)

https://github.com/realnickel/shim-review/blob/BaseALT-shim15.4-ia32-x64-20211215/altlinux-ca.cer
 - [x] binaries, for which hashes are added do vendor_db ( if you use vendor_db and have hashes allow-listed )

 we do not use vendor_db
 - [x] any extra patches to shim via your own git tree or as files

 we use only upstream patches, refer to the list below or examine our git tree:

http://git.altlinux.org/gears/s/shim.git?p=shim.git;a=commit;h=daaf9bdbc9a188aa3ebd54fbfe7416dbd352b6dc
 - [x] any extra patches to grub via your own git tree or as files

https://github.com/realnickel/shim-review/tree/BaseALT-shim15.4-ia32-x64-20211215/grub_patches
 - [x] build logs

https://github.com/realnickel/shim-review/blob/BaseALT-shim15.4-ia32-x64-20211215/build-ia32.log

https://github.com/realnickel/shim-review/blob/BaseALT-shim15.4-ia32-x64-20211215/build-x64.log
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

https://github.com/realnickel/shim-review/blob/BaseALT-shim15.4-ia32-x64-20211215/Dockerfile

###### What organization or people are asking to have this signed:
Basealt Ltd. (Bazalt Svobodnoe Programmnoe Obespechenie, OOO)
https://www.basealt.ru

###### What product or service is this for:
OS ALT
https://getalt.org/en/
https://www.basealt.ru/go/downloads/

###### Please confirm this as the origin your shim.
We use 15.4 shim (https://github.com/rhboot/shim/releases/tag/15.4) +

latest chosen upstream fixes (including critical ones discussed in https://github.com/rhboot/shim-review/issues/165)

While review rebuild is performed by applying mentioned patches upon requested upstream tarball.

822d07ad shim-15.4-upstream-0001-Fix-handling-of-ignore_db-and-user_insecure_mode.patch

5b3ca0d2 shim-15.4-upstream-0003-Fix-a-broken-file-header-on-ia32.patch

4068fd42 shim-15.4-upstream-0004-mok-allocate-MOK-config-table-as-BootServicesData.patch

493bd940 shim-15.4-upstream-0005-Don-t-call-QueryVariableInfo-on-EFI-1.10-machines.patch

05875f3a shim-15.4-upstream-0006-Post-process-our-PE-to-be-sure.patch

9f973e4e shim-15.4-upstream-0007-Relax-the-check-for-import_mok_state.patch

4d64389c shim-15.4-upstream-0010-shim-another-attempt-to-fix-load-options-handling.patch

9e4f38ab shim-15.4-upstream-0020-shim-move-the-bulk-of-set_second_stage-to-its-own-fi.patch

ada7ff69 shim-15.4-upstream-0022-shim-don-t-fail-on-the-odd-LoadOptions-length.patch

34e3ef20 shim-15.4-upstream-0023-arm-aa64-fix-the-size-of-.rela-sections.patch

7501b6bb shim-15.4-upstream-0024-mok-fix-potential-buffer-overrun-in-import_mok_state.patch

3f327f54 shim-15.4-upstream-0025-mok-relax-the-maximum-variable-size-check.patch

4583db41 shim-15.4-upstream-0026-Don-t-unhook-ExitBootServices-when-EBS-protection-is.patch

1b30c2b9 shim-15.4-upstream-0027-fallback-find_boot_option-needs-to-return-the-index-.patch

204f6bb5 shim-15.4-upstream-0028-httpboot-Ignore-case-when-checking-HTTP-headers.patch

c5784078 shim-15.4-upstream-0029-fallback-incorrect-check-after-AllocateZeroPool.patch

cff8db7d shim-15.4-upstream-0030-fallback-free-the-right-variable-on-the-read_file-er.patch

f9ced705 shim-15.4-upstream-0031-shim-avoid-BOOTx64.EFI-in-message-on-other-architect.patch

44f18635 shim-15.4-upstream-0032-str-remove-duplicate-parameter-check.patch

437caecb shim-15.4-upstream-0033-fallback-Print-info-on-GetNextVariableName-errors.patch

77648c5c shim-15.4-upstream-0034-fallback-Use-a-dynamic-buffer-when-list-var-names.patch

0837d010 shim-15.4-upstream-0035-fallback-add-compile-option-FALLBACK_NONINTERACTIVE.patch

main goal of this submission is to fix fwupd-efi failure:
https://github.com/fwupd/firmware-lenovo-thinkpad/issues/129

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
OS ALT is a linux distribution supporting Secure Boot

###### How do you manage and protect the keys used in your SHIM?
Access to server used to sign binaries is restricted physically.
Only few trusted persons have sign authority.

###### Do you use EV certificates as embedded certificates in the SHIM?
No EV certs, but selfsigned altlinux-ca.cer is embedded

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
No

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
Yes

###### fixed ?
Yes

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
SBAT for shim:

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.altlinux,1,ALT Linux,shim,15.4-alt3,http://git.altlinux.org/gears/s/shim.git

SBAT for grub:

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.06,https://www.gnu.org/software/grub/
grub.altlinux,1,ALT Linux,grub,2.06-alt3,http://git.altlinux.org/gears/g/grub.git

SBAT for fwupd-efi:

sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd-efi,1,Firmware update daemon,fwupd-efi,1.1,https://github.com/fwupd/fwupd-efi
fwupd-efi.altlinux,1,ALT Linux,fwupd-efi,1.1-alt2,http://git.altlinux.org/gears/f/fwupd-efi.git

##### Were your old SHIM hashes provided to Microsoft ?
Yes

##### grub2 bootloaders can not be verified ?
Yes

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
Downstream RHEL/Fedora/Debian/Canonical like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?
upstream grub-2.06 including patches for all currently discussed security issues;
also there are some SB patches from Fedora and other patches listed in repository's grub_patches subdir

###### If your SHIM launches any other components, please provide further details on what is launched
It also launches fwupd-efi-1.1-alt2

###### please provide further details on what is launched and how it enforces Secureboot lockdown
It doesn't

###### apply. Please describe your strategy.
We switched to a new certificate

###### How do the launched components prevent execution of unauthenticated code?
GRUB and kernel are patched to enforce Secure Boot.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Linux Kernel:
5.4  (std-def: standard longterm kernel for stable branches),
5.10 (std-def: standard longterm kernel for unstable branch),
        http://git.altlinux.org/gears/k/kernel-image-std-def.git
5.13 (un-def: more modern than std-def and with forced preemption enabled),
        http://git.altlinux.org/gears/k/kernel-image-un-def.git?p=kernel-image-un-def.git;a=summary

###### What changes were made since your SHIM was last signed?
Upstream version update (15.4 + fixes -> 15.4 + fixes1)

###### What is the SHA256 hash of your final SHIM binary?
25905d8f78b9ac7620c21c3a3d9ccf1478a2abf451e5f56c04e474caa703845a  shimia32.efi

d94d5d156268e30295d074f055fd1ebdfd9d6e6264a134ebb478fcda9035af92  shimx64.efi

**Comment by realnickel** [comment]
FWIW: previous accepted review was #158

**Comment by frozencemetery** [comment]
There's a checklist at the top.

**Comment by realnickel** [comment]
@frozencemetery, @vathpela, @steve-mcintyre, @julian-klode!
Could you please comment on the following: after 15.5-rc1 is tagged should we move to using it unconditionally, or 15.4 with a patch set mentioned in our submission (which makes it much like 15.5-rc1 actually) is still "reviewable and signable" ?

**Comment by julian-klode** [comment]
I considered reviewing this, but it does not follow best practices WRT having a simple Dockerfile I can run in podman, so you'll have to wait for someone to deal with your specialness.

**Comment by realnickel** [comment]
@julian-klode, sorry to hear that  ;(. That was never a problem before... 
So, do you mean I should "invert" my file stack "Docker run from shell script" into "shell script run from Dockerfile" to comply?
What is your opinion on shim version and patch set?

**Comment by realnickel** [comment]
> I considered reviewing this, but it does not follow best practices WRT having a simple Dockerfile I can run in podman, so you'll have to wait for someone to deal with your specialness.

@julian-klode, I addressed your claim in updated submission. Hope it works with podman as it does with docker. shim binaries were not changed.

https://github.com/realnickel/shim-review/tree/BaseALT-shim15.4-ia32-x64-20211116

**Comment by realnickel** [comment]
@julian-klode, @frozencemetery,
is there any issue with our submission which prevents it from being reviewed?

**Comment by frozencemetery** [comment]
>  So, do you mean I should "invert" my file stack "Docker run from shell script" into "shell script run from Dockerfile" to comply?

Not quite.  Ideally, you wouldn't have a shell script at all, just a Dockerfile.

**Comment by realnickel** [comment]
> > So, do you mean I should "invert" my file stack "Docker run from shell script" into "shell script run from Dockerfile" to comply?
> 
> Not quite. Ideally, you wouldn't have a shell script at all, just a Dockerfile. 

Ok. I pulled that helper shell script into the Docker file.
https://github.com/realnickel/shim-review/commit/f07f436cda76e7408ea07b3a2d8460aaada50f1d

>Additionally, the usage of gear and hsh-sandbox mean that there's quite a lot of build infrastructure to review.

No additional infrastructure left at all. No hasher (hsh-sandbox), no gear, no even rpmbuild any more.
https://github.com/realnickel/shim-review/commit/3652ad0e48018eae494025996850ef8aacc1939b
> 
> You've chosen to not follow the guidance of README.md: "Please create your shim binaries starting with the 15.4 shim release tar file: https://github.com/rhboot/shim/releases/download/15.4/shim-15.4.tar.bz2" - instead, you've got a custom git tree hosted elsewhere. This will need to be changed if you want my review.

Reworked Dockerfile to use required  tarball as source. While that was not a strict requirement before and I didn't encounter a call for unconditional use of such approach. As a linux distribution we've got settled package build infrastructure using git source trees and I thought that shim-review board welcomes shim build reproduction scenarios that are as close to normal vendor build workflow as possible. Guess I misunderstood something.

https://github.com/realnickel/shim-review/commit/b222e27795914ab713abc34f7a4be02a15e76cd8

Updated  README.md and ISSUE_TEMPLATE.md and this issue header post accordingly. You may refer to 
https://github.com/realnickel/shim-review/tree/BaseALT-shim15.4-ia32-x64-20211215

@julian-klode, @frozencemetery,  please review an updated submission. EFI binaries remain unchanged.

**Comment by realnickel** [comment]
@julian-klode, @frozencemetery, @cyphermox, @cyphermox, @steve-mcintyre,
may our submission be reviewed?

**Comment by frozencemetery** [comment]
1. Submission is not a new vendor
2. Submission reproduces
3. Patches appear to be cherry-picks from main.
4. All questions answered.
5. Org matches
6. Access to certs is "restricted physically"
7. Cert is valid 10 years
8. SBAT looks okay
9. grub is used
10. grub patches look okay
11. It's not immediately clear to me whether this kernel is correctly patched or not
12. N/A
13. Normal secure boot patching is claimed.

I'd like another set of eyes on access control (6) and grub patches (10).

**Comment by realnickel** [comment]
@frozencemetery, thank you for the review!

What concerns to (6), if this should be explicitly mentioned now, we use FIPS-140 certified dongle to store CA-cert used as VENDOR_CERT.

**Comment by julian-klode** [comment]
I'm not going to re-review the grub patches more detailed, I trust in the last review of them and the current state looks sensible.

(6) has been addressed in previous comment

Marking as accepted

**Comment by realnickel** [comment]
@julian-klode, @frozencemetery, thanks for the review!
Binaries were signed, so closing the issue.
