### ISSUE TITLE
shim-15 for CloudReady

### ISSUE THREAD

**Issue by nicholasbishop** [rhboot/shim-review#21]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
[neverware/shim-review@neverware-shim-20180723](https://github.com/neverware/shim-review/tree/neverware-shim-20180723)
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

###### What organization or people are asking to have this signed:
Neverware Inc. (https://www.neverware.com)

###### Version of shim:
15

###### Sysdev Submission ID:
Microsoft told us to get approval from the shim review board before submitting it to them.

###### What product or service is this for:
CloudReady

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
CloudReady is a Linux distro; we'd like to encourage people to boot our OS with secure boot enabled.

**Comment by cyphermox** [comment]
Confirming the builds are reproducible, still need to have a look at the grub patchset.

**Comment by cyphermox** [comment]
Sorry about the delay. I see no issues with the grub patches. As far as I am concerned this submission is suitable for signing.

ff5aa4640be7c17d115d05f57258c168a3834f6af0899c0e57d371fb1ccb0a55  shimia32.efi
3d3d3086c0246c401f8e44930c3f7a1bef212241fc656ca4c4d2fa244a59d255  shimx64.efi
