### ISSUE TITLE
SHIM 15.4 for AmZetta Technologies

### ISSUE THREAD

**Issue by amzdev0401** [rhboot/shim-review#210]
Make sure you have provided the following information:

 - [ ] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 - [ ] completed README.md file with the necessary information
 - [ ] shim.efi to be signed
 - [ ] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [ ] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [ ] any extra patches to shim via your own git tree or as files
 - [ ] any extra patches to grub via your own git tree or as files
 - [ ] build logs
 - [ ] a Dockerfile to reproduce the build of the provided shim EFI binaries

###### What organization or people are asking to have this signed:
`[your text here]`

###### What product or service is this for:
`[your text here]`

###### Please confirm this as the origin your shim.
`[your text here]`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`[your text here]`

###### How do you manage and protect the keys used in your SHIM?
`[your text here]`

###### Do you use EV certificates as embedded certificates in the SHIM?
`[your text here]`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`[your text here]`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
`[your text here]`

###### fixed ?
`[your text here]`

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
`[your text here]`

##### Were your old SHIM hashes provided to Microsoft ?
`[your text here]`

##### grub2 bootloaders can not be verified ?
`[your text here]`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`[your text here]`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`[your text here]`

###### If your SHIM launches any other components, please provide further details on what is launched
`[your text here]`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`[your text here]`

###### apply. Please describe your strategy.
`[your text here]`

###### How do the launched components prevent execution of unauthenticated code?
`[your text here]`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`[your text here]`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`[your text here]`

###### What changes were made since your SHIM was last signed?
`[your text here]`

###### What is the SHA256 hash of your final SHIM binary?
`[your text here]`

**Comment by julian-klode** [comment]
Closing this issue, as it does not contain any data - maybe it was a bot
