### ISSUE TITLE
Shim 15.4+patches for Cisco PuzzleOS

### ISSUE THREAD

**Issue by joylatten** [rhboot/shim-review#212]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20211011
 - [x] completed README.md file with the necessary information
https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20211011/README.md
 - [x] shim.efi to be signed
https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20211011/artifacts.20211007130509
See the file, shimx64.efi .
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20211011/config/certs
A copy of our vendor db can be seen in the file vendor_db.esl file in the artifacts directory.
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
We have not added any hashes to the vendor db, only the certificates mentioned above.
 - [x] any extra patches to shim via your own git tree or as files
The Dockerfile has information on the source of the included patches and the shim-git_commit_extra.log file in the artifacts directory contains the output of git log -p 15.4..HEAD after all of the patches have been applied.
 - [x] any extra patches to grub via your own git tree or as files
We do not use GRUB, we boot directly into the Linux Kernel from shim using a stripped down systemd-boot EFI stub. More information can be found in our README.md file.
 - [x] build logs
https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20211011/artifacts.20211007130509
See the file, build.log .
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries
 https://github.com/puzzleos/uefi-shim_review/tree/puzzleos-shim-x86_64-20211011
See the file, Dockerfile.

###### What organization or people are asking to have this signed:
`Cisco Systems, Inc.`

###### What product or service is this for:
`PuzzleOS, a Linux based appliance OS used in a number of Cisco products.`

###### Please confirm this as the origin your shim.
`The included Dockerfile uses the 15.4 tag as a base after verifying the GPG signature, all patches are applied on top of this base.`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`PuzzleOS is designed to run on any platform that supports UEFI Secure Boot and the easiest way to support the largest number of systems is to have a shim bootloader signed by Microsoft.`

###### How do you manage and protect the keys used in your SHIM?
`The certificates included in our shim build are built from keys stored in Cisco's corporate key management system. Access to this system is tightly controlled and operations are restricted to authorized individuals.`

###### Do you use EV certificates as embedded certificates in the SHIM?
`No.`

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
`No, only certificates are stored in the vendor db file.`

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
`We do not currently plan to sign Linux Kernels prior to v5.10 which contains 75b0cea7bf30 ("ACPI: configfs: Disallow loading ACPI tables when locked down").`

###### fixed ?
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.
The "stubby" EFI shim: https://github.com/puzzleos/stubby`

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
    Our shim build uses the SBAT information below:

    sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
    shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
    shim.puzzleos,1,PuzzleOS,shim,15.4-202110-1,https://github.com/puzzleos

    As we only plan on booting Linux Kernels directly from shim using stubby, I expect that we would 
    adopt the following pattern for our kernel EFI binaries:

    sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
    stubby.puzzleos,1,PuzzleOS,stubby,%{stubby_version},https://github.com/puzzleos/stubby 
    linux.puzzleos,1,PuzzleOS,linux,%{kernel_version},https://github.com/puzzleos

##### Were your old SHIM hashes provided to Microsoft ?
`This is a new vendor submission, there are no old hashes to submit.`

##### grub2 bootloaders can not be verified ?
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.
The "stubby" EFI shim: https://github.com/puzzleos/stubby`

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.
The "stubby" EFI shim: https://github.com/puzzleos/stubby`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.
The "stubby" EFI shim: https://github.com/puzzleos/stubby`

###### If your SHIM launches any other components, please provide further details on what is launched
`We only plan to use our shim build to launch the Linux Kernel.`

###### please provide further details on what is launched and how it enforces Secureboot lockdown
`We have no plans to use GRUB2 as a second stage loader. Our intention is to bundle the Linux Kernel, initramfs, and kernel command line into a single EFI binary such that the PE/COFF signature protects all of those components. We are using a small EFI stub, based on the systemd-boot stub, to do this and we have augmented it to add support for a SBAT section.
The "stubby" EFI shim: https://github.com/puzzleos/stubby`

###### apply. Please describe your strategy.
`This is a new vendor submission, complete with new CA certificates. Further, we have no plans to boot GRUB with our shim build.`

###### How do the launched components prevent execution of unauthenticated code?
`We rely on the existing Linux Kernel mechanisms to prevent the execution of unwanted code.`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`No. We do not use our shim to load any additional bootloaders.`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`We do not currently plan to sign Linux Kernels prior to v5.10.`

###### What changes were made since your SHIM was last signed?
`This is a new vendor submission, we have not previously signed any shim builds.`

###### What is the SHA256 hash of your final SHIM binary?
`% sha256sum *
86b414b764fdebd000f16b5ec383ecf5de521c0e6efccce54c7fc1ab1655cc79  build.log
961e1bcf7f7b0da3fbe962039ba0d6be7eb3057c81c63dd613b7e385729ab08b  fbx64.efi
e1bd0ce63b172c4e948eef9968d78ff3600a4db265e60b1c308ae43b591c6ba3  mmx64.efi
a39b4c7a3765ee92d13e2520ddfb9740821fc9169cd1253c51c4db1c33148193  shim-git_commit_extra.log
4d42abebf7f5ecdcabacb15aeed908858cdda738cac1cc3c3afea7c00def68f2  shimx64.efi
0950f70d1dce96ac227a09f4885356df2527de75891b6ca5c703a0af800bbccb  vendor_db.esl`

**Comment by pjbrown4** [comment]
Build is reproducible.

**Comment by julian-klode** [comment]
There are a couple of outstanding questions we need to address:

- The README.md lists Serge and Tycho as contacts, is that still accurate; why is none of the contact persons submitting this?
- We have not validated Tycho's email

Compared to the last submission which was not accepted a couple of changes were made that look OK. I think the previous review got ACKED by Steve (with caveat of wanting a 2nd review), and I'm happy so far with the changes, and can reproduce the bugs, so I'm leaning towards accepting this.

**Comment by hallyn** [comment]
Hi @julian-klode  - @joylatten  took this over from Paul.  She'll update the README to add her name.

It would still be great to have Tycho's email validated as well.

**Comment by joylatten** [comment]
Hi @julian-klode I have updated the README as the primary contact. 

Is it possible for another email be sent to Tycho for validating his email?

**Comment by julian-klode** [comment]
Sorry I only really look at this on Fridays really, but I'll take care of it

**Comment by joylatten** [comment]
Thank you!

**Comment by joylatten** [comment]
any new status?

**Comment by hallyn** [comment]
Hi - just to make sure:  while checking on the status of this, I noticed that there's a long list of patches, but they are all applied upstream.  The guidance still says to base on 15.4 release.  Is that still correct?

**Comment by joylatten** [comment]
Hi @frozencemetery,
Which of the contacts still need to be verified? And how do we go about completing the verification(s)?

**Comment by julian-klode** [comment]
Ramble... Notes for review:

I really do not like the approach to certificates here, with a vendor_db with 3 certificates in it. It's very confusing to review (call it a "novel approach"), why don't they just have one parent CA whose certificate is embedded.

I'm meh about the fact that it's built from git where we specifically ask people to build from the tarball instead. I like how you can track the origin of the patches to the repository, but then you also have to look at the individual commit ids to see if they make sense on their own.

**Comment by julian-klode** [comment]
- The keys for @joylatten and @hallyn do not have UIDs for the Cisco email addresses to which I just sent verification emails
- Tycho's key is broken so can't be imported:
```
gpg: key 0x18D18F1BC464DCA3: 2 duplicate signatures removed
gpg: key 0x18D18F1BC464DCA3: 2 bad signatures
gpg: key 0x18D18F1BC464DCA3: 2 signatures reordered
gpg: key 0x18D18F1BC464DCA3: no user ID for key signature packet of class 13
gpg: key 0x18D18F1BC464DCA3: no user ID for signature
gpg: Total number processed: 1
```

**Comment by hallyn** [comment]
bewahrendem
saufenden
Essigs
Schulr�ume
gehobenen
homogenerer

**Comment by hallyn** [comment]
> Tycho's key is broken so can't be imported - Apparently it does not contain any UID:

When I look at https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0xA91175B11F2CC0FEB9944208F0D44CEB106606C7, I see this one which imports fine for me:

```
serge@jerom:~$ gpg --recv-keys --keyserver keyserver.ubuntu.com 0xA91175B11F2CC0FEB9944208F0D44CEB106606C7
gpg: key F0D44CEB106606C7: public key "Tycho Andersen <tycho@tycho.ws>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by tych0** [comment]
I don't think we should use that key -- I unfortunately can't update launchpad's key because I'm locked out of my account due to no longer being a Canonical employee :).

Can you say which key you imported? https://tycho.pizza/tych0.asc should work I hope, but gpg is hard to use, so it probably doesn't :)

**Comment by joylatten** [comment]
weitermache
Bundesbediensteten
blitztet
wohlgef�lligstes
scharfgemachten
best�ckbare

**Comment by julian-klode** [comment]
> I don't think we should use that key -- I unfortunately can't update launchpad's key because I'm locked out of my account due to no longer being a Canonical employee :).

Oh, that's not normal, getting locked out of launchpad after leaving. You can open an RT by email to rt@ubuntu.com

> Can you say which key you imported? https://tycho.pizza/tych0.asc should work I hope, but gpg is hard to use, so it probably doesn't :)

I used `gpg --keyserver keyserver.ubuntu.com --recv-keys 3CCAB226289DE0160C61BDB418D18F1BC464DCA3`. It seems to work on `keys.openpgp.org` which I just got to work yesterday, and the file works too.

@tych0 I just sent you a new world list (and accidentally an unencrypted one first, sorry about that).

**Comment by tych0** [comment]
Which e-mail did you send it to? I haven't received anything...

Will e-mail rt, thanks.

**Comment by julian-klode** [comment]
@tych0 To your corporate email to associate the shim submission with your corporate account

**Comment by tych0** [comment]
Oof, I hadn't checked that one yet this morning :). Thanks. Word list is:

```
gengenderem
ereilendem
fortkommendes
plattgewalztem
untadelhaftere
verzanktes
```

**Comment by julian-klode** [comment]
All contacts verified, ignoring the unicode shenanigans in the german words :D

**Comment by joylatten** [comment]
@julian-klode  
We must be able to distinguish kernels signed by different keys by their pcr7 value. We use the pcr7 value  to build TPM EA Policy for efi binaries (kernel+initrd+cmdline) signed with the 3 keys.
We tested with a parentCA only in either the VENDOR_CERT_FILE or VENDOR_DB_FILE, and shim uses that to extend pcr7. We are then unable to use the pcr7 value to distinguish our kernels nor apply our TPM EA Policies appropriately.

**Comment by joylatten** [comment]
hi,  curious if there is any new status?
