### ISSUE TITLE
Shim 15.4 for Circle Linux 8

### ISSUE THREAD

**Issue by rouzer-zhou** [rhboot/shim-review#217]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
   https://github.com/circle-linux/shim-review/tree/circlelinux-8-shim-x86_64-20211118
- [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

###### What organization or people are asking to have this signed:
Circle Enterprise Software Foundation

###### What product or service is this for:
Circle Linux 8

###### Please confirm this as the origin your shim.
Yes, we are using shim 15.4 release tarball

Review repo located at: [circle-linux/shim-review@circlelinux-8-shim-x86_64-20211118](https://github.com/circle-linux/shim-review/tree/circlelinux-8-shim-x86_64-20211118), which includes README.md, both shim EFI binaries, circle-boot-ca-cert.der cert, root.log and build.log

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Circle Linux is a community enterprise operating system designed to be 100% bug-for-bug compatible with RHEL and replacing CentOS 8 since it will be EOL this year

###### How do you manage and protect the keys used in your SHIM?
FIPS-140-2 level 2 certified HSM

###### Do you use EV certificates as embedded certificates in the SHIM?
No

###### If you use new vendor_db functionality, are any hashes allow-listed, and if yes: for what binaries ?
We don't use vendor_db functionality in this build

###### Is kernel upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 present in your kernel, if you boot chain includes a Linux kernel ?
Yes, We have validated that commit present:
75b0cea7bf307f362057cc778efe89af4c615354
And the configuration setting CONFIG_EFI_CUSTOM_SSDT_OVERLAYS is disabled.

###### fixed ?
All those exists and the signed bootloaders are derived from grub 2.02 with all of the relevant patches.

###### Please provide exact SBAT entries for all SBAT binaries you are booting or planning to boot directly through shim
On shim, we have:

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,1,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.circle,1,Circle Linux,shim,15.4-4,security@cclinux.org

On grub2, we have:

sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,1,Free Software Foundation,grub,2.02,https://www.gnu.org/software/grub/
grub.rhel8,1,Red Hat Enterprise Linux 8,grub2,1:2.02-99.el8.1,mail:secalert@redhat.com
grub.circle8,1,Circle Linux 8,grub2,1:2.02-99.el8.1,mail:security@cclinux.org

On fwupd, we have:

sbat,1,UEFI shim,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
fwupd,1,Firmware update daemon,fwupd,1.5.9,https://github.com/fwupd/fwupd
fwupd.circle,1,Circle Linux,fwupd,1.5.9,mail:security@cclinux.org

##### Were your old SHIM hashes provided to Microsoft ?
This is our first submission

##### grub2 bootloaders can not be verified ?
This is our first sumission

##### * Upstream grub2 shim_lock verifier or * Downstream RHEL/Fedora/Debian/Canonical like implementation ?
RHEL like implementation

###### What is the origin and full version number of your bootloader (GRUB or other)?
Same version as RHEL and code is here https://git.cclinux.org/stage/rpms/grub2.git added our certs and sbat entry, this will build grub2-2.02-99

###### If your SHIM launches any other components, please provide further details on what is launched
We also have fwupd, which will have similar .sbat provisions to grub2

###### please provide further details on what is launched and how it enforces Secureboot lockdown
None, only linux

###### apply. Please describe your strategy.
We are not reusing any previously used CA, this is our first submission

###### How do the launched components prevent execution of unauthenticated code?
Everything validates signatures using shim's protocol.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
RHEL kernel and all signed kernels are all patched for the kernel boothole CVEs and have the CONFIG_EFI_CUSTOM_SSDT_OVERLAYS config option disabled.

###### What changes were made since your SHIM was last signed?
This is our first submission

###### What is the SHA256 hash of your final SHIM binary?
d4765bc5a705f2438cace435bbd82fa7267d4d857770b67660218b5854e275f6  shimx64.efi
d1a81df3dcc5f49c507a5730bf97a76d40116982c977ed86184dda9144783178  shimia32.efi

**Comment by tSU-RooT** [comment]
Hi, I have read your submission.
I noticed below points.

- Please link to your repo expressly,
like this: [circle-linux/shim-review@circlelinux-8-shim-x86_64-20211106](https://github.com/circle-linux/shim-review/tree/circlelinux-8-shim-x86_64-20211106)
- Cert file is HTML.
https://github.com/circle-linux/shim-review/blob/circlelinux-8-shim-x86_64-20211106/circle-boot-ca-cert.der
- I have failed to pull container image of `circlelinux/circlelinux-shim:8-154.3`, so I couldn't confirm reporoducibility of your shim.
- Contacts: Only first names are noted, and no PGP(GPG) public keys attached.
- Sorry for asking this, is `Circle Enterprise Software Foundation` really exist? (I hope it's not copy&paste of Rocky Linux's submission)

**Comment by rouzer-zhou** [comment]
> 
> 
> Hi, I have read your submission. I noticed below points.
> 
>     * Please link to your repo expressly,
>       like this: [circle-linux/shim-review@circlelinux-8-shim-x86_64-20211106](https://github.com/circle-linux/shim-review/tree/circlelinux-8-shim-x86_64-20211106)
I will link it to our repo.
> 
>     * Cert file is HTML.
>       https://github.com/circle-linux/shim-review/blob/circlelinux-8-shim-x86_64-20211106/circle-boot-ca-cert.der
> 
      Thank you, I has comitted the correct format Cert file.
>     * I have failed to pull container image of `circlelinux/circlelinux-shim:8-154.3`, so I couldn't confirm reporoducibility of your shim.
> 
 There is a error in container image, I will fix it.

>     * Contacts: Only first names are noted, and no PGP(GPG) public keys attached.
> 
Can you tell me how I can get a PGP key?

>     * Sorry for asking this, is `Circle Enterprise Software Foundation` really exist? (I hope it's not copy&paste of Rocky Linux's submission)
Now we are a linux distribution community. we focus on delivering a robust open source ecosystem around a Linux platform. 
Our website is here:https://www.cclinux.org/home

**Comment by SherifNagy** [comment]
That does looks a lot like Rockylinux submission copy&paste, but anyway we at rocky got asked not to use a special docker container for shim and I thought to share this info with you too since you are following the same path.

**Comment by rouzer-zhou** [comment]
@SherifNagy 
Thank you, but can you tell me the function of PGP key here?how can I get a PGP key?

**Comment by julian-klode** [comment]
No disrespect, but if you want to build a Linux distribution and get secure boot signed binaries, you should be able to figure this out on your own.

But I see you just disable the gpg checks for the sources, so hooray, anyone can MITM package updates and hijack users of your distro?

**Comment by xnox** [comment]
> > ```
> > * Contacts: Only first names are noted, and no PGP(GPG) public keys attached.
> > ```
> 
> Can you tell me how I can get a PGP key?
> 

This comment alone indicates potentially lack of security practices at this vendor. I would object to signing their shim submission for at least 12 months due to this comment alone.

**Comment by nicholasbishop** [comment]
PGP is pretty ancient and not well-loved, there's no shame in not being familiar with it. I've work on a Linux distro for six years or so, and I think secure boot signing is the only time I've ever had to directly interact with PGP. Ideally shim review can be a place to help other distros, not a gatekeeper against people who are unfamiliar with the particular tools that have been chosen :)

@rouzer-zhou A common way to do PGP operations is with GnuPG, aka GPG. The [wikipedia](https://en.wikipedia.org/wiki/GNU_Privacy_Guard) page has a useful overview, and the [manual](https://www.gnupg.org/gph/en/manual/book1.html) describes some of the specific commands to run.

In truth I think the most common way to use PGP is to google "how do I do X with gpg" when you need to do a particular operation; it's not a tool that most people use on a day-to-day basis.

**Comment by xnox** [comment]
@nicholasbishop submitter of shim must have strong knowledge and reliable processes of how they manager their archive signing keys, grub/kernel signing keys, and ability to receive encrypted & authenticated security notifications. These things today rely on x509 and PGP certificates and keys. It is required for shim development and for integrity of the Circle Linux itself.

**Comment by SherifNagy** [comment]
> @SherifNagy Thank you, but can you tell me the function of PGP key here?how can I get a PGP key?

@rouzer-zhou I would start reading the wikipedia page mentioned by @nicholasbishop but in short, you can sign emails, encrypted emails / files and sign git commits with PGP for validation, however, the keys also can be signed to create a ring of trust after physical validation.

**Comment by rouzer-zhou** [comment]
Thanks very much, I know the function of the pgp key ,for example rpm signing, but I do not understand why I need to attach one PGP pub key here.
I have attached my PGP key.

**Comment by julian-klode** [comment]
So people can reach you encrypted in case of a security issue.

**Comment by rouzer-zhou** [comment]
I want to know when I can get my signed shim files.
If there are not any problems, please sign it quickly.

**Comment by Doncuppjr** [comment]
Your files will not be signed here. Microsoft will do that. Only your build process will be reviewed here, and either denied or approved.

**Comment by rouzer-zhou** [comment]
what is the meaning of "contact verification"? what should I do next?

**Comment by ecos-platypus** [comment]
I am not an authorized reviewer that can send you emails for contact verification. However, to address recurring questions regarding contact verification, I opened an issue with a documentation draft. Feel free to take a look at the last paragraph of #230.

**Comment by bella485** [comment]
HI devs,  is there anything wrong for circlelinux secboot cert supply ? if need something , please contact us, thanks alot.

**Comment by julian-klode** [comment]
Closing outdated request due to the recent round of CVEs in grub and shim requiring a new submission with fixes for all these CVEs.
