### ISSUE TITLE
Possibility of signing 4.19.x kernel?

### ISSUE THREAD

**Issue by vt-alt** [rhboot/shim-review#219]
README says:
> If your boot chain of trust includes linux kernel, is "efi: Restrict efivar_ssdt_load when the kernel is locked down" upstream commit 1957a85b0032a81e6482ca4aab883643b8dae06e applied ? Is "ACPI: configfs: Disallow loading ACPI tables when locked down" upstream commit 75b0cea7bf307f362057cc778efe89af4c615354 applied ?

Still, is there any possibility to sign 4.19.x stable kernels?

**Comment by julian-klode** [comment]
As long as they have the necessary patches. Someone else has more details on what's needed I assume, but you might need to cherry-pick patches yourself.

**Comment by vt-alt** [comment]
They are not cherry-pickable since there is no lockdown support in 4.19, it's first appeared in 5.4.

**Comment by vt-alt** [comment]
> They are not cherry-pickable since there is no lockdown support in 4.19, it's first appeared in 5.4.

So, if 4.19 kernel cannot be locked down why apply the patches which disallow some other kernel functionality on condition of the kernel being locked down?

By my reasoning 4.19 should be allowed to be signed, because there is no lockdown possibility. I wish there is authoritative answer on this.

**Comment by vt-alt** [comment]
Perhaps, you should explicitly state that kernel lockdown functionality is required.
