### ISSUE TITLE
CIsco SHIM-14

### ISSUE THREAD

**Issue by dosman0** [rhboot/shim-review#22]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/cisco/sto-uefi-secure-bootloader/tree/cisco-shim-x64-20180802
 - [x] completed README.md file with the necessary information
https://github.com/cisco/sto-uefi-secure-bootloader/blob/cisco-shim-x64-20180802/shim-review/README.md
 - [x] shim.efi to be signed
https://github.com/cisco/sto-uefi-secure-bootloader/blob/cisco-shim-x64-20180802/shim-review/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/cisco/sto-uefi-secure-bootloader/blob/cisco-shim-x64-20180802/shim-review/cisco_virtual_root.der
 - [x] any extra patches to shim via your own git tree or as files
none
 - [x] any extra patches to grub via your own git tree or as files
none
 - [x] build logs
https://github.com/cisco/sto-uefi-secure-bootloader/blob/cisco-shim-x64-20180802/shim-review/build.log

###### What organization or people are asking to have this signed:
Cisco Systems IANA Enterprise Number 9

###### Version of shim:
https://github.com/rhboot/shim/releases/tag/14

###### Sysdev Submission ID:
UEFI File Submission ID: 13985242977356081

###### What product or service is this for:
Cisco Appliances and Virtual products that are using Linux based Operating Systems

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Customers using Cisco Virtual products that run on 3rd party servers (DELL, HP...) do not have permissions to change the UEFI db and add our keys. The Microsoft signed SHIM allows these products to securely run on those platforms

**Comment by dosman0** [comment]
Anything else I need to submit for this review??

**Comment by cyphermox** [comment]
I'm not sure what to understand from the last two sections from the readme?

-------------------------------------------------------------------------------
Put info about what bootloader you're using, including which patches it includes to enforce Secure Boot here:
-------------------------------------------------------------------------------
GRUB2 shipping with CentOS 7, and Ubuntu

-------------------------------------------------------------------------------
Put info about what kernel you're using, including which patches it includes to enforce Secure Boot here:
-------------------------------------------------------------------------------
Standard kernels from CentOS 7 and Ubuntu. Secure boot support flags enabled during builds


Does that mean you're using whatever booloader CentOS 7 and Ubuntu use, and in that case, why replace their shim?

For "Standard kernels"; what do you mean by "Secure boot support flags enabled during builds"? Are you relying directly on whatever distros are providing? Or are you rebuilding these kernels to enable further options?

**Comment by dosman0** [comment]
We are using a standard shim only to get the Cisco RootCA certificate into our verify chain.  Our kernels will have changes and will be signed with a Cisco product EE certificate that chains back thru the Cisco RootCA.  Customers running on 3rd party servers, that don't have signing keys to add to the UEFI db, will need to use our shim signed by the MS keys pre-installed so they have access to the Cisco RootCA certificate.   

Not sure what the "lots of additional changes in various places in the binary" would be either, can you provide a diff set so we can evaluate it? Tool chain differences???

**Comment by cyphermox** [comment]
I'm building with a simplified dockerfile based on the one you provided (just removing the stuff that looks extra for jenkins and whatnot):

`FROM docker.io/centos:7 
#Install basic build environment and headers
RUN yum groupinstall -y "Development Tools"
RUN yum install -y openssl-devel gnu-efi-devel elfutils-libelf-devel git openssl
#Install fpm and its dependencies
RUN yum install -y ruby-devel rpm-build rubygems
RUN gem install --no-ri --no-rdoc fpm
RUN git clone --branch cisco-shim-x64-20180802 https://github.com/cisco/sto-uefi-secure-bootloader.git
WORKDIR /sto-uefi-secure-bootloader
RUN make VENDOR_CERT=build-tools/certs/cisco_virtual_root.der
RUN hexdump -Cv shimx64.efi > built.hex
RUN hexdump -Cv shim-review/shimx64.efi > orig.hex
RUN diff -u  orig.hex  built.hex 
`

Once the shim is built, it will output the differences between the built file and the file you provided in shim-review/.

**Comment by dosman0** [comment]
Thank you for helping us sort this out.  I have another question, if you can't get a bit for bit true comparison, how do we get a checksum that matches the image that has already been submitted to MS? Basically, how does MS know they have the same image that you approved?? I don't mean to cause trouble, just trying to understand how this review helps MS.

**Comment by cyphermox** [comment]
Someone reviews your binaries, compare against the one you provided in the git tree (which should be the same you sent to Microsoft), and if they are close enough, approve the submission (here we tend to give the sha256sum of the original again).

I know to expect some differences (for instance in the ephemeral cert embedded that can sign fb*.efi and mm*.efi during the build, if ENABLE_SHIM_CERT is set; and the COFF Optional Header checksum).

If I take as example the build in docker for this submission:

```
--- orig.hex	2018-08-22 19:08:55.000000000 +0000
+++ built.hex	2018-08-22 19:08:50.000000000 +0000
@@ -7,11 +7,11 @@
 00000060  74 20 62 65 20 72 75 6e  20 69 6e 20 44 4f 53 20  |t be run in DOS |
 00000070  6d 6f 64 65 2e 0d 0d 0a  24 00 00 00 00 00 00 00  |mode....$.......|
 00000080  50 45 00 00 64 86 09 00  08 00 00 00 00 1c 10 00  |PE..d...........|
-00000090  a1 0e 00 00 f0 00 06 02  0b 02 02 19 00 4a 09 00  |.............J..|
-000000a0  00 ce 06 00 00 f0 00 00  00 e0 01 00 00 e0 01 00  |................|
+00000090  a1 0e 00 00 f0 00 06 02  0b 02 02 1b 00 4a 09 00  |.............J..|
+000000a0  00 ce 06 00 00 00 00 00  00 e0 01 00 00 e0 01 00  |................|
 000000b0  00 00 00 00 00 00 00 00  00 10 00 00 00 02 00 00  |................|
 000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
-000000d0  00 b0 10 00 00 04 00 00  35 70 12 00 0a 00 00 00  |........5p......|
+000000d0  00 c0 10 00 00 04 00 00  6b 72 12 00 0a 00 00 00  |........kr......|
 000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000100  00 00 00 00 10 00 00 00  00 00 00 00 00 00 00 00  |................|
```

This first hunk of diff shows that there is a difference in the minor number of the linker (so toolchain is definitely a difference -- that's the first  19 vs. 1b), then in the AddressOfEntryPoint field (that's the second "line" in the first set of changes, where 00f0 vs. 0000). I'm using [PE Format doc](https://docs.microsoft.com/en-us/windows/desktop/debug/pe-format#ms-dos-stub-image-only) from Microsoft as a reference to figure this out.

The next change is between "357012" and "6b7212" -- those are checksums which we know can differ.

Have you kept the system on which the original shim was built? If so, what is the exact version of binutils there?

In general, I'd try to avoid doing extensive hieroglyphic study on the submissions, since it's very time consuming and a lot can be fixed just by making sure we use as close as possible an environment to reproduce builds. Some docker containers aren't the best for that, if the packages can be updated often during their life of the container.

**Comment by dosman0** [comment]
Please close this issue. We have canceled the original submission to MS as well.  We have reviewed and retooled our build/archive processes and will be resubmitting a new version shortly.
