### ISSUE TITLE
Updating vendor cert expiration

### ISSUE THREAD

**Issue by dbnicholson** [rhboot/shim-review#249]
This is more of a question, so sorry for abusing the issues for it. For Endless OS (most recent review #176), our vendor CA certificate is set to expire in about 4 years. I don't think shim actually checks expiration, but we'd like to regenerate the certificate to extend that much further. This is primarily for other parts of our infrastructure that do validate certificate expiration. Having shim updated with the regenerated certificate would be purely for consistency, I believe.

Will this cause any issues in review? Do you envision any issues with such a change? The rest of our shim usage is unchanged.

**Comment by SherifNagy** [comment]
I am not a member of the reviewing panelist, but I recall that within the review process they do check shim's embedded cert expiry and the duration, and I think some comments on some reviews where that the CA / cert lifetime was a bit long, so not sure what should happen here. However the question might be more related to how MSFT will treat a shim that is being submitted with expiry cert, I know that MSFT maintain the firmware dbx and not sure if they just block the shim's hash or the shim's certs hash.

**Comment by dbnicholson** [comment]
That's interesting about the length of the certificate lifetime. Last time I was making UEFI CA certificates I went and dug up Microsoft's and they use a 30 year expiration. That's what I was going to use, but I'd be interested in hearing other rationale.

As for adding to dbx for revocation, there's not actually anything to revoke. The certificate is still valid now and will remain so until it expires. The certificate I'm generating will have the same public key, subject and subject key identifier, so from an X.509 validation perspective it's the same certificate. It will just have different validity dates and a different serial number. I think that's pretty standard procedure for handling X.509 CA certificates.

**Comment by frozencemetery** [comment]
Right, shim can't check expirations because we effectively don't have a clock at that point.

As a shim reviewer, I wouldn't have a problem approving a submission that just updated cert expirations.  However, if we manage to never release a shim update in 4 years I'd be somewhat shocked - there have been 3 in the last ~15 months - and submitting a signing request for something that isn't the latest shim will raise eyebrows (which doesn't mean you can't, or that it won't be approved, just that it'll be different and therefore slower/harder).

Hope that helps.

**Comment by dbnicholson** [comment]
@frozencemetery thanks. Indeed, I don't expect to actually submit the shim signing request until we get around to a full shim update (which would include the updated vendor cert). In the meantime, I want to be able to update our infrastructure with confidence that it won't cause issues once we get around to the actual shim update. I believe the answer is "that's fine".

Good to know about why shim doesn't check expirations, too. I always figured it was because you can't require the certificates to get updated in a timely manner (since firmware updates may never happen).

**Comment by dbnicholson** [comment]
I think that's all the information I need, so I'm going to close this. Thanks!
