### ISSUE TITLE
Shim review request for Broadband Computer Company Ltd

### ISSUE THREAD

**Issue by broadbandcomputercompany** [rhboot/shim-review#25]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/broadbandcomputercompany/shim-review/tree/bccl-shim-x64-20180815 
 - [x] completed README.md file with the necessary information
https://github.com/broadbandcomputercompany/shim-review/blob/bccl-shim-x64-20180815/README.md
 - [x] shim.efi to be signed
https://github.com/broadbandcomputercompany/shim-review/blob/bccl-shim-x64-20180815/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/broadbandcomputercompany/shim-build/blob/master/bccl.cer
 - [x] any extra patches to shim via your own git tree or as files
No patches applied
 - [x] any extra patches to grub via your own git tree or as files
No patches applied
 - [x] build logs
https://github.com/broadbandcomputercompany/shim-review/blob/bccl-shim-x64-20180815/build.log

###### What organization or people are asking to have this signed:
Broadband Computer Company Ltd (http://www.broadbandcomputer.com)

###### Version of shim:
15

###### Sysdev Submission ID:
We were directed to the shim review board by Microsoft after submitting our shim to them for signing. Subsequently our original sysdev submission has been closed pending approval from the shim review board.

###### What product or service is this for:
Secure COAST 

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:

Secure COAST is a security focused linux distro based on Ubuntu 18.04. 
We encourage our customers to boot our OS with secure boot enabled, hence the need for a 
signed shim.

**Comment by cyphermox** [comment]
I'll do this review. It's shim 15, with a dockerfile for build, seems like everything should be straightforward and complete enough for the review to go quickly.

**Comment by cyphermox** [comment]
Build is easily reproducible using the included Dockerfile.

What steps are you taking to ensure the security of your signing key embedded in shim? Is it an EV cert?

How do you maintain the chain of trust given that you include your own certificate in shim, but claim to be using the GRUB bootloader and kernel from Ubuntu with no changes?

**Comment by broadbandcomputercompany** [comment]
Hi Mathieu

Thanks for reviewing this for us and I'm pleased the Dockerfile bundling of the build process made it easy for you to replicate the build (I took inspiration for this set up from another shim review submission which looked incredibly neat).

The certificate embedded in the shim is a self created and authorised certificate with a long expiry date. The purpose for this is to avoid having to go back through this process again in the near future when, for example, an EV certificate (which we also possess for the purposes of signing Windows software components and also as required for the submission of EFI signing requests to MS) which only has a life of 12 months would expire (I note another recent submission was caught out by this as a result of embedding an EV certificate in their shim build).

Wrt security of the certificates and related key pair, these are kept on encrypted storage and only accessable to myself (CTO) and other high ranking members of our company. Their use is solely for the purpose of signing components required as part of the EFI boot process.

In terms of maintaining the chain of trust, we shall be signing GRUB and the Ubuntu kernel with our own certificate in addition to any kernel driver modules which are required to support our distribution. It is this last requirement, the necessity to sign 3rd party driver modules in order for Ubuntu to be able to load these modules whilst operating under secure boot mode, which has required us to undertake this development requiring this review, having first ran into issues being unable to load unsigned webcam and WiFi drivers (eg Broadcom) without disabling secure boot.

I hope I've managed to answer your question adequately. Please let me know if you require any further info.

Best regards, Brian.

**Comment by broadbandcomputercompany** [comment]
Hi Mathieu
Is it possible to progress this application to the accepted state now? We have an upcoming release that depends upon this functionality and we still need to put the shim through the Microsoft signing process which is also going to take some time. Please let me know if you have any further questions.
Best regards, Brian.
