### ISSUE TITLE
Shim 15.6 for AlmaLinux OS 8

### ISSUE THREAD

**Issue by andrewlukoshko** [rhboot/shim-review#250]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
`https://github.com/AlmaLinux/shim-review/tree/almalinux-8-shim-x64-20220620`

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
```
bfa0e10640c38b32bcd69ef7bf482c1084acb20447ae68b329e3f85377353a9f  shimia32.efi
dff56ad39c7fb354e4bf0f2866b7da7b45dab472a26e2e5b671363e0c7898354  shimx64.efi
```

**Comment by andrewlukoshko** [comment]
PGP keys on keyserver.ubuntu.com:
https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xafb1408dcf15f687
https://keyserver.ubuntu.com/pks/lookup?op=vindex&search=0xd2f7f2686583bd6e

**Comment by andrewlukoshko** [comment]
@frozencemetery hello, we need security contacts verification here

**Comment by steve-mcintyre** [comment]
I've sent mail to do identity verification

**Comment by jaboutboul** [comment]
fairway bowing palled Chicago grievous strictly scoff mitering Isuzu giggly

**Comment by steve-mcintyre** [comment]
Looking:
- Builds reproduce here
- Certs look OK: both EV certs expiring in 2025 (nit: it would be much easier to compare the certs to what's in the shim binary if you generated the .esl file from them at runtime)
- signing keys managed in an HSM
- SBAT data looks ok
- shim builds from upstream 15.6 with no patches
- grub config looks ok, borrowed from RHEL
- Linux config and patches sound OK, also from RHEL
- first submission, so no old binaries to revoke

Questions:
- you've derived your grub from RHEL accoeding to your SBAT. What about fwupd?

**Comment by andrewlukoshko** [comment]
anthracite worksheets rude impinging emasculates keyboarding corral riskiness wraiths superimposing

**Comment by andrewlukoshko** [comment]
@steve-mcintyre fwupd comes from RHEL too

**Comment by steve-mcintyre** [comment]
> @steve-mcintyre fwupd comes from RHEL too

OK, you should probably update the embedded SBAT data to reflect that then (checking what's in your README.md). Not a big thing, but it's useful for potential revocations.

**Comment by steve-mcintyre** [comment]
Verification done, all questions done. No issues remaining, marking as accepted.

**Comment by andrewlukoshko** [comment]
Thanks!

**Comment by frozencemetery** [comment]
@andrewlukoshko did you get a signed shim?
