### ISSUE TITLE
Shim 15.6 for CloudLinux OS 8

### ISSUE THREAD

**Issue by andrewlukoshko** [rhboot/shim-review#251]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
`https://github.com/cloudlinux/shim-review/tree/cloudlinux-shim-x86_64-20220621`

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
```
96dd31a8e0c9a2bb278a63be330c65b664b71b72a941e2959f8df5a596f8811a  shimia32.efi
dd2b4413b033df6a0152a2831804097a8a99e098b65de415d83807d285577ab7  shimx64.efi
```

**Comment by andrewlukoshko** [comment]
@frozencemetery hello, we need security contacts verification here

**Comment by steve-mcintyre** [comment]
verification emails sent

**Comment by andrewlukoshko** [comment]
impressionism phalanges disturbs heathenish majorettes abler bounds semiprecious ungodly bragging

**Comment by steve-mcintyre** [comment]
Checking:
- shim builds reproduce here
- Cert looks OK: EV cert from Certum, expires 2024
- signing keys in an HSM
- SBAT data looks ok
- minor nit in the fwupd SBAT: please add the RHEL data too if you're derived
- 15.6, no patches
- grub confif and patches all borrowed from RHEL
- Similar for Linux
- old shim and grub binaries will be blocked appropriately

All looks good, just waiting on the veriffication to complete!

**Comment by andrewlukoshko** [comment]
@steve-mcintyre Leonid's words:
`parts warhorse métier Jeannette Buick Elbe milked soundproofs axe ravines`

**Comment by steve-mcintyre** [comment]
all done, approved!

**Comment by andrewlukoshko** [comment]
Thanks!

**Comment by andrewlukoshko** [comment]
Shim is signed by MS, closing.
