### ISSUE TITLE
shim-15.6 for ZeronsoftN

### ISSUE THREAD

**Issue by joseph-zeronsoftn** [rhboot/shim-review#254]
Confirm the following are included in your repo, checking each box:

 - [X] completed README.md file with the necessary information
 - [X] shim.efi to be signed
 - [X] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [X] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [X] any extra patches to shim via your own git tree or as files
 - [X] any extra patches to grub via your own git tree or as files
 - [X] build logs
 - [X] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------

https://github.com/zeronsoftn/shim-review/tree/zeronsoftn-shim-x86_64-20220627

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------

```
473133c16e9ae07f3d27c5f4e7968da57b6fdbf893b77eb329269f3925e92106  shimaa64.efi
d7f4c74156264b3848b82352c0284107f37d09776f1eb0448dc575c8b876d7c4  shimia32.efi
f19621c78390a3a0464930522d85683e47ade0e4fd691a8c2c8d6ced6fe7282f  shimx64.efi
```

Previous submissions: #147

**Comment by frozencemetery** [comment]
Your contact information has changed - it would have been helpful to call this out.  Why does Joeseph Lee have a new key?

**Comment by joseph-zeronsoftn** [comment]
@frozencemetery The key has expired and a new one has been created.

**Comment by frozencemetery** [comment]
Okay, but why did you do that instead of renewing the expired key?

**Comment by joseph-zeronsoftn** [comment]
@frozencemetery Actually, there is no big reason. I thought it was not good to use the same key for a long time.

**Comment by steve-mcintyre** [comment]
@frozencemetery are you going to look at this review again?

**Comment by frozencemetery** [comment]
Please note https://github.com/rhboot/shim-review/issues/307
