### ISSUE TITLE
Shim 15.4 for SUSE Euler Linux

### ISSUE THREAD

**Issue by parheliamm** [rhboot/shim-review#255]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
`https://github.com/parheliamm/shim-review/tree/sel-2.0-shim-20220628`

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
aarch64:
pesign --hash --padding --in usr/share/efi/aarch64/shim-sel.efi 
hash: 68237d2b12f0244ff2132d682c280ed82ac61be38239eba6bbf9d85533704c4e

sha256sum ./shim-sel_aarch64.efi
62a566791f05dfa9d97dd46f71ff7eb180a3ddf7f54374cfd0588964c800b14d  shim-sel_aarch64.efi

x86_64:
pesign --hash --padding --in=./shim-sel_x86_64.efi
hash: 019a6dff58ad3c47788bb1ff7795797d3d1a1a31ce8e4463593ef53f9e43d93b

sha256sum ./shim-sel_x86_64.efi 
caf985b34fb5960708df6a30d7e49b6ea0a46d754bf5264831334ed88f37f840  shim-sel_x86_64.efi

**Comment by julian-klode** [comment]
outdated request due to the recent round of CVEs in grub and shim requiring a new submission with fixes for all these CVEs.
