### ISSUE TITLE
shim 15+1533136590.3beb971 for Ubuntu

### ISSUE THREAD

**Issue by cyphermox** [rhboot/shim-review#26]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag:

https://github.com/CanonicalLtd/shim-review/tree/ubuntu-shim-amd64+arm64-20180822

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

###### What organization or people are asking to have this signed:
Ubuntu

###### Version of shim:
shim 15-based snapshot, up to commit 3beb971

###### What product or service is this for:
Ubuntu

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
This is a well-known Linux distro.

**Comment by vathpela** [comment]
Well, right now I can't get this to work. On my first attempt, my local build wound up with a .eh_frame section that's larger than yours.  I decided I might have introduced a toolchain error, so I tried again, and this time I get:

```
root@clever-egret:~# add-apt-repository ppa:canonical-foundations/shim
 devirt (but x86-only) ppa for building shim binary packages, so they live somewhere other than -proposed while awaiting SecureBoot signing
 More info: https://launchpad.net/~canonical-foundations/+archive/ubuntu/shim
Press [ENTER] to continue or Ctrl-c to cancel adding it.

'Error reading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&exact=on&search=0xCDE5112BD4104F975FC8A53FD4C0B668FD4C9139 (3 tries): Service Unavailable'
```
I suspect that's a transient error on the other end of the network, so for now I'm going to put this down and come back to it either later today or tomorrow.

**Comment by vathpela** [comment]
The updated version of this looks good to me.

**Comment by cyphermox** [comment]
Submission IDs:

 - shimx64 - 14524649745353396
 - shimaa64 - 14331838088421456
