### ISSUE TITLE
Rocky Linux 8 shim-15.6 x64 and ia32

### ISSUE THREAD

**Issue by SherifNagy** [rhboot/shim-review#274]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
`https://github.com/rocky-linux/shim-review/tree/refs/tags/rockylinux-8-shim-15.6-x86_64-20220817`

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
afbf3a7538194ff130bf60979252a8f425dc3cbfdee176c40f018733719d8efa  shimx64.efi
fc1eddf678dcc8e039544b409d92db564a97be6e7a7bd7ac5f2aaf9da628b9eb  shimia32.efi

-------------------------------------------------------------------------------
### What is the link to your previous shim review request (if any, otherwise N/A)?
-------------------------------------------------------------------------------
For Rocky Linux 8 we have #194

**Comment by steve-mcintyre** [comment]
Very similar to #273, of course
Looking:
- No need for contact verification, already done in #273
- shim builds reproduce here
- shim from upstream, no patches
- Includes a CA key with ~9 years left, ok
- SBAT data looks (mostly!) fine
- revocation story is fine
- kernel looks fine, borrowed from RHEL
- HSM for key management
- grub looks ok, borrowed from RHEL
- list of grub modules looks fine

Things to check/fix:
- your quoted grub SBAT still contains @@VERSION@@ (and so did the submission in #273, missed that yesterday)

**Comment by steve-mcintyre** [comment]
No worries, all good now!

**Comment by SherifNagy** [comment]
Closing, we got back the signed shim from Microsoft
