### ISSUE TITLE
 Lernstick shim-15.6-1 x64 (20220817)

### ISSUE THREAD

**Issue by ronnystandtke** [rhboot/shim-review#275]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
`https://github.com/Lernstick/shim-review/tree/lernstick-shim-amd64-20220817`

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
`138bcb7ebc81ac44324122b04d0e4dc6aef63d3d7fd04ddaa9d856cde1cde78e shimx64.efi`

-------------------------------------------------------------------------------
### What is the link to your previous shim review request (if any, otherwise N/A)?
-------------------------------------------------------------------------------
Previous (accepted) submission: https://github.com/rhboot/shim-review/issues/196

**Comment by steve-mcintyre** [comment]
Looking:
- identity verification not needed (#196)
- shim reproduces ok here
- upstream 15.6, no patches
- includes a CA key with ~9y left, ok. Following a similar strategy to Debian, ok
- SBAT data looks (mostly!) OK (seel below), including upstream Debian data
- revocation story looks good
- kernel sounds ok, borrowed from Debian
- HSM for key management, ok
- grub looks (mostly) OK, borrowed from Debian
- list of grub modules is fine

Issues / queries
- you mention a Debian grub version 2.06-4, but that doesn't actually exist yet!

**Comment by ronnystandtke** [comment]
Hi Steve,

Thank you for your review!

We have taken the latest git snapshot of the Debian package, therefore it was build on top of the unreleased 2.06-4.
Because the content of 2.06-4 might change before release and to avoid confusion we are now using 2.06-3 as the base.
The new tag is here (only the grub version numbers have changed):
https://github.com/Lernstick/shim-review/tree/lernstick-shim-amd64-20220819

**Comment by steve-mcintyre** [comment]
Yeah, that was exactly my worry on the Debian grub package. Thanks for fixing!

**Comment by steve-mcintyre** [comment]
All good now, marking accepted

**Comment by ronnystandtke** [comment]
Thank you for the review. We just received a signed Shim.
