### ISSUE TITLE
shim 15.6 for elux-20220819

### ISSUE THREAD

**Issue by christoph-at-unicon** [rhboot/shim-review#277]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed (as shimx64.efi)
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [n/a] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [n/a] any extra patches to shim via your own git tree or as files
 - [n/a] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
`https://github.com/UniconSoftware/shim-review/releases/tag/unicon-shim-amd64-20200918`

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
3ab8a8f5c054e577e1d07ca49e718c21e2a80dfe8dce50e5fc220e9eee7ec043  shimx64.efi

-------------------------------------------------------------------------------
### What is the link to your previous shim review request (if any, otherwise N/A)?
-------------------------------------------------------------------------------
(https://github.com/rhboot/shim-review/issues/124)

**Comment by SherifNagy** [comment]
I am not a reviewer, but it seems like your shim is not the latest 15.6 as stated in the title and the repo tagged is from 2020

**Comment by steve-mcintyre** [comment]
Agreed, adding a Bug label here.

**Comment by christoph-at-unicon** [comment]
Okay, seems there was a mess with the branches. I assume you're seeing commit 8d535c9 from 2020 in the "master" branch - you ought to see commit 2e23e01 in the "main" branch. Should I open a new PR?
As same background, the old one is from the previous review request (#124).

**Comment by SherifNagy** [comment]
> Okay, seems there was a mess with the branches. I assume you're seeing commit [8d535c9](https://github.com/rhboot/shim-review/commit/8d535c917f3f689cd579d145ab158ef27460969c) from 2020 in the "master" branch - you ought to see commit [2e23e01](https://github.com/rhboot/shim-review/commit/2e23e014cba91a1efc58eacef87a5cf74327b565) in the "main" branch. Should I open a new PR? As same background, the old one is from the previous review request (#124).

*** Not an official reviewer, so this information might be wrong, but this is what we did and seems like what other vendor do ***
I don't think you should be opening PR against rhboot/shim-review repo, you should clone the repo to your own github, do the edits and upload the needed files if applicable then tag that branch " on your github " and post the tag here in the issue / ticket you open for review , seems like this has been done before in issue #124 with https://github.com/UniconSoftware/shim-review/releases/tag/unicon-shim-amd64-20200918 as the tagged review source, you need to do the same with for the new submission with new sources you need to get reviewed, more info here https://github.com/rhboot/shim-review

**Comment by frozencemetery** [comment]
Your submission still says 15.2 ("HEAD of shim/15.2").  I'm going to close this; if you still need a signed shim, please open a new review based on 15.7.
