### ISSUE TITLE
ubuntu-shim-amd64+arm64-20221118 (15.7-0ubuntu1)

### ISSUE THREAD

**Issue by julian-klode** [rhboot/shim-review#298]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed ) `don't have any`
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries
 
:information_source:  We have a GitHub workflow that conveniently checks reproducibility and also dumps SBAT and hashes for your convenience!

-------------------------------------------------------------------------------
### What is the link to your tag in a repo cloned from rhboot/shim-review?
-------------------------------------------------------------------------------
https://github.com/CanonicalLtd/shim-review/tree/ubuntu-shim-amd64+arm64-20221118

You'll see the badge at the commit at the top is green, indicating the workflow successfully reproduced the binaries.

-------------------------------------------------------------------------------
### What is the SHA256 hash of your final SHIM binary?
-------------------------------------------------------------------------------
```
$ sha256sum shim*.efi
d02697ef3c6a2a4980e3b2ceedce0fd6591ff10e163fe6f7678553723a366254  shimaa64.efi
ab1b96c04a3898253c5f8b381cc21e0d03c5e5f674fd102070afefb8469ed8fc  shimx64.efi
```

-------------------------------------------------------------------------------
### What is the link to your previous shim review request (if any, otherwise N/A)?
-------------------------------------------------------------------------------
issue #190

**Comment by frozencemetery** [comment]
This can optionally use a systemd second stage.

**Comment by frozencemetery** [comment]
Also, how you build your packages is ultimately to you, but the pages of "install: WARNING: ignoring --strip-program option as -s option was not specified" are a bit much, yeah?

**Comment by julian-klode** [comment]
Yeah I don't know where the --strip-program comes from exactly, needs more investigation.

We use the tiny systemd-boot stub, which loads its own embedded kernel (it's one signed binary for the whole), not the systemd-boot bootloader.

**Comment by julian-klode** [comment]
MS submissions:

shimaa64.efi (14614433294396992)
shimx64.efi (13715497686671834)

**Comment by steve-mcintyre** [comment]
# Checked and fine
- No need for contact verification, already have a trust path
- Shim from upstream, one patch which we've already accepted before
- Minor tweaks to shim build options are fine
- Includes a CA key with >9 years left, ok
- SBAT data looks fine
- Reasonable description of kernel patches and config
- Revocation story is fine
- CA key management description is ok, but no mention of how the **signing** keys are managed - see below
- Grub looks ok
- List of grub modules looks fine
- Shim builds reproduce fine for both amd64 and arm64

# Things to fix
- Please describe how your **signing** keys are managed

# Grumbles (not a blocker for this review)
- Please clean up your review repo, you're still listing a load of older patches in shim-patches that already went upstream 
- I've not yet seen a security review of the systemd-boot stub to be 100% happy with it. What version(s) are you using?

**Comment by julian-klode** [comment]
The signing keys are wrapped by an HSM as part of the lp-signing service.

That service is accessible to the launchpad admins, and they install the keys into signing PPAs. Only a special set of a handful of people can copy packages to those PPAs for signing, not including me.

Previous signing keys were installed into the main archive and lead to accidental signing as any archive admin could approve signing requests, and signing requests where generated automatically by uploading grub, this is no longer possible. It's much better safety now :)

### stub
The systemd-boot stub is fairly small and combined with the kernels into a single image, and it can only load the kernel embedded with it, so we do not really consider it a 2nd loader but more a replacement for the kernels EFI stub.

I don't have a complete view of what is being used, it's safe to assume we use the stub on all releases where Ubuntu Core is released, with their respective versions, so since 16.04 Ubuntu.

**Comment by julian-klode** [comment]
Sorry about the patches, I don't know what happened there. Only the no vendor dbx patch remains, the full tree is at the https://git.launchpad.net/~ubuntu-core-dev/shim/+git/shim/tree/debian

**Comment by steve-mcintyre** [comment]
Ok, all good now IMHO

**Comment by julian-klode** [comment]
Signed shims have been received, thanks!
