### ISSUE TITLE
2017-12-16 Deepin #2050412 / #2048383

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#3]
Date: Sat, 16 Dec 2017 14:05:44 +0800
Subject: [Shim-review] Shim review request for Deepin - MS Sysdev Submission #1935785

Hello Everyone.

I would like to request a shim review for Deepin to get it signed by UEFI CA. Submission id is #1935785.

Deepin (https://deepin.org/en) is yet another linux distribution based on Debian GNU/Linux. It has been actively maintained since 2011.
 It is used in middle schools and governments in China.

Current submission is based on shim package found in Debian upstream repo. Only uefi-ca file is replaced by our own.
All of its content can be found at : https://github.com/xushaohua/shim-review. "shimx64-unsigned.efi" is the EFI file to be signed.

Regards,
Xu Shaohua
------------------
Wuhan Deepin Technology Co., Ltd.

**Comment by cyphermox** [comment]
For now, this is missing too much information to succesfully complete a rebuild. I sent an email to ask for further info.

**Comment by XuShaohua** [comment]
Hi @cyphermox 

Thank you for your work. And really sorry to reply after so long.

I've read shim-review (https://github.com/rhboot/shim-review) work flow.
And now the latest version of shim (v14) has been submitted to sysdev, based on this process.

Submission ids are:
shim ia32: #2050412
shim x64: #2048383

And shim-review project of this submission is https://github.com/xushaohua/shim-review

Shim efi files in these submissions have been checked based on an article of microsoft sysdev blog
(https://blogs.msdn.microsoft.com/windows_hardware_certification_ch/2013/12/04/uefi/).

Could you help to review this new submission? Thank you in advance.

Have a nice day.

**Comment by XuShaohua** [comment]
@vathpela Hi, Peter. Would you please take some time to help me review this submission? Thanks.

**Comment by vathpela** [comment]
So, there's still a couple of issues here:
1) I've tried to duplicate your shimia32.efi binary, and had some success - but it's not going to work, and I have some questions.

It looks like you've removed --no-undefined from the ld arguments in the Makefile?  And as a result (and due to a bug in the makefile) you're building it against the x86_64 version of libgcc.a, which results in having a .rel.plt section that is not properly aligned.  That in turn will make the resulting signature invalid.

So something's going to have to be done about that.  If you're okay rebuilding with shim-15 that should all get fixed automatically; if not, I'm going to have to help walk you through making shim-14 work on ia32.  (If you actually need a 32-bit bootloader?)

2) I can reproduce your shimx64.efi build just fine.  So if you want to rebuild it with shim-15 that's fine, but if you'd rather just keep with this build, I don't have any problem with that.

3) https://github.com/xushaohua/shim-review says you have no kernel patches.  You should at least carry the set of patches to enforce the Secure Boot policies.  If you clone the repository at https://github.com/vathpela/linux/tree/secure-boot-4.14 and run `git format-patch v4.14..secure-boot-4.14`, it'll generate the series of patches you should use.

**Comment by XuShaohua** [comment]
@vathpela 
Hi Peter,

I've upgrade to shim-15 on weekend. The new submission ids are #2259423 (ia32) and ##2259422 (amd64). These EFI files are also tested. shim-review link is at https://github.com/XuShaohua/shim-review .

Linux 4.14 is also patched with secure-boot-4.14, and I'll merge these patches to later version of kernel. It would be great if these patches can be merged to upstream.

Thank you for your work.

**Comment by XuShaohua** [comment]
@vathpela 
Hi Peter,
Can you please help review this new submission? If there is any issue about it, please let me know.

CC @martinezjavier @haobinnan

**Comment by XuShaohua** [comment]
@vathpela Please help close this issue, thx.

**Comment by nohappiness** [comment]
> @vathpela Please help close this issue, thx.

Hi @vathpela , @XuShaohua has step down his position and due to the long time of no response, he has removed his `shim-review` project. Please help us close this issure, and I'll open a new one with more detailed information.

Many thanks.

CC @cyphermox

**Comment by julian-klode** [comment]
Closing this review requests as it is from before 2019, and likely not valid anymore. Also note that we just added some new questions, and if you submit a new review request with the current question set, also include a Dockerfile to build the shim to not slow down review.
