### ISSUE TITLE
NewStartOS V4 shim-15.6 x64 and ia32

### ISSUE THREAD

**Issue by LiangJianNSDL** [rhboot/shim-review#303]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
https://github.com/LiangJianNSDL/shim-review/tree/nsdl-v4-shim-amd64-i386-20230306

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
sha256sum shimia32.efi
a3ff0cc4313616cb3dfb0784b75c66481ec1625735ea912215f9f403c0d6cedf  shimia32.efi
sha256sum shimx64.efi
a9ee49df074e4edce671c60090c8223c7aa0be872c32565ce4d497136629db28  shimx64.efi

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
https://github.com/rhboot/shim-review/issues/289

**Comment by frozencemetery** [comment]
Please note https://github.com/rhboot/shim-review/issues/307

**Comment by LiangJianNSDL** [comment]
> Please note #307
Hi, frozencemetery. I have applied NX.patch to shim, you can check the build.log to find relevant information, and I have updated shimia32.efi shimx64.efi NX.patch and other related files, you can find them in the link above. Thank you for your reply.

**Comment by frozencemetery** [comment]
>> Were these binaries created from the 15.6 shim release tar?
> This is the unmodified shim-15.6 release.

>> What patches are being applied and why:
> None.

**Comment by LiangJianNSDL** [comment]
> It is written:
> 
> > > Were these binaries created from the 15.6 shim release tar?
> 
> > This is the unmodified shim-15.6 release.
> 
> and
> 
> > > What patches are being applied and why:
> 
> > None.
Thanks for your reminding, I have updated the README.md. Thanks again.

**Comment by LiangJianNSDL** [comment]
Hi,frozencemetery
What does "contact verification needed" label mean? What do I need to do. 
Looking forward to your reply. @frozencemetery

**Comment by steve-mcintyre** [comment]
Picking up on this review now, apologies for the delay. :-(

I've just mailed both of your contact addresses now to start contact verification. Please follow the instructions there.

**Comment by steve-mcintyre** [comment]
# Review of NewStartOS V4 shim-15.6 x64 and ia32 nsdl-v4-shim-amd64-i386-20230306

## OK

- No previous shims signed, so revocation is easy
- Shim builds reproduce fine for ia32 and x64
- Shim from 15.6 upstream, with the NX patch applied.
- SBAT data looks fine
- Grub looks ok, borrowed from RH/Rocky
- List of grub modules looks OK for now
- Kernel lockdown sounds ok

## Issues / queries / outstanding

- Contact verification reequired - mails sent
- This is a shim 15.6 submission - you **must** move forwards to a current
  version if you're going to get a signed shim now.
- The cert you've embedded looks bogus (please fill in some sensible
  details!), and it has **already expired**.
- Key split up and managed separately. How are you signing kernel and
  grub builds?
- Do you not include fwupd in your distribution?

**Comment by steve-mcintyre** [comment]
It's been a few weeks without comment. Need to move forwards from 15.6.
