### ISSUE TITLE
HP Inc - ThinPro - shim - 20181005

### ISSUE THREAD

**Issue by eniaczhp** [rhboot/shim-review#34]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

# What organization or people are asking to have this signed:

    HP Inc.

# What product or service is this for:

    HP ThinPro

# What's the justification that this really does need to be signed for the whole world to be able to boot it:

    HP would like ThinPro to be bootable on any device without disabling SecureBoot.

# Who is the primary contact for security updates, etc.

    Name: Eniac Zhang
    Position: Engineer
    Email address: eniacz@hp.com
    PGP key, signed by the other security contacts, and preferably also with signatures that are reasonably well known in the linux community: n/a

# Who is the secondary contact for security updates, etc.

    Name: Clemenceau, Matthieu <matthieu.clemenceau@hp.com>
    Position: Manager
    Email address: matthieu.clemenceau@hp.com
    PGP key, signed by the other security contacts, and preferably also with signatures that are reasonably well known in the linux community: n/a

# What upstream shim tag is this starting from:

    https://github.com/rhboot/shim/tree/13

# URL for a repo that contains the exact code which was built to get this binary:

    https://github.com/eniaczhp/ThinProShim/tree/20181001

# What patches are being applied and why:

    abort_abort_abort.patch: define abort to avoid an unnecessary reloc.

# What OS and toolchain must we use to reproduce this build? Include where to find it, etc. We're going to try to reproduce your build as close as possible to verify that it's really a build of the source tree you tell us it is, so these need to be fairly thorough. At the very least include the specific versions of gcc, binutils, and gnu-efi which were used, and where to find those binaries.
   
    See method.txt for configuration details

# Which files in this repo are the logs for your build? This should include logs for creating the buildroots, applying patches, doing the build, creating the archives, etc.

    See build.log

# Put info about what bootloader you're using, including which patches it includes to enforce Secure Boot here:

    It's grub2 with the well known set of secure boot patches (among other patches.)

# Put info about what kernel you're using, including which patches it includes to enforce Secure Boot here:

    It's currently targeted to ship with 4.18.7 kernel, which has the well known set of secure boot patches.

**Comment by eniaczhp** [comment]
any updates?  this request has been open for over 10 days.

**Comment by cyphermox** [comment]
Rebuild was successful; this is a build with about no changes from shim 13 in git (except for the abort patch)

I find this shim acceptable for signing:

`36aaffee2f1bb5ec4e631805fff6a81ed007fa41bb8b9b171912be0714c1a69b  shimx64.efi
`

**Comment by cyphermox** [comment]
Still, can we have a look at the patchset for grub? Is that published somewhere?

**Comment by eniaczhp** [comment]
this is the grub we use: https://packages.ubuntu.com/xenial/admin/grub2

also is the md5sum you posted from your own build?  the shimx64.efi produced by my build (also in submission under assets has a different md5sum:
bcf34b7a6f2d03f7ef4e87b56864e409  assets/shimx64.efi

which one do we expect MS to sign?
