### ISSUE TITLE
DS-shim-x86_64-20181012

### ISSUE THREAD

**Issue by RiottSquad** [rhboot/shim-review#36]
Make sure you have provided the following information:

 - [X] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
	https://github.com/AdvancedDesignCorp/shim-review/tree/DS-shim-x86_64-20181012
 - [X] completed README.md file with the necessary information
 - [X] shim.efi to be signed
 - [X] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [X] any extra patches to shim via your own git tree or as files
 - [X] any extra patches to grub via your own git tree or as files
 - [X] build logs

###### What organization or people are asking to have this signed:
Advanced Design Corp. (https://www.a-d.co.jp/)

###### What product or service is this for:
DataSweeper (This refers to methods of totally erasing data from storage media that can then be reused.)

###### What is the origin and full version number of your shim?
15

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
The loader is used to load and start our native UEFI based pre-boot authentication.
It's essential to be able to provide software that works with every machine that has Secure Boot enabled.

###### How do you manage and protect the keys used in your SHIM?
Only public keys are in SHIM as it verifies signatures of loaded components.

###### Do you use EV certificates as embedded certificates in the SHIM?
No

###### What is the origin and full version number of your bootloader (GRUB or other)?
grub2 2.02+dfsg1-12

###### If your SHIM launchers any other components, please provide further details on what is launched
No

###### How do the launched components prevent execution of unauthenticated code?
N/A

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
grub2 2.02+dfsg1-12

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Currently targeted to ship with 4.14.xx kernel.
No additional modifications or patches applied.

###### What changes were made since your SHIM was last signed?
N/A

###### What is the hash of your final SHIM binary?
(sha256) ad49b4afbec5cf763b9ea97347c7a397802f0ba79412d2e4caa2e0b7776ca9b5  shimx64.efi

**Comment by cyphermox** [comment]
I do not understand very well how this works. Does it start GRUB, or does it start your "native UEFI based pre-boot authentication". Why not have your UEFI code signed by Microsoft then?

Please tell us more about what and how things are booting when DataSweeper is installed.

**Comment by RiottSquad** [comment]
DataSweeper is UEFI bootable live Linux system (core component)
The core component uses GRUB to be able to provide users more than one way of booting up the program as a Live-Linux system.

**Comment by cyphermox** [comment]
What version of grub is in use? How are you building that part? Are any additional patches applied to it?

**Comment by RiottSquad** [comment]
Please see my coments bellow. 

> What version of grub is in use? 
> Are any additional patches applied to it?

GRUB2 with no patche
https://github.com/rhboot/grub2

> How are you building that part? 

Ubuntu 18.04.1 LTS (Kernel 4.15.0-34-generic) 
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0 
gnu-efi 3.0.8-0ubuntu1~18.04.1

If I need to do something else, please let me know.

**Comment by cyphermox** [comment]
Grub2 with no patches from that tree's master branch would not include sufficient code to enforce Secure Boot. Furthermore, why build it on Ubuntu if you're using RH code?

**Comment by RiottSquad** [comment]
> Grub2 with no patches from that tree's master branch would not include sufficient code to enforce Secure Boot. Furthermore, why build it on Ubuntu if you're using RH code?

I have put wrong ling by mistake. I apologize for this.
This is correct link.

[ftp://ftp.gnu.org/gnu/grub/grub-2.02.tar.xz](url)

**Comment by cyphermox** [comment]
That doesn't change anything though. What patches are you applying on top of that to support UEFI Secure Boot and enforce that loaded UEFI binaries are verified?

Please provide complete and clear instructions so we can rebuild these pieces to check that shim is indeed what we expect it to be.

**Comment by RiottSquad** [comment]
Sorry for my late response.
Changed the function to use grub2 2.02+dfsg1-12.

There isn't any problem with that based on this understanding, is there?

**Comment by RiottSquad** [comment]
I understand that you are very busy, but If I need to do something else, please let me know. 
Thank you.

**Comment by cyphermox** [comment]
Could you please include the source tarball or a built binary for your grub?

I am not sure I understand exactly how this works. How is a system using DS supposed to boot? Which pieces of software will be loaded in what order?

**Comment by RiottSquad** [comment]
DataSweeper ("DS") is an application specifically designed for Linux OS.
In order to run DS, the user will need dedicated hardware such as USB dongle.
And for that reason, you'd need boot the dedicated Linux kernel with built-in miniroot (initramfs) which enables hardware check.
We expect the dedicated kernel itself should be operated more than one PCs with various models & configurations.
The more the target PCs on which the DS application will be running, the more chances we'll have of updating the Build of the dedicated Kernel.
If the dedicated Kernel will complete the hardware check with successful result, it will then shift to the Live-Linux system and install the drivers which is necessary for the DS to be setup & boot on the target PCs.
To be able to boot this dedicated Kernel on the PCs with enabled Secure Boot setting, you will need a corresponding Grub (and Shim).

**Comment by julian-klode** [comment]
Closing this review requests as it is from before 2019, and likely not valid anymore. Also note that we just added some new questions, and if you submit a new review request with the current question set, also include a Dockerfile to build the shim to not slow down review.
