### ISSUE TITLE
Existing shim reviews and the 15.8 release

### ISSUE THREAD

**Issue by jason-rodri** [rhboot/shim-review#364]
I have a question concerning organizations who have outstanding 15.7 shim reviews and how we should approach the 15.8 shim release.

Should we update our existing 15.7 reviews with the 15.8 release or should we create an additional review for the 15.8 release?

With the 15.8 release now public will an existing 15.7 shim review be approved?

**Comment by kukrimate** [comment]
15.8 fixes security issues, no more 15.7 shims should be signed.

**Comment by enriched** [comment]
@kukrimate thank you for clarifying that. Do you know if updating the current review would be acceptable, or are people typically asked to create a new review?

**Comment by SherifNagy** [comment]
I would say opening a new submission will make everyone's life easier, but that's my personal preference

**Comment by jsetje** [comment]
I'd like to propose that all 15.7 based submissions be closed asking for a 15.8 based one. One of the CVEs addressed in 15.8 has a disturbingly high score and I could see revocations for 15.7 become mandatory very suddenly.

**Comment by THS-on** [comment]
@jsetje now went through the submissions asking people either to update or create new ones.

If they don't respond in a timely fashion, I'll close them.

**Comment by THS-on** [comment]
everybody seems now to have responded to the updating requests, therefore closing this one
