### ISSUE TITLE
Shim 15.8 for CloudLinux OS 8

### ISSUE THREAD

**Issue by andrewlukoshko** [rhboot/shim-review#365]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
[`https://github.com/cloudlinux/shim-review/tree/cloudlinux-shim-x86_64-20240126`](https://github.com/cloudlinux/shim-review/tree/cloudlinux-shim-x86_64-20240126)

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
```
643009b06fd4e7494f4555e6488eb9728b216a40e8d8eefa0feea65f0be3b9c0  shimia32.efi
47135ec9676de5abfe0a596c89fd992247a9ab16f700c26e8a14aee213f17423  shimx64.efi
```

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
shim-15.4: https://github.com/rhboot/shim-review/issues/152  
shim-15.6: https://github.com/rhboot/shim-review/issues/251  

Secondary security contact changed since last review and needs verification.

**Comment by SherifNagy** [comment]
New security contact's verification email has been sent out

While I am not an official reviewer, here are my comments "looking at latest tag: https://github.com/cloudlinux/shim-review/tree/cloudlinux-shim-x86_64-20240126 ":

* SHIM sources within the SRPM matches the release hash
* New SHIM's CA valid for 10 years
* SHIM binary reproducible correctly
* Contacts GPG keys looks good
* CA and certs protection story looks good
* Kernel patches and lockdown configurations story looks good "Kernel is RHEL + Their own LVE module" . See note below
* Grub modules looks good, matches RHEL "source is borrowed from RHEL"
* SBAT entries looks good and keeping the RHEL upstream entry "shim still haven't revoked grub < 4 yet, so grub,3 entry is acceptable" 

About LVE kernel module, just to confirm, this seems to be an out-of-tree kernel module with kmod based on my finding, I can't find any source code mortification to the kernel package itself, is that correct?

I think we need one more official reviewer to look at this submission, best of luck with the submission :)

**Comment by andrewlukoshko** [comment]
@SherifNagy verification email:
`Eiloh7ph aiNieW9h agaiC6ru ce2eS7zo quubee2E eu7ieTai`

**Comment by SherifNagy** [comment]
Words matches what I have sent to Dmitry Morozov, the second security contact.

@andrewlukoshko can you confirm what modification are done to the kernel sources to support LVE? as far as I can tell, I see you are using external out-of-tree kernel module kmod-lve, I can't find any patches to the kernel other than just modification to the SPEC file to conflict and requires kmod-lve specific version. Is that all?

**Comment by andrewlukoshko** [comment]
@SherifNagy almost.

CloudLinux kernel has slightly different config:
```
+CONFIG_SECURITY_PATH=y
+CONFIG_SECURITY_WRITABLE_HOOKS=y
+CONFIG_SECURITY_SELINUX_BOOTPARAM=y
+CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE=0
+CONFIG_NET_VENDOR_MARVELL=y
+CONFIG_SKGE=m
```
But in general you're right and most of the LVE functionality is implemented in kernel module.

**Comment by SherifNagy** [comment]
> There's the `shim.cloudlinux,4` entry. As far as I'm aware, it should be `shim.cloudlinux,1` after the bump to `shim,4` unless there are some historical reasons I'm not aware of. Similar to `grub.cloudlinux,2`. I'll ask another reviewer from the committee to check this out as well.

As far as I know, it is not a good idea if you revert / reset the vendor's specific global number generation just in case if they already revoking this, it can be same as their last submission or higher version, worth checking and get more clarification with another reviewer for sure

**Comment by andrewlukoshko** [comment]
@aronowski we're following upstream strategy and bump shim.cloudlinux for every version to make it possible to revoke everything up to specific version. So basically we want to provide as much flexibility as possible.
If we do `shim.cloudlinux,1` now and it will be revoked at some point this will mean that our `shim-15.6` which has `shim.cloudlinux,2` is better and still allowed to boot but it should not because `shim-15.6` has vulnerabilities.

**Comment by julian-klode** [comment]
@aronowski No, the more specific number should not be reset. If you reset it and it later turns out you had to revoke shim.cloudlinux,2 and smaller your newer binaries also end up being revoked

@andrewlukoshko That is wrong as well. You should only bump your own SBAT level if you have a vendor-specific vulnerability. You should not be following the upstream number or anything. If upstream code is affected and needs revoked it will be revoked using the upstream handle.

**Comment by julian-klode** [comment]
To be more clear if you increase shim.cloudlinux or grub.cloudlinux entries the questions we ask are:

- what vulnerabilities have been detected and fixed in this new sbat level
- why you have not submitted the previous levels for revocation

**Comment by jsetje** [comment]
Always incrementing the vendor specific generation gives us more potential options for a finer grained revocation in the future. I don't see why we wouldn't bump it. And yes, this is just in case of a scenario that probably won't happen.

**Comment by andrewlukoshko** [comment]
BTW Red Hat bumped vendor SBAT level for their last submission for RHEL8 https://github.com/rhboot/shim-review/issues/374
```
shim.redhat,3,Red Hat Inc,shim,15.8,secalert@redhat.com
```
It's not mentioned in README for some reason but if you check src.rpm you'll see it.

**Comment by andrewlukoshko** [comment]
Microsoft signed this version.
Submission IDs:
13590580995602435
13770904983953491

Thanks everyone, closing.
