### ISSUE TITLE
Shim 15.8 for Canonical

### ISSUE THREAD

**Issue by kukrimate** [rhboot/shim-review#368]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
[https://github.com/canonical/shim-review/blob/ubuntu-shim-amd64+arm64-20240202](https://github.com/canonical/shim-review/blob/ubuntu-shim-amd64+arm64-20240202)
*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************

    $ sha256sum shim*.efi
    21d895284c1783b4e3d82584bc4aca197204f385f0da2192e2222e501ed9cc1b  shimaa64.efi
    39037872a0bb357a0f40c5e3ce6a1757b5b54c78c31f8d5da01169c2ca94b3a7  shimx64.efi

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
[https://github.com/rhboot/shim-review/issues/298](https://github.com/rhboot/shim-review/issues/298)

**Comment by jsetje** [comment]
The build reproduces for me. The vendor dbx patch seems reasonable.

The generation number all look OK, but we should probably agree on when the vendor specific ones are bumped. Incrementing them for every release could provide us with additional options in the future. (This is not a blocking comment.)

I didn't spot any issues with the rest of the answers.

**Comment by kukrimate** [comment]
@jsetje

Thanks for the review.

Note for reviewers:
- I have been added to the list of security contacts in this release, we also have two other already verified. I'll likely be handling posting shims here for the foreseeable future, so maybe we should the verification dance. (My GPG key fingerprint is in the README and available on keyserver.ubuntu.com)

**Comment by kukrimate** [comment]
Verification words:
```lofts pompoms larboard sol conceptualizes tackled blogs undergone apocryphal arrangement
```

**Comment by kukrimate** [comment]
Also re kernel patches, wording can be changed next time. Point is lockdown bypass fixes are applied and tested by the kernel team, and I assume change are made as appropriate.

I don't maintain kernel code, so can't provide details off the top of my head. But if you concern about specific upstream changes missing I can forward that to the kernel team.

**Comment by xnox** [comment]
Valid questions which in theory should have already had publically traceable documentation (unless i need to chase people up with a yard stick). Can you please request review from me on this PR to comment with details?

**Comment by julian-klode** [comment]
@aronowski Well @xnox is commenting as part of our kernel team, not as a separate entity, I don't think that was clear.

**Comment by jsetje** [comment]
For some reason I thought there had been another reviewer on this already. I'll run through the whole thing now.

**Comment by kukrimate** [comment]
Signed shims received, closing.
