### ISSUE TITLE
Shim 15.8 for TeraByte

### ISSUE THREAD

**Issue by TBOpen** [rhboot/shim-review#369]
Updated Feb 23, 2024:

Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed ) (Note: N/A)
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs - (NOTE: docker file will generate them.)
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
https://github.com/TBOpen/shim-review/releases/tag/TeraByte-Shim15.8-x64-20240310

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
02c4bf81a5f359213d80ec365366d8be35b02bf84e522802c5fc8ee8694c8e05 *shimx64.efi

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
https://github.com/TBOpen/shim-review/releases/tag/TeraByte-Shim15.4-x64-20210510

**Comment by TBOpen** [comment]
Just waiting patiently, while customers disable secure boot on their systems.   FWIW, the latest Gpg4win outlook plugin no longer crashes outlook so it's in place and also added the corp email to the newer openpgp key servers rather than our really old ones on the MIT server.

**Comment by TBOpen** [comment]
I'm not sure how to quote the comment for the comments like you did above, but here are the answers:

#1 - Yes, the one you found TeraByte Corporate <corp@terabyteunlimited.com> is correct, publicly published.

#2 - We are moving to a newer GRUB version (that has all fixes in place) and the new shim won't be able to load the old GRUB.  So I guess "yes", would be the answer.

#3 - It's N/A because we had no bugs in our part of the software being loaded so no need to blacklist it.   I presume the SBAT entries (or NX requirement) will handle it (something is already preventing loading on updated systems).  Or is it even if SHIM itself needs to be updated, we have to provide old hashes to our builds (I thought that was why SBAT was created - to prevent overloading the database).

#4 - We typically only use the new key on updates from say 6.6 to 6.7 but not 6.6.1 to 6.6.2 but we can.

#5 - I just figured if you build the binary and it's the same, that's all that is needed.    Is there an exact process to pull them out of the docker build (do they exist or do we need to pipe the output somehow).  I've seen the updates happen but the binary output is the same.   If you tell me exactly what you want I can get it for you.

#6 - The shim was provided and figured you would want to look what was in there, but I can post here as well (I extracted this from the .efi):
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,4,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.terabyte,1,TeraByte,UEFI shim,2,https://www.terabyteunlimited.com

#7 - I don't recall the prior versions doing that, but I noticed the hash was different on each build and I looked in to it, it was the PE header time/date field (plus what looks like a crc of the header).  Is there a better fedora number to use, it doesn't matter to me as long as it builds okay.   Is Fedora 37 a good one to use?  I'll move to that one if that would be better.

Thank You.

**Comment by TBOpen** [comment]
I just ran a test using Fedora 37 - the nice thing is the binary hash matches each build - this is because the date/time field is 0, whereas the newer compiler in Fedora 38 actually outputs the date/time.  So this board will have to deal with that at some point.  I'll just revert to 37 so that I'm not having to hassle with thing because of being on the bleeding edge. 

So someone just let me know exactly what log I'm supposed to get and how to get it.   I don't see much docker output.  If I rebuild it, you see all the installing of fedora items, if I just build where it just recompiles the shim, there is hardly any output.   But the binary will match.

**Comment by TBOpen** [comment]
Okay, I updated the issue - New link and hash provided in original message.  I also output the the build capture to the same folder the shim is output to.   When you run the docker_make_shim it will overwrite the items in terabyte_shim-15.8_built so you may want to save them away if you want to compare them.   I also put a copy of the shim .efi in the root of the submissions (basically copied out of terabyte_shim-15.8_built).

**Comment by TBOpen** [comment]
The confirmation email can be sent anytime someone is ready...

**Comment by TBOpen** [comment]
Did you get the updated .zip ?

**Comment by TBOpen** [comment]
Are you guys checking in to the policy for SBAT vs adding to DBX ?   Just wondering why the delay, MS said sometimes they are communicating with you guys behind the scenes.

**Comment by TBOpen** [comment]
> Sorry, which .zip file is it about?

I was referring to the the new tag link - which you obviously have.

> Please, update the appropriate section in README.md and ping me once the change is there 

It's updated, new tag: https://github.com/TBOpen/shim-review/releases/tag/TeraByte-Shim15.8-x64-20240310

Thanks.

**Comment by TBOpen** [comment]
Thanks, I don't want to bug anyone, I presume it won't take long for the regulars to check it out ...

**Comment by TBOpen** [comment]
@SherifNagy @vden-irm @dennis-tseng99
It would be much appreciated if someone could provide the extra review?

**Comment by dennis-tseng99** [comment]
Reviewing
### === Review for Shim 15.8 for TeraByte #369 ===

- Binaries are producible based on tag TeraByte-Shim15.8-x64-20240310 (ok)
  shim_build.log file is generated.
- Hash value is matched (ok)
  $ sha256sum shimx64.efi
  02c4bf81a5f359213d80ec365366d8be35b02bf84e522802c5fc8ee8694c8e05  shimx64.efi
- NX flag is disable: (ok)
  $ objdump -x shimx64.efi | grep -E 'SectionAlignment|DllCharacteristics'
  SectionAlignment        00001000
  DllCharacteristics      00000000

- shim sbat (ok)
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,4,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.terabyte,1,TeraByte,UEFI shim,2,https://www.terabyteunlimited.com
  
- There are 2 patches needed to be digged in.
-------------------------------
What patches are being applied and why:
shim-15.8.patch
grub-2.12-tbu.patch
--------------------------------

- Certificate Validity: (ok)
openssl x509 -in shim.cer -inform der -noout -text        
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0d:75:dc:e4:ee:cc:7f:f3:23:a2:50:d0:ee:42:f7:ed:e6:58:33:3c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = TeraByte UEFI SB 2024, O = Terabyte Inc, L = Las Vegas, ST = Nevada, C = US
        Validity
            Not Before: Feb  3 00:55:05 2024 GMT
            Not After : Jan 31 00:55:05 2034 GMT
        Subject: CN = TeraByte UEFI SB 2024, O = Terabyte Inc, L = Las Vegas, ST = Nevada, C = US
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)

shim.cer is DER format:
/shim-review-TeraByte-Shim15.8-x64-20240310/cert> hexdump shim.cer
0000000 8230 b303 8230 9b02 03a0 0102 0202 0d14
0000010 dc75 eee4 7fcc 23f3 50a2 eed0 f742 e6ed
0000020 3358 303c 060d 2a09 4886 f786 010d 0b01
0000030 0005 6930 1e31 1c30 0306 0455 0c03 5415
0000040 7265 4261 7479 2065 4555 4946 5320 2042
........

ASN.1 Tree is something like this:
30 82 03 b3
----30 82 02 9b
--------a0 03 
------------02 01 02
--------02 14 0d 75 dc e4 ee cc 7f f3 23 a2 50 d0 ee 42 f7 ed e6 58 33 3c

10 years is good. However, NIST deems Certificate RSA 2048 sufficient until 2030, but your last date of the validity is 2034. Suggest you use 4096 bits next time.

- Suggestion:
For the next submission, please specify more details about the contact information for your product when you specify vendor_url field, or just use email instead. For example, you might change to:
shim.terabyte,1,TeraByte,UEFI shim,2,https://www.terabyteunlimited.com/packages/shim
 
- Still digging into your patch files. Any expert's help is welcome.

**Comment by TBOpen** [comment]
Thanks.

grub patch is already mainstream to be in next Debian grub 2.12-2 (and grub 2.12 itself) (except of course the title).

shim patch disables fallback, we don't need it or want it, works around compiler warning treated as error issues, and allows providing second stage filename in shim.dat file instead of hard coded or parameter in uefi boot item because that is how we do it.

**Comment by dennis-tseng99** [comment]
Understood. Let's accept it.

**Comment by TBOpen** [comment]
Thanks!

**Comment by TBOpen** [comment]
Completed.
