### ISSUE TITLE
Cisco SHIM-14-x86_64-20181024

### ISSUE THREAD

**Issue by dosman0** [rhboot/shim-review#37]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/cisco/sto-uefi-secure-bootloader/tree/cisco-shim-x86_64-20181024/shim-review
 - [x] completed README.md file with the necessary information
https://github.com/cisco/sto-uefi-secure-bootloader/blob/cisco-shim-x86_64-20181024/shim-review/README.md
 - [x] shim.efi to be signed
https://github.com/cisco/sto-uefi-secure-bootloader/blob/cisco-shim-x86_64-20181024/shim-review/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/cisco/sto-uefi-secure-bootloader/blob/cisco-shim-x86_64-20181024/shim-review/cisco_virtual_root.der
 - [x] any extra patches to shim via your own git tree or as files
n/a
 - [x] any extra patches to grub via your own git tree or as files
n/a
 - [x] build logs
https://github.com/cisco/sto-uefi-secure-bootloader/blob/cisco-shim-x86_64-20181024/shim-review/build.log

###### Sysdev Submission ID:
UEFI File Submission ID:  14403955457868706

###### What organization or people are asking to have this signed:
Cisco Systems
IANA Enterprise Number 9

###### What product or service is this for:
Cisco Appliances and Virtual products that are using Linux based Operating Systems

###### What is the origin and full version number of your shim?
https://github.com/rhboot/shim/releases/tag/14

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Customers using Cisco Virtual products that run on 3rd party servers (DELL, HP...) do not have permissions to change the UEFI db and add our keys.  The Microsoft signed SHIM allows these products to securely run on those platforms

###### How do you manage and protect the keys used in your SHIM?
Stored offline via a dedicated group within Cisco

###### Do you use EV certificates as embedded certificates in the SHIM?
yes

###### What is the origin and full version number of your bootloader (GRUB or other)?
GRUB2 shipping with CentOS 7, and Ubuntu

###### If your SHIM launches any other components, please provide further details on what is launched
n/a

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
no

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Standard kernels from CentOS 7 and Ubuntu. Secure boot support flags enabled during builds

###### What changes were made since your SHIM was last signed?
resubmit of the initial attempt. Only internal DevOps have changed to make the build more reproducible.

###### What is the hash of your final SHIM binary?
8cb61fc8da9f37aa1a05f153208f781ee791bac2a7a7c4a24b14d1e54f449d61 shimx64.efi

**Comment by dosman0** [comment]
Hi, do you have all the info needed to approve this submission??

**Comment by cyphermox** [comment]
Yes, got all I need.

`Step 17/29 : RUN sha256sum /shimx64.efi
 ---> Running in f7b885f76d5f
8cb61fc8da9f37aa1a05f153208f781ee791bac2a7a7c4a24b14d1e54f449d61  /shimx64.efi`

Rebuild test is done; binaries rebuild fine with the expected differences in build ident and what looks like the relocation table.

**Comment by dosman0** [comment]
Cool!  Does that mean you accept the submission??  Who notifies MS?

**Comment by cyphermox** [comment]
Yes, this one is approved.

You will want to contact MS yourself to have your submission reviewed there at sysdev.
