### ISSUE TITLE
shim 15.8 for SUSE Enterprise Linux

### ISSUE THREAD

**Issue by jsegitz** [rhboot/shim-review#393]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
`https://github.com/jsegitz/shim-review/tree/SUSE-SLES-shim-x86_aarch64-20240229`

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
x86_64:
pesign: f327bfe0e31193974df9fa68b621a2c87d154ef2986059ce16fc6d0bd7537a96 shim-sles.efi
sha256sum: bf24a19e3bd5ca535b0815be9e49b36b835a9f36310ed5b3e5f87959a52b87e2  shim-sles.efi

aarch64:
pesign: 8bfe4fc6a7506d82a4efdd39ecac04ef0ab6f65d9ac3514d803462a7b4ae7fcf shim-sles.efi
sha256sum: 5f3c747130027da84c47256a6d089b6cb1c923a3517d31c8703e360c9f2832c6  shim-sles.efi

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
https://github.com/rhboot/shim-review/issues/301

**Comment by jsegitz** [comment]
Updated the tag to indicted the current SLES service pack (SP5 instead of SP4)

**Comment by MuthuvelKuppusamy** [comment]
Not able to reproduce the build,

![image](https://github.com/rhboot/shim-review/assets/79298793/83aa889b-8b2d-472e-a9b8-f8dd81c7e167)

**Comment by jsegitz** [comment]
seems like the architecture variable is not set (line 206 in the README.md). Please try
`podman build --build-arg ARCHITECTURE=x86_64 -t sles_shim:15.8 .`

**Comment by jsegitz** [comment]
Thank you for the review. The shim binary is the one from our build service, not of the local (or container build). That was my error, sorry. The pesign hash has been fine, but the sha256sum not. I uploaded the proper shim binary in https://github.com/jsegitz/shim-review/commit/8519f8d1e237eec3ff7c233942480c9d9806ecb1 and updated the tag

**Comment by jsegitz** [comment]
Ephemeral keys: We work with vendors to make their kernel modules work on our operating system. Recompiling every module for every new kernel would be problematic for us. I'll raise this with our kernel team, but even if it's possible (and I'm not so sure about this) it would need quite some time.

SBAT entries email: These addresses are reaching the same team, but I'll see that we unify this. Thanks for the note

**Comment by jsetje** [comment]
I'm not spotting any remaining issues here.

**Comment by jsegitz** [comment]
thank you very much for the review!
