### ISSUE TITLE
shim 15.8 for CentOS Stream 9 

### ISSUE THREAD

**Issue by bstinsonmhk** [rhboot/shim-review#399]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
`https://github.com/CentOS/shim-review/commit/bf46854b217e5960a10d3da609106cea1aea8f44`

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
af59c32ed630729ad36261b2e6d0ea0170c9f220ade2c961fb333601e9f3f389

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
https://github.com/rhboot/shim-review/issues/65

**Comment by SherifNagy** [comment]
Sending contact verification email to @bstinsonmhk

**Comment by bstinsonmhk** [comment]
Verification Response: 
AB7Uur6U bohdi4Fu PaeM5eo6 echai5AM Faegie9a

**Comment by SherifNagy** [comment]
I just need a clarification about the grub2 sbat entries, you mention your source is exactly as rhel however you are using grub2.rh for older release of grub2. 

As far as I understand centos stream is the upstream for RHEL, and I know that some pushes comes from RHEL into centostream, so it make sense keeping grub2.rh but also I think you need to have grub2.centos in there, to be honest, I need another opinion here I will tag @vathpela @steve-mcintyre for input

**Comment by steve-mcintyre** [comment]
@bstinsonmhk any response to @SherifNagy's question please?

**Comment by steve-mcintyre** [comment]
No responses to questions and pings, closing.

Please re-open if you come back to this.
