### ISSUE TITLE
 2017-10-24 Filewave

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#4]
Date: Fri, 24 Nov 2017 14:50:01 +0100
From: Marcin Wcislo
Subject: [Shim-review] Shim review request (FileWave, submission ID: 1972187)

Hi,

We decided to switch embedded certificate in our shim and because of that we need another review from you. All required information and
files (as described in the review procedure) can be found here: https://github.com/fw-dev/shim-review
<https://github.com/fw-dev/shim-review>. This submission is almost exactly the same as the previous one with one exception, this time we
didn’t embed public key certificate of our self-signed CA but we used public key certificate of our Extended Validation certificate
acquired from Symantec. Everything else (code, build platform, packages, grub, kernel, test procedures) is exactly the same. I hope that
it can help with having this submission reviewed swiftly. If you have any more questions, please let me now.

Our first submission was handled in subject: Shim review request (FileWave, submission ID: 1956769).

Best regards, Marcin

**Comment by cyphermox** [comment]
@vathpela You already responded by email that this one is fine for signing, should it be closed ?

**Comment by marcinwfilewave** [comment]
I just noticed that review process moved to this repository (from mailing list). We already had our shim accepted by you and signed by Microsoft. This issue can be closed. Thank you.

**Comment by cyphermox** [comment]
Closing, this was accepted on the ML.
