### ISSUE TITLE
shim-15.8 for CentOS Stream 8 

### ISSUE THREAD

**Issue by bstinsonmhk** [rhboot/shim-review#400]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
`https://github.com/CentOS/shim-review/commit/4c3f4a82bc70abd56737f2c023cf6ab59120381b`

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
478f378b1ffa1bdea33d623cc969bd3abb1214605c4c91a01942f343dfa03a19

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
https://github.com/rhboot/shim-review/issues/65

**Comment by msmeissn** [comment]
The readme.md seems not up to date with the template. the section with ephemeral keys is missing at least.

**Comment by steve-mcintyre** [comment]
@bstinsonmhk Could you please update your submission to match the most recent template please?

**Comment by steve-mcintyre** [comment]
No responses to questions in several months, closing

**Comment by AlexBaranowski** [comment]
@steve-mcintyre -> They EOLed about 10 days ago :) https://www.centos.org/cl-vs-cs/ so 👍🏻
