### ISSUE TITLE
shim 15.8 for Policorp Linux

### ISSUE THREAD

**Issue by policorp-dev** [rhboot/shim-review#405]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
https://github.com/policorp-dev/shim-review/tree/policorptecnologia-shim-x64-20240327

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
677f300cc3c019d0909af41229309d0016f62e962df534781a83560ca5e352ae shimx64.efi

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
N/A

**Comment by es-fabricemarie** [comment]
I'm not an official reviewer, but I just want to help reduce the work load of official reviewers.

- shim-review source repo is a branch not a tag (should be ok though)
    - this mini review is for branch `policorptecnologia-shim-x64-20240327`, on commit point `547786a9bdc788cae2e8dfe3aa39675bd0382128`
- dockerfile pulls from official shim git repo directly, branch 15.8:
    ```
    git clone --recursive -b 15.8 https://github.com/rhboot/shim.git
    ```
- build is reproducible
- shim shasum matches: `4aa025926083ae419fa8faa002a257c47603c674509616d6275d7e3922cafbc7  shimx64.efi`
- certificate:
    - valid for 20 years, 2048 bit RSA
    - self signed CA issued to `C = BR, ST = Amazonas, L = Manaus, O = Policorp Tecnologia Ltda., CN = Secure Boot Signing, emailAddress = contato@policorp.com.br`
    - At the question `Do you use EV certificates as embedded certificates in the SHIM?` you replied yes, when in fact the certificate above is self-signed.
- shim sbat section does not add a vendor specific line at the end of it:
    ```
    objcopy -j .sbat -O binary shimx64.efi /dev/stdout
    ```

    ```
    sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
    shim,4,UEFI shim,shim,1,https://github.com/rhboot/shim
    ```
- grub sbat is also the default debian grub sbat section (as per claim for submiter) without vendor speciic line.
- NX compat is disabled
    ````
    objdump -p review/shimx64.efi  | grep DllCharacteristics
    ````
    
    ````
    DllCharacteristics      00000000
    ````
- signing keys: are they stored in software or do you use an HSM/CloudHSM?

**Comment by policorp-dev** [comment]
Thanks for your comment, about the signing keys, yes they are stored on software, according to your comment we gonna change our repo.

**Comment by policorp-dev** [comment]
Thanks for your rewiew, i would like to provide some corrections and clarifications regarding some issues raised recently:

**Addition of Public Key** A public key generated in .PEM format was added.

**Contact Email Update** The contact email has been modified to direct to the person responsible for managing our system's subscription process. This change will ensure more effective and direct communication regarding this critical aspect of our project.

**Key Management Method** There was a misunderstanding on our part regarding the key management method. We do not use software for this purpose; instead, we rely on a USB Token exclusively designated for this purpose. Furthermore, we have a machine dedicated exclusively to this functionality. Only authorized personnel have access to these devices, thus ensuring adequate security and control.

**Correction regarding GRUB2 Global SBAT** Regarding the answer related to GRUB2 Global SBAT, there was a typo. The standard we follow is that of Debian, and not the one mentioned previously.
GRUB2 Modules Loaded on Our System: There was a mistake regarding the modules loaded on our system. The above information was obtained from a discontinued version of our system. We currently use the modules loaded by default in the Debian Bookworm version

**Comment by policorp-dev** [comment]
Thanks for the answer.

We already updated, adding our PGP keys in two separate files **.pub**, the keyserver link is on Readme.md

**Comment by policorp-dev** [comment]
Thanks for the answer

We changed our  **.pub** files, now our keys are 4096 bit key and we prolong the validate date

**Comment by Fabian-Gruenbichler** [comment]
> * The other one is valid only for a year, therefore the verification process will need to be repeated most likely when a new shim version comes out. Is this the intended process?

just chiming in from the side-lines here: having a short expiration date is actually a good thing! it means that if you lose access to the key *and the revocation certificate* (which should not happen, but you never know), it will become unusable on its own. extending the expiration date is easily done, and *does not require revalidating the key* and doesn't change its fingerprint (it does require access to the key that signed it). of course, you do have to remember to both extend the key and published the extended version, else other people won't be able to contact you.

**Comment by steve-mcintyre** [comment]
Contact verification emails sent - please respond here as instructed.

**Comment by policorp-dev** [comment]
Thanks for the answer.

**Message for our primary contact(Lucas Adriano Salles)**: coiffure Ionics riced extemporized engravings keenly Della styling dotage.

**Message for our second contact(Luiz Henrique da Silva de Oliveira)**: confrontations software Wiley shadowiest cannot Marylou stinger safaris starling waterline

**Comment by steve-mcintyre** [comment]
Contacts verified OK

**Comment by dennis-tseng99** [comment]
### === Review for Shim 15.8 for Policorp Linux #405 ===

- Binaries are producible by running "docker build ." (Ok)
- hash value is matched
- NX is disabled (Ok)
/efi-boot-shim# objdump -x shimx64.efi | grep -E 'SectionAlignment|DllCharacteristics'
SectionAlignment        00001000
DllCharacteristics      00000000

- sbat seems ok

```
objcopy --only-section .sbat -O binary shimx64.efi /dev/stdout
sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
shim,4,UEFI shim,shim,1,https://github.com/rhboot/shim
shim.policorp,1,Policorp Tecnologia,shim,15.8,contato@policorp.com.br

bat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
grub,4,Free Software Foundation,grub,2.06,https://www.gnu.org/software/grub/
grub.debian,4,Debian,grub2,2.06-13,https://tracker.debian.org/pkg/grub2
```

- use ephemeral key (good)

- Certificate Validity (?) : 20 years + 2048 bits + EKU codesign
openssl x509 -in policorp.der -inform der -noout -text

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            05:3f:35:68:a5:79:45:73:1a:a3:aa:17:b1:b2:0f:72:83:61:f3:6d
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = BR, ST = Amazonas, L = Manaus, O = Policorp Tecnologia Ltda., CN = Secure Boot Signing, emailAddress = contato@policorp.com.br
        Validity
            Not Before: Aug 23 15:24:22 2023 GMT
            Not After : Aug 18 15:24:22 2043 GMT
        Subject: C = BR, ST = Amazonas, L = Manaus, O = Policorp Tecnologia Ltda., CN = Secure Boot Signing, emailAddress = contato@policorp.com.br
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
        ...........
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                90:86:68:CE:7B:1A:DE:11:67:90:19:41:CA:42:A1:13:ED:92:44:5C
            X509v3 Authority Key Identifier: 
                keyid:90:86:68:CE:7B:1A:DE:11:67:90:19:41:CA:42:A1:13:ED:92:44:5C

            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Extended Key Usage: 
                Code Signing, 1.3.6.1.4.1.311.10.3.6, 1.3.6.1.4.1.2312.16.1.2
            Netscape Comment: 
            .............
```

- Question about your last validity year 2043. Because NIST deems RSA 2048 sufficient until 2030, that is to say 2048 bit keys will be valid up to about the year 2030.
May I suggest you change the last year to 2030 next time ? Otherwise any code you sign with a 2048 bit key today will have to be re-signed with a longer key in the year 2029.

- conclusion:
This task has been reviewed by many experts, like @steve-mcintyre and @aronowski.
Contact verification is ok. 
The global generation number of sbat of grub has been fixed.
The RSA public key length has been changed from 1024 to 2048 bits, but the last validity year is dangerous. Hope to change that minor error next time.
It seems everything is fine. Accepting.

**Comment by policorp-dev** [comment]
Thanks for the review, we have a question, when we go to Microsoft's file subscription service, they ask for a .cab file, what should this .cab contain? We got stuck on that part.

**Comment by es-fabricemarie** [comment]
@policorp-dev and you should sign your cab file with your corporate EV certificate to certify it comes from you.
Requirements/docs are here: https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/file-signing-reqs

**Comment by THS-on** [comment]
@policorp-dev did you get a signed shim back?

**Comment by THS-on** [comment]
Closing as there was no response over a month
