### ISSUE TITLE
CPSD-shim-15-x86_64-20181114

### ISSUE THREAD

**Issue by chscf** [rhboot/shim-review#41]
Make sure you have provided the following information:

 - [X] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 - [X] completed README.md file with the necessary information
 - [X] shim.efi to be signed
 - [X] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [X] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [X] build logs

https://github.com/chscf/shim-review/tree/CPSD-shim-x86_64-20181114

###### What organization or people are asking to have this signed:
The company is called cpsd (https://www.cpsd.at/), located in Austria. We're working in the field of IT security, with our main focus on full disk encryption.

###### What product or service is this for:
The pre-boot authentication environment for our company's Full Disk Encryption CryptoPro Secure Disk (see https://www.cpsd.at/)

###### What is the origin and full version number of your shim?
shim-15

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Because we want the whole world to use our product ;)

###### How do you manage and protect the keys used in your SHIM?
The private key is on a FIPS 140-2 token.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes

###### What is the origin and full version number of your bootloader (GRUB or other)?
see below

###### If your SHIM launches any other components, please provide further details on what is launched
shim loads a self-developed boot component which does all further authorization/os loading stuff.

###### How do the launched components prevent execution of unauthenticated code?
Our boot component does not load any unsigned binaries.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
N/A

###### What changes were made since your SHIM was last signed?
Upgraded from shim-0.8 to shim-15

###### What is the hash of your final SHIM binary?
44ed00a46d11e631f334f8cfc3747b02b53e0e48b89e9641a0e4a1775f3121e1  shim-15-SCF-unsigned.efi

**Comment by cyphermox** [comment]
Some of the questions above are not fully developped. Why do you need *shim* signed, rather than having Microsoft sign your own bootloader?

We typically only sign shims when developped in order to chainload grub, for Linux distributions. Without being able to review the next stage bootloader, I'm not in a position to be able to tell whether or not the next stage is secure, and will in fact refuse to load unsigned binaries.

**Comment by cyphermox** [comment]
I don't know about the policies Microsoft uses for signing; but using this shim should not be a shortcut to avoid having proper review of UEFI applications. Without reviewing the applications we can't know for sure that they don't load unauthenticated code.

Can you please bring this up with Microsoft? Maybe there's a misunderstanding somewhere?

**Comment by julian-klode** [comment]
Closing this review requests as it is from before 2019, and likely not valid anymore. Also note that we just added some new questions, and if you submit a new review request with the current question set, also include a Dockerfile to build the shim to not slow down review.
