### ISSUE TITLE
shim 15.8 for Oracle Solaris 11.4

### ISSUE THREAD

**Issue by daveminer1** [rhboot/shim-review#447]
Confirm the following are included in your repo, checking each box:

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate(s) embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] binaries, for which hashes are added to vendor_db ( if you use vendor_db and have hashes allow-listed )
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
 - [x] a Dockerfile to reproduce the build of the provided shim EFI binaries

*******************************************************************************
### What is the link to your tag in a repo cloned from rhboot/shim-review?
*******************************************************************************
`https://github.com/daveminer1/shim-review/tree/oraclesolaris-shim-x86_64-20241010`

*******************************************************************************
### What is the SHA256 hash of your final SHIM binary?
*******************************************************************************
b098fb90bff86509aacff0e5bc197583e7e77968cc64da4d41d310fb4eab3087  shimx64.efi

*******************************************************************************
### What is the link to your previous shim review request (if any, otherwise N/A)?
*******************************************************************************
N/A

*******************************************************************************
### If no security contacts have changed since verification, what is the link to your request, where they've been verified (if any, otherwise N/A)?
*******************************************************************************
N/A

**Comment by es-fabricemarie** [comment]
- build reproduces fine with dockerfile and `docker build .`
    ```
    b098fb90bff86509aacff0e5bc197583e7e77968cc64da4d41d310fb4eab3087  /usr/share/shim/15.8-1.0.3.el9/x64/shimx64.efi
    ```
- shim built from 15.8 official tarball, unpatched
- NX bit is not set
- SBAT entries look alright
- OpenPGP keys:
    - Alan Coopersmith's key found on Ubuntu OpenPGP key server:
        - `https://keyserver.ubuntu.com/pks/lookup?search=4A193C06D35E7C670FA4EF0BA2FB9E081F2D130E&fingerprint=on&op=index`
        - expires: 2028-04-19, key is cross-signed
    - Dave Miner's key not found on Ubuntu/MIT OpenPGP key servers, no key expiry. Key is cross-signed.
- EV Code Signing cert used:
    - RSA 3072 bit
    - `Issuer: C=US, O=DigiCert, Inc., CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1`
    - `Subject: jurisdictionC=US, jurisdictionST=Delaware, businessCategory=Private Organization, serialNumber=2101822, C=US, ST=California, L=Redwood City, O=Oracle America, Inc., CN=Oracle America, Inc.`
    - Expires in April next year: `Not After : Apr  2 23:59:59 2025 GMT`

Issues:
- `DISABLE_EBS_PROTECTION` is set so official reviewer will have to take a deeper look.
- grub2 is patched (build glue and zfs among others). More scrutiny by core team member is advised.

**Comment by jsetje** [comment]
Since I work for the same company as the submitters, I don't count as a reviewer in this case. However, I looked this over in some detail before it was submitted.

DISABLE_EBS_PROTECTION is expected,  since with the custom ELF validation code nothing will call back into shim lock protocol to have shim validate anything additional.

**Comment by daveminer1** [comment]
My key is present on pgp.mit.edu:

Search results for 'oracle miner dave com'

Type bits/keyID     Date       User ID

pub   256E/[8C450938](https://pgp.mit.edu/pks/lookup?op=get&search=0x1DDC7D078C450938) 2024-07-23 [Dave Miner <dave.miner@oracle.com>](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x1DDC7D078C450938)

**Comment by daveminer1** [comment]
Confirming identity

leaders drearier picker sequins oatmeal torrential Portsmouth revert Lindsay strait

**Comment by alanc** [comment]
> Mail sent to @daveminer1 for verification.
> 
> Alan's key is an ancient 1024-bit DSA key. We can't use that - it's way past time he generated something newer that's less readily broken.

Is not the RSA4096 key shown on https://keyserver.ubuntu.com/pks/lookup?search=0xCFDF148828C642A7&fingerprint=on&op=index sufficient?

**Comment by jsetje** [comment]
The old DSA one shows up first, presumably because it's your oldest key endorsing the others? I don't think we should use it anymore, but removing it from the server doesn't seem right either.

**Comment by julian-klode** [comment]
> > Mail sent to @daveminer1 for verification.
> > Alan's key is an ancient 1024-bit DSA key. We can't use that - it's way past time he generated something newer that's less readily broken.
> 
> Is not the RSA4096 key shown on https://keyserver.ubuntu.com/pks/lookup?search=0xCFDF148828C642A7&fingerprint=on&op=index sufficient?

That is a subkey of a dsa1024 key, and as such the binding signature (the signature the primary key makes to certify the subkey as bound to it) is not strong enough, you need to properly rotate to a strong primary key.

As the primary key is the root of trust, when someone goes fetch the key it will fetch and trust all it's subkeys and encrypt to the latest encryption subkey.

An attacker with enough compute could be able to fake signatures binding arbitrary new suvkeys to the primary keys as dsa1024 is particularly weak.

**Comment by steve-mcintyre** [comment]
@julian-klode has described this exactly - just adding new stronger subkeys isn't sufficient

**Comment by alanc** [comment]
Sorry, I thought what I had done years ago was doing that, but I guess I did not. Unfortunately that description, no matter how exact, does not help me understand what I need to do now to satisfy you while not breaking the verification of the hundreds of X.Org package releases I've signed with that key which distros use to verify.  Can you point to instructions for what gpg commands you want me to use here?

**Comment by steve-mcintyre** [comment]
Hi Alan!

No worries! You don't have to kill the old key, you can just create another new key for this new purpose.

The guide we typically point people to in the Debian community is https://keyring.debian.org/creating-key.html ; the defaults in gpg tend to be reasonable out of the box these days, but it dosn't hurt to check things look sane.

**Comment by daveminer1** [comment]
Alan has generated a new key, the review is updated with the new fingerprint and updated pub files for both

**Comment by steve-mcintyre** [comment]
Mail to Alan on the way now

**Comment by alanc** [comment]
Confirming my identity:

primitive epigram tablelands raking drubs reactive teakettle layettes hoppers extrinsic

**Comment by lorddoskias** [comment]
Review

- [x] Build reproduces: 
    `b098fb90bff86509aacff0e5bc197583e7e77968cc64da4d41d310fb4eab3087  /shimx64.efi`

- [x] HSM is used to store the key
- [x] SBAT entries ok
- [x] Shim is built from the provided srpm, which includes the upstream 15.8 as verified by the sha256 csum: 
  ```
     fisk:~/projects/shim-review/oracle/src$ sha256sum shim-15.8.tar.bz2 
         a79f0a9b89f3681ab384865b1a46ab3f79d88b11b4ca59aa040ab03fffae80a9  shim-15.8.tar.bz2
  ```
  

- [x] SBAT looks ok: 
 ```
#23 0.185 sbat,1,SBAT Version,sbat,1,https://github.com/rhboot/shim/blob/main/SBAT.md
#23 0.185 shim,4,UEFI shim,shim,1,https://github.com/rhboot/shim
#23 0.185 shim.solaris11,3,UEFI shim,shim,15.8,mail:secalert_us@oracle.com
```

- [x] Certificate is OK

**Comment by daveminer1** [comment]
Thanks for the questions, Steve:

- We could use 1 as the generation; I was aligning it with the OL generation number initially since we are aligning with/reusing their build and intend to stay that way but there's really no reason we need to do this.
- `iorw `and `memrw` certainly aren't needed, that list was initially carried over from our 1.99 build and I hadn't considered them.  They'll be dropped.
- Yes, Secure Boot in firmware does enforce use of Verified Boot.  In contrib/vboot/verify.c, the verify_get_boot_policy() function reads the EFI variable and forces the policy to VERIFY_ENFORCE if enabled.  The policy is then enforced in verify_module() which is called from the verifier that's in verfy_efi.c.

**Comment by steve-mcintyre** [comment]
> Thanks for the questions, Steve:
> 
>     * We could use 1 as the generation; I was aligning it with the OL generation number initially since we are aligning with/reusing their build and intend to stay that way but there's really no reason we need to do this.

It's fair enough to keep the same generation, and it makse sense  - just mentioning the reasoning here would not hurt. :-)

>     * `iorw `and `memrw` certainly aren't needed, that list was initially carried over from our 1.99 build and I hadn't considered them.  They'll be dropped.

OK. Please do. Have you signed any GRUB builds including those modules, at this point?

>     * Yes, Secure Boot in firmware does enforce use of Verified Boot.  In contrib/vboot/verify.c, the verify_get_boot_policy() function reads the EFI variable and forces the policy to VERIFY_ENFORCE if enabled.  The policy is then enforced in verify_module() which is called from the verifier that's in verfy_efi.c.

Cool, thanks for clariFying.

**Comment by daveminer1** [comment]
> OK. Please do. Have you signed any GRUB builds including those modules, at this point?

GRUB 2.12 isn't yet in our release so we haven't yet signed any builds with those modules.

**Comment by steve-mcintyre** [comment]
> > OK. Please do. Have you signed any GRUB builds including those modules, at this point?
> 
> GRUB 2.12 isn't yet in our release so we haven't yet signed any builds with those modules.

Good, that makes life much easier then!

**Comment by steve-mcintyre** [comment]
## Follow-up: grub patches

Sorry this has taken quite a while - there's a lot of changes here, and more of a diff than most of the (semi-)common Linux distro patches.

- Lots of patches to configuration to build on Solaris - obvious
- Surprised to see "Disable 30_uefi-firmware", but hey - it's your platform.
- A few generic-looking patches - please send them upstream for discussion?
  - 0012-read.c.patch
    - add non-blocking read. What for, OOI?
  - 0014-zfs.c.patch
    - generic-looking improvements to ZFS support
  - 0015-zfsinfo.c.patch
    - similar?
  - 0023-msdos_partition.h.patch
  - 0037-efi_init.c.patch (and related)
    - adding smbios support
  - 0040-view.c.patch
- Quite a few patches that look like bugfixes, definitely send upstream!
  - 0018-hostdisk.c.patch
  - 0019-pxe.c.patch
  - 0020-sun-hostdisk.c.patch
- Disabling some warnings :-(
  - 0010-cat.c.patch
  - 0031-menu_text.c.patch
- zvmm / vboot etc. - the meat of the changes here
  - yay ELF bnary and certificate parsing :-(
  - contrib/vboot/verify*
    - ASN.1 :-(
    - wouldn't it make more sense to use the in-built libgcrypt code
      for crypto/signing etc.?
    - I can see mentions of - added shims and emulation in
      `grub-core/lib/libgcrypt_vboot` ?

While it would be nice to see a lot of this code pushed into upstream GRUB, I'm clearly not going to block this review on that.

**Comment by steve-mcintyre** [comment]
Questions answered OK I think - thanks!

**Comment by steve-mcintyre** [comment]
While there's a lot of changes to GRUB here, nothing stands out and worries me. Accepting!

**Comment by daveminer1** [comment]
Steve, thanks for all the time you put in on this, we know it was a lot to digest.  To answer a couple of your GRUB questions:

> 0012-read.c.patch
>    add non-blocking read. What for, OOI?

We mainly have this so we can use a well-timed keypress to turn on debug during network boot, as we have some fairly complex scripting to locate the right grub.cfg for a client.

> contrib/vboot/verify*
>   wouldn't it make more sense to use the in-built libgcrypt code
>    for crypto/signing etc.?
>    I can see mentions of - added shims and emulation in
>    grub-core/lib/libgcrypt_vboot ?

Yes, I think there's some cleanup to be done, we've lost some history/knowledge there.

I do hope to upstream a lot of the patches now that they're cleanly separated again, which wasn't the case with our prior GRUB version.  We intend to stay current going forward!

**Comment by daveminer1** [comment]
Microsoft submission id 14244042660000973.  Binary signed, closing.
