### ISSUE TITLE
shim-15 for CentOS 7.6.1810 - version 2

### ISSUE THREAD

**Issue by arrfab** [rhboot/shim-review#45]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

###### What organization or people are asking to have this signed:
`Red Hat, Inc.`

###### What product or service is this for:
`CentOS Linux 7.6.1810`

###### What is the origin and full version number of your shim?
`shim 15`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`CentOS Linux is deployed on a high number of nodes already using it in SecureBoot mode enabled`

###### How do you manage and protect the keys used in your SHIM?
`Can't discuss this publicly, but hardware HSM is used`

###### Do you use EV certificates as embedded certificates in the SHIM?
`no`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`grub2 rebuilt from upstream RHEL 7.6 tree, so https://git.centos.org/commit/rpms!grub2.git/28f7f8f0658e20412cba7a6af37539b1e1f567b2`

###### If your SHIM launches any other components, please provide further details on what is launched
`nothing else than grub2 and then kernel`

###### How do the launched components prevent execution of unauthenticated code?
`Our CI test shows that trying to boot an unsigned kernel isn't working, while a correct pesigned one works`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`NO`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`official RHEL 7.6 rebuild kernel.src.rpm`

###### What changes were made since your SHIM was last signed?
`new release, so bumped from shim v12 to shim v15`

**Comment by arrfab** [comment]
@vathpela not willing to harass you, but any ETA on when this can be reviewed and submitted ? More people are asking for that either through the reported bug tracker or irc.
Thanks :-)

**Comment by cyphermox** [comment]
Ok; reviewing this today. Sorry I couldn't get to it sooner.

**Comment by cyphermox** [comment]
I think your shim-review tree has some issues. It's missing the 0002-MokListRT-Fatal.patch; but is it possible the shimx64.efi file there is also not the right one? I can't succesfully rebuilt the binary and get a close enough result to approve for signing.

**Comment by arrfab** [comment]
Ouch, sorry :-(
It was applied in our buildsystem (and also that can be seen in the root.log and build.log) and then copied in that git branch, but while I modified (and tested) that it worked, I forgot to "git add" the patch itself ... Now done . sorry

**Comment by arrfab** [comment]
https://github.com/CentOS/shim-review/blob/7.6.1810-2/0002-MokListRT-Fatal.patch is now there.
I also confirm that the shimx64.efi (sha256sum 47391a4b25918b7f414420d8f651e302b287a96e0747019d76f705fbf361974e) is the correct one that was built with that patch and also the one tested by other people (see the centos bug report)

**Comment by justinclift** [comment]
@arrfab If there's an updated <whatever> that needs testing, let me know. :smile:

**Comment by cyphermox** [comment]
I try rebuilds with a slightly modified version of the Dockerfile, so as to be able to directly compare the shimx64.efi binary you provide with the one that gets built:

```
FROM docker.io/centos@sha256:b67d21dfe609ddacf404589e04631d90a342921e81c40aeaf3391f6717fa5322
  
COPY shimx64.efi /
COPY centos-7.6.1810-shim-build-deps.repo /etc/yum.repos.d/
RUN yum update -y
RUN yum install -y gcc gnu-efi gnu-efi-devel make redhat-rpm-config-9.1.0-80.el7 rpm-build yum-utils wget
RUN mkdir -p /build/builddir/{SPECS,SOURCES}
COPY shim.spec /build/builddir/SPECS/
RUN yum-builddep -y /build/builddir/SPECS/shim.spec
COPY rpmmacros /root/.rpmmacros
COPY centos.esl /build/builddir/SOURCES/
COPY 0001-Add-vendor-esl.patch /build/builddir/SOURCES/
COPY 0002-MokListRT-Fatal.patch /build/builddir/SOURCES/
COPY shim-find-debuginfo.sh /build/builddir/SOURCES/shim-find-debuginfo.sh
WORKDIR /build
RUN wget https://github.com/rhboot/shim/releases/download/15/shim-15.tar.bz2 -O /build/builddir/SOURCES/shim-15.tar.bz2
RUN rpmbuild -ba --define 'dist .el7.centos' /build/builddir/SPECS/shim.spec --noclean
RUN sha256sum /build/builddir/BUILDROOT/shim-15-2.el7.centos.x86_64/usr/share/shim/x64-15-2.el7.centos/shimx64.efi
RUN hexdump -Cv /build/builddir/BUILDROOT/shim-15-2.el7.centos.x86_64/usr/share/shim/x64-15-2.el7.centos/shimx64.efi > /built.hex
RUN hexdump -Cv /shimx64.efi > /orig.hex
RUN diff -u /orig.hex /built.hex || true
RUN objdump -x /shimx64.efi | head -n 60
RUN objdump -x /build/builddir/BUILDROOT/shim-15-2.el7.centos.x86_64/usr/share/shim/x64-15-2.el7.centos/shimx64.efi | head -n 60
```
I can't get the binaries to match; there's a large number of changes possibly due to how the relocation table is being built, and some parts appear to be OpenSSL code. Do you get similar results when using the Dockerfile? https://paste.ubuntu.com/p/vmF7h8gxZ4/

**Comment by arrfab** [comment]
I just rebuilt first it with a modified Dockerfile , but without having updated the container (still on disk), so haven't touched intermediate layers : 

Step 17/22 : COPY shimx64.efi /
 ---> 33ce8d65468d
Removing intermediate container cd1598f95770
Step 18/22 : RUN hexdump -Cv /build/builddir/BUILDROOT/shim-15-2.el7.centos.x86_64/usr/share/shim/x64-15-2.el7.centos/shimx64.efi > /built.hex
 ---> Running in 1a189bfa2d8a

 ---> 48518a879cdf
Removing intermediate container 1a189bfa2d8a
Step 19/22 : RUN hexdump -Cv /shimx64.efi > /orig.hex
 ---> Running in 05877d4c1b85

 ---> 1dca44e97354
Removing intermediate container 05877d4c1b85
Step 20/22 : RUN diff -u /orig.hex /built.hex || true
 ---> Running in 71735c8fbbf6

--- /orig.hex	2019-01-12 16:16:24.000000000 +0000
+++ /built.hex	2019-01-12 16:16:22.000000000 +0000
@@ -11,7 +11,7 @@
 000000a0  00 d2 06 00 00 00 00 00  00 e0 01 00 00 e0 01 00  |................|
 000000b0  00 00 00 00 00 00 00 00  00 10 00 00 00 02 00 00  |................|
 000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
-000000d0  00 f0 10 00 00 04 00 00  33 11 13 00 0a 00 00 00  |........3.......|
+000000d0  00 f0 10 00 00 04 00 00  36 8d 12 00 0a 00 00 00  |........6.......|
 000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000100  00 00 00 00 10 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -45091,9 +45091,9 @@
 000b0220  61 63 68 69 6e 65 3a 20  4c 69 6e 75 78 20 78 38  |achine: Linux x8|
 000b0230  36 5f 36 34 20 78 38 36  5f 36 34 20 78 38 36 5f  |6_64 x86_64 x86_|
 000b0240  36 34 20 47 4e 55 2f 4c  69 6e 75 78 20 24 0a 24  |64 GNU/Linux $.$|
-000b0250  43 6f 6d 6d 69 74 3a 20  32 38 39 38 62 31 64 36  |Commit: 2898b1d6|
-000b0260  65 30 65 32 34 36 31 31  66 33 62 31 63 38 62 63  |e0e24611f3b1c8bc|
-000b0270  61 35 31 37 33 37 66 35  66 61 38 62 39 35 39 31  |a51737f5fa8b9591|
+000b0250  43 6f 6d 6d 69 74 3a 20  64 61 62 30 62 65 35 62  |Commit: dab0be5b|
+000b0260  37 61 38 66 62 34 34 66  31 63 39 31 62 30 61 33  |7a8fb44f1c91b0a3|
+000b0270  64 36 63 37 36 63 66 37  63 64 39 65 36 36 65 66  |d6c76cf7cd9e66ef|
 000b0280  20 24 0a 00 00 00 00 00  00 00 00 00 00 00 00 00  | $..............|
 000b0290  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000b02a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ---> 4229e39eefab
Removing intermediate container 71735c8fbbf6
Step 21/22 : RUN objdump -x /shimx64.efi | head -n 60
 ---> Running in 14f0ac0d79da


/shimx64.efi:     file format pei-x86-64
/shimx64.efi
architecture: i386:x86-64, flags 0x00000133:
HAS_RELOC, EXEC_P, HAS_SYMS, HAS_LOCALS, D_PAGED
start address 0x000000000001e000

Characteristics 0x206
	executable
	line numbers stripped
	debugging information removed

Time/Date		Sat Jan 10 21:01:04 1970
Magic			020b	(PE32+)
MajorLinkerVersion	2
MinorLinkerVersion	27
SizeOfCode		00096e00
SizeOfInitializedData	0006d200
SizeOfUninitializedData	00000000
AddressOfEntryPoint	000000000001e000
BaseOfCode		000000000001e000
ImageBase		0000000000000000
SectionAlignment	0000000000001000
FileAlignment		0000000000000200
MajorOSystemVersion	0
MinorOSystemVersion	0
MajorImageVersion	0
MinorImageVersion	0
MajorSubsystemVersion	0
MinorSubsystemVersion	0
Win32Version		00000000
SizeOfImage		0010f000
SizeOfHeaders		00000400
CheckSum		00131133
Subsystem		0000000a	(EFI application)
DllCharacteristics	00000000
SizeOfStackReserve	0000000000000000
SizeOfStackCommit	0000000000000000
SizeOfHeapReserve	0000000000000000
SizeOfHeapCommit	0000000000000000
LoaderFlags		00000000
NumberOfRvaAndSizes	00000010

The Data Directory
Entry 0 0000000000000000 00000000 Export Directory [.edata (or where ever we found it)]
Entry 1 0000000000000000 00000000 Import Directory [parts of .idata]
Entry 2 0000000000000000 00000000 Resource Directory [.rsrc]
Entry 3 0000000000000000 00000000 Exception Directory [.pdata]
Entry 4 0000000000000000 00000000 Security Directory
Entry 5 00000000000b5000 0000000a Base Relocation Directory [.reloc]
Entry 6 0000000000000000 00000000 Debug Directory
Entry 7 0000000000000000 00000000 Description Directory
Entry 8 0000000000000000 00000000 Special Directory
Entry 9 0000000000000000 00000000 Thread Storage Directory [.tls]
Entry a 0000000000000000 00000000 Load Configuration Directory
Entry b 0000000000000000 00000000 Bound Import Directory
Entry c 0000000000000000 00000000 Import Address Table Directory
Entry d 0000000000000000 00000000 Delay Import Directory
Entry e 0000000000000000 00000000 CLR Runtime Header
Entry f 0000000000000000 00000000 Reserved
 ---> 8314c5fe1b73
Removing intermediate container 14f0ac0d79da
Step 22/22 : RUN objdump -x /build/builddir/BUILDROOT/shim-15-2.el7.centos.x86_64/usr/share/shim/x64-15-2.el7.centos/shimx64.efi | head -n 60
 ---> Running in 3b2801a95032


/build/builddir/BUILDROOT/shim-15-2.el7.centos.x86_64/usr/share/shim/x64-15-2.el7.centos/shimx64.efi:     file format pei-x86-64
/build/builddir/BUILDROOT/shim-15-2.el7.centos.x86_64/usr/share/shim/x64-15-2.el7.centos/shimx64.efi
architecture: i386:x86-64, flags 0x00000133:
HAS_RELOC, EXEC_P, HAS_SYMS, HAS_LOCALS, D_PAGED
start address 0x000000000001e000

Characteristics 0x206
	executable
	line numbers stripped
	debugging information removed

Time/Date		Sat Jan 10 21:01:04 1970
Magic			020b	(PE32+)
MajorLinkerVersion	2
MinorLinkerVersion	27
SizeOfCode		00096e00
SizeOfInitializedData	0006d200
SizeOfUninitializedData	00000000
AddressOfEntryPoint	000000000001e000
BaseOfCode		000000000001e000
ImageBase		0000000000000000
SectionAlignment	0000000000001000
FileAlignment		0000000000000200
MajorOSystemVersion	0
MinorOSystemVersion	0
MajorImageVersion	0
MinorImageVersion	0
MajorSubsystemVersion	0
MinorSubsystemVersion	0
Win32Version		00000000
SizeOfImage		0010f000
SizeOfHeaders		00000400
CheckSum		00128d36
Subsystem		0000000a	(EFI application)
DllCharacteristics	00000000
SizeOfStackReserve	0000000000000000
SizeOfStackCommit	0000000000000000
SizeOfHeapReserve	0000000000000000
SizeOfHeapCommit	0000000000000000
LoaderFlags		00000000
NumberOfRvaAndSizes	00000010

The Data Directory
Entry 0 0000000000000000 00000000 Export Directory [.edata (or where ever we found it)]
Entry 1 0000000000000000 00000000 Import Directory [parts of .idata]
Entry 2 0000000000000000 00000000 Resource Directory [.rsrc]
Entry 3 0000000000000000 00000000 Exception Directory [.pdata]
Entry 4 0000000000000000 00000000 Security Directory
Entry 5 00000000000b5000 0000000a Base Relocation Directory [.reloc]
Entry 6 0000000000000000 00000000 Debug Directory
Entry 7 0000000000000000 00000000 Description Directory
Entry 8 0000000000000000 00000000 Special Directory
Entry 9 0000000000000000 00000000 Thread Storage Directory [.tls]
Entry a 0000000000000000 00000000 Load Configuration Directory
Entry b 0000000000000000 00000000 Bound Import Directory
Entry c 0000000000000000 00000000 Import Address Table Directory
Entry d 0000000000000000 00000000 Delay Import Directory
Entry e 0000000000000000 00000000 CLR Runtime Header
Entry f 0000000000000000 00000000 Reserved
 ---> 69a7433152ac
Removing intermediate container 3b2801a95032
Successfully built 69a7433152ac

**Comment by cyphermox** [comment]
Ok, after clearing all containers and images and pulling from the repo again, I finally got a binary that was good:

```
Step 21/23 : RUN diff -u /orig.hex /built.hex || true
 ---> Running in b11c529ff178
--- /orig.hex	2019-02-06 20:59:42.000000000 +0000
+++ /built.hex	2019-02-06 20:59:38.000000000 +0000
@@ -11,7 +11,7 @@
 000000a0  00 d2 06 00 00 00 00 00  00 e0 01 00 00 e0 01 00  |................|
 000000b0  00 00 00 00 00 00 00 00  00 10 00 00 00 02 00 00  |................|
 000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
-000000d0  00 f0 10 00 00 04 00 00  33 11 13 00 0a 00 00 00  |........3.......|
+000000d0  00 f0 10 00 00 04 00 00  f9 14 13 00 0a 00 00 00  |................|
 000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 00000100  00 00 00 00 10 00 00 00  00 00 00 00 00 00 00 00  |................|
@@ -45091,9 +45091,9 @@
 000b0220  61 63 68 69 6e 65 3a 20  4c 69 6e 75 78 20 78 38  |achine: Linux x8|
 000b0230  36 5f 36 34 20 78 38 36  5f 36 34 20 78 38 36 5f  |6_64 x86_64 x86_|
 000b0240  36 34 20 47 4e 55 2f 4c  69 6e 75 78 20 24 0a 24  |64 GNU/Linux $.$|
-000b0250  43 6f 6d 6d 69 74 3a 20  32 38 39 38 62 31 64 36  |Commit: 2898b1d6|
-000b0260  65 30 65 32 34 36 31 31  66 33 62 31 63 38 62 63  |e0e24611f3b1c8bc|
-000b0270  61 35 31 37 33 37 66 35  66 61 38 62 39 35 39 31  |a51737f5fa8b9591|
+000b0250  43 6f 6d 6d 69 74 3a 20  66 66 34 63 62 38 39 37  |Commit: ff4cb897|
+000b0260  36 66 36 38 34 39 61 33  32 65 31 32 37 66 61 37  |6f6849a32e127fa7|
+000b0270  62 33 63 37 64 35 38 62  66 66 61 66 30 30 64 31  |b3c7d58bffaf00d1|
 000b0280  20 24 0a 00 00 00 00 00  00 00 00 00 00 00 00 00  | $..............|
 000b0290  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 000b02a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
Removing intermediate container b11c529ff178
```

I find this shim acceptable for signing:

```
$ sha256sum shimx64.efi 
47391a4b25918b7f414420d8f651e302b287a96e0747019d76f705fbf361974e  shimx64.efi
```

**Comment by arrfab** [comment]
Hi guys, can we get a status update on this one please ? (as I see it was tagged as "accepted" 5 days ago) .
Thanks !

**Comment by arrfab** [comment]
Just to comment in this ticket (in case people were following here and not tracking our original bug (https://bugs.centos.org/view.php?id=15522) that the correct packages were now built/signed/pushed to updates repo : 

* mokutil.x86_64                                     15-2.el7.centos         updates 
* shim-ia32.x86_64                                   15-2.el7.centos         updates       
* shim-unsigned-ia32.x86_64                          15-2.el7.centos         updates       
* shim-unsigned-x64.x86_64                           15-2.el7.centos         updates       
* shim-x64.x86_64                                    15-2.el7.centos         updates       

Thanks
