### ISSUE TITLE
where to download patches for Linux 4.19 kernel secure boot?

### ISSUE THREAD

**Issue by haobinnan** [rhboot/shim-review#46]
May I know where to get patches for Linux 4.19 kernel secure boot?

**Comment by cyphermox** [comment]
People use the patchset from David Howells; and update the patches as appropriate for new kernel versions. I don't think the changes are likely to be very big.

https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/linux-fs.git/log/?h=efi-lock-down

Distros may have their own way of handling this, and I'm not a kernel developer, but that's the jist of it. You may want to look at how other distros (Fedora, Ubuntu, SuSE, Debian) have kept these patches so far.

AFAIK, David Howells is working on having these patches upstreamed into the kernel proper, so you might not need to do anything special soon.
