### ISSUE TITLE
2018-12-29 shim-15 (ia32, x64) for OS ALT (Bazalt Svobodnoe Programmnoe Obespechenie, OOO)

### ISSUE THREAD

**Issue by realnickel** [rhboot/shim-review#47]
Hello,

As part of the Shim signing process as requested by Microsoft, I am kindly
asking you to approve our shim to get it signed by Microsoft.
You can download the shim package at:
http://git.altlinux.org/gears/s/shim.git

All the stuff requested by shim review board is at:
https://github.com/realnickel/shim-review.git

### What organization or people are asking to have this signed:

Basealt Ltd. (Bazalt Svobodnoe Programmnoe Obespechenie, OOO)
 https://www.basealt.ru

### What product or service is this for:
OS ALT https://www.basealt.ru/go/download/

### What is the origin and full version number of your shim?
https://github.com/rhboot/shim/releases/tag/15

### What's the justification that this really does need to be signed for the whole world to be able to boot it:
OS ALT is a linux distribution supporting Secure Boot

### How do you manage and protect the keys used in your SHIM?
Access to server used to sign binaries is restricted physically

### Do you use EV certificates as embedded certificates in the SHIM?
no EV certs, but selfsigned altlinux-ca.cer is embedded

### What is the origin and full version number of your bootloader (GRUB or other)?
GRUB2.02, elilo3.16, rEFInd0.11.4
http://git.altlinux.org/gears/g/grub.git
http://git.altlinux.org/gears/e/elilo.git
http://git.altlinux.org/gears/r/refind.git

### If your SHIM launches any other components, please provide further details on what is launched
rEFInd0.11.4 in case of LiveCD or OS installer boot 
grub2.02 in case of installed system

How do the launched components prevent execution of unauthenticated code?

Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Linux Kernel: 4.14 (std-def: standard longterm kernel), http://git.altlinux.org/gears/k/kernel-image-std-def.git; 
4.19 (un-def: more modern than std-def and with forced preemption enabled), http://git.altlinux.org/gears/k/kernel-image-un-def.git?p=kernel-image-un-def.git;a=summary

### What changes were made since your SHIM was last signed?
Upstream version update (0.4 -> 15)

### What is the hash of your final SHIM binary?
479b62c0a762692c45ff9f25c56789c1ede85982e2415f37b6d756de6b685b12 shimia32.efi 2bceb0c2a625ee289218dcc30a7eef8caa9551af82a2af1aba75d2a668c01094 shimx64.efi

**Comment by cyphermox** [comment]
I'm reasonably sure there are a few missing patches to enforce Secure Boot in GRUB; I see only a single patch that adds 'linuxefi', but that alone is not sufficient -- please see the patches applied at https://github.com/rhboot/grub2/commits/grub-2.02-sb

I'll attempt to rebuild shim today, but the above feels to me like a real blocker. @vathpela ?

**Comment by vathpela** [comment]
Yeah, that looks like a blocker to me.  Also elilo and refind haven't been audited, and last I looked at them haven't been made to use the shim verify protocol, so they're not going to work and aren't good candidates to sign for an SB environment.

Has this been tested at all?  I'd expect some failures if it has.

**Comment by realnickel** [comment]
@cyphermox, @vathpela, thanks for your feedback.

> I'm reasonably sure there are a few missing patches to enforce Secure Boot in GRUB; I see only a single patch that adds 'linuxefi', but that alone is not sufficient -- please see the patches applied at https://github.com/rhboot/grub2/commits/grub-2.02-sb

I applied the SB enforcement patch set to our GRUB.
While testing new package release for operability updated sources are available [here](http://git.altlinux.org/people/nickel/packages/?p=grub.git). Later on they would also be available at [gears repo](http://git.altlinux.org/gears/g/grub.git)

Is this sufficient to comply with signed shim compatibility requirements from GRUB's side?

And what concerns to rEFInd and elilo... 
elilo upstream claimed that [project is closed](https://sourceforge.net/p/elilo/news/) and final release is 3.16;
rEFInd development is still running and there is [SB support](http://www.rodsbooks.com/refind/secureboot.html)
@vathpela, could you, please, give it an another audit try?
Anyway if that wouldn't succeed should we drop using elilo and rEFInd at all, or just drop signing those binaries with our key to prevent usage in SB environment to get our shim signed?

**Comment by cyphermox** [comment]
Rebuild done; I find this shim acceptable for signing:

```
479b62c0a762692c45ff9f25c56789c1ede85982e2415f37b6d756de6b685b12  ./build/shimia32.efi
2bceb0c2a625ee289218dcc30a7eef8caa9551af82a2af1aba75d2a668c01094  ./build/shimx64.efi
```

**Comment by realnickel** [comment]
@cyphermox, @vathpela, thank you for review.
Our binaries were signed by Microsoft.
