### ISSUE TITLE
Gooroom-shim-x64-20190328

### ISSUE THREAD

**Issue by jongkyung** [rhboot/shim-review#48]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/jongkyung/shim-review/releases/tag/Gooroom-shim-x64-20190328

 - [x] completed README.md file with the necessary information
https://github.com/jongkyung/shim-review/blob/master/README.md

 - [x] shim.efi to be signed
https://github.com/jongkyung/shim-review/blob/master/shimx64.efi

 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/jongkyung/shim-review/blob/master/gooroom-uefi-ca.der

 - [x] any extra patches to shim via your own git tree or as files
No patched appied

 - [x] any extra patches to grub via your own git tree or as files
https://github.com/jongkyung/shim-review/blob/master/gooroom-validate-linux-image-by-shim.patch

 - [x] build logs
https://github.com/jongkyung/shim-review/blob/master/build.log

###### What organization or people are asking to have this signed:
`[Gooroom]`

###### What product or service is this for:
`[Gooroom OS]`

###### What is the origin and full version number of your shim?
`[shim 15+1533136590.3beb971-0ubuntu1+grm1u1]`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`[To make secure boot on Gooroom OS]`

###### How do you manage and protect the keys used in your SHIM?
`[no]`

###### Do you use EV certificates as embedded certificates in the SHIM?
`[no]`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`[grub2 2.02+beta3-5+grm1u6]`

###### If your SHIM launches any other components, please provide further details on what is launched
`[none]`

###### How do the launched components prevent execution of unauthenticated code?
`[We will show messages that execution of unauthenticated code isn't working]`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`[no]`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`[linux 4.9.110-3+deb9u6+grm1u2, no patches for secure boot]`

###### What changes were made since your SHIM was last signed?
`[no, It's first time]`

###### What is the hash of your final SHIM binary?
`[sha256sum fb501b838fe9b91b6adfd9eaa5ff0c5824c7f802fcdc1f960d13a11f3a3db76c  ./shimx64.efi]`

**Comment by cyphermox** [comment]
How can we proceed with attempting to rebuild this? Do you have images available so that we can have a look and reproduce the binaries you are creating for shim?

**Comment by jongkyung** [comment]
You can download the Gooroom 1.2 iso with the shim binaries (/usr/lib/shim/shimx64.efi)

https://drive.google.com/open?id=14R4-QaNoUndMCDG1ae1hdjvIYrIPn_6o

We are currently developing a distribution, 
so please share it with Google Drive so that you understand it.

**Comment by cyphermox** [comment]
But what we want to do is rebuild this shim to make sure we can build it with the same toolchain; the same source code; and find that we're getting the same binary -- that it hasn't been tampered with.

I tried to reproduce the build, but I am unable to find the right set of toolchain (binutils, gcc, etc.) to successfully get back a similar binary. It seems like this is a mix of old packages from Debian and Ubuntu, but I can't quite get the same package versions.

**Comment by jongkyung** [comment]
I uploaded live iso again, including the toolchain.
https://drive.google.com/open?id=1jgA1HD4rBK_8VxMx_tw3VGr9S2iAsAi1

$ sha256sum ./Gooroom-1.3-20190328-toolchain-amd64.hybrid.iso 
35ee20ad1d81cea7a07a2843e15ba4b4a2f98bf4bf3c16d3556883534bf2783e  ./Gooroom-1.3-20190328-toolchain-amd64.hybrid.iso

I put the shim source in the /shim directory.
$ sudo tar xvzf shim-15+1533126590.3beb971-0ubunutu1+grm1u1.tar.gz
$ cd shim.git
$ sudo dpkg-buildpakage -b

Thanks again in advance for your review.

**Comment by cyphermox** [comment]
Thanks. I'm downloading the image, I will have another look.

**Comment by cyphermox** [comment]
Rebuild done; things are looking good here.

I find this shim acceptable for signing:

```
fb501b838fe9b91b6adfd9eaa5ff0c5824c7f802fcdc1f960d13a11f3a3db76c ./shimx64.efi
```

**Comment by jongkyung** [comment]
thank you!!!
