### ISSUE TITLE
Question on signing process of shim-review project

### ISSUE THREAD

**Issue by caschulz88** [rhboot/shim-review#50]
Hi,

I have a short question on shim-review project and what it is for. So basically it's for signing a shim bootloader, which loads a GRUB2 bootloader afterwards. That's clear so far. For loading next stage (Linux kernel, etc...) the GRUB2 is responsible and therefor you are out of it and only check if the shim loads the GRUB2 correct?

What if it comes to the following scenario:

shim -> GRUB2 -> chainload bootmgfw

the chainloaded bootmgfw has been signed by our KEK, which is built-in shim so that the verification succeeds within GRUB2. If I understood it correctly GRUB2 uses the verification methods provided by shim when executing LoadImage() and StartImage() first tries to valide using the MOKs (Machine Owner Keys) and if this fails with EFI_SECURITY_VIOLATION it will check if the built-in certificate will work for valication. In case the chainloaded bootmgfw would load itself other EFI components via LoadImage() and StartImage() it will have to use the same strategy for validation so that shim can validate as well - otherwise only the MOKs will be used and will again fail due to EFI_SECURITY_VIOLATION.

Is such a scenario also covered by the shim-review process and is it required to use a certain version of GRUB2 to get the shim with built-in certificate signed (e.g. latest version in rhboot project)? Signing a shim, which loads the bootmgfw directly is not supported, but with inserting the GRUB2 in between there should be no blocker any longer.

Thanks a lot for clarification!

Cheers

**Comment by cyphermox** [comment]
This was a question, does not require shim review -- closing now (you can still comment afterwards anyway)
