### ISSUE TITLE
shim-15 for BCWipe Total WipeOut 

### ISSUE THREAD

**Issue by Jetico** [rhboot/shim-review#52]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/Jetico/shim-review
 - [x] completed README.md file with the necessary information
make VENDOR_CERT_FILE=pub_cert.der
 - [x] shim.efi to be signed
https://github.com/Jetico/shim-review/blob/master/bootx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/Jetico/shim-review/blob/master/pub_cert.der
 - [x] any extra patches to shim via your own git tree or as files
https://github.com/Jetico/shim-review/blob/master/shim.patch
 - [x] any extra patches to grub via your own git tree or as files
https://github.com/Jetico/shim-review/blob/master/grub_patch.diff
 - [x] build logs
https://github.com/Jetico/shim-review/blob/master/build.log

###### What organization or people are asking to have this signed:
Jetico Inc. Oy https://www.jetico.com/

###### What product or service is this for:
BCWipe Total WipeOut
https://www.jetico.com/data-wiping/wipe-hard-drives-bcwipe-total-wipeout

###### What is the origin and full version number of your shim?
shim-15

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Jetico products are trusted by government and military agencies, all of the top 10 U.S. defense contractors, many national laboratories, as well as various other enterprises and a wide global base of home and small business users in over 100 countries.

###### How do you manage and protect the keys used in your SHIM?
It is stored on e-Token
Physically isolated
Only one person has access to it

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes

###### What is the origin and full version number of your bootloader (GRUB or other)?
GRUB 2.02

###### If your SHIM launches any other components, please provide further details on what is launched
Custom Linux build with our bcwipe application

###### How do the launched components prevent execution of unauthenticated code?
Components are protected by digital signatures, signed with our private key and verified by this shim build with our public key, which is embedded into application code.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
kernel 4.19.2

###### What changes were made since your SHIM was last signed?
This is first submission.

###### What is the hash of your final SHIM binary?
sha256
368a698a60df3fe2a95d782d35e651f079816813365ae2acde2537a9d206c917

**Comment by Jetico** [comment]
Hello
Is there a way to speed up process somehow?

**Comment by cyphermox** [comment]
We need to be able to reproduce the binaries built to complete the review. Do you have instructions on how this can be done? Those should be in README.md.

Some of the shim patching is bizarre. Why do you need to add dgst? Why some of the other changes?

Also, it seems to be like grub will be missing a number of patches for Secure Boot support, so it would load any further pieces (linux kernel, etc) without verifying if they are signed by a valid key.

**Comment by Jetico** [comment]
Our extra code is in the the https://github.com/Jetico/shim-review/blob/master/shim.patch so it must be applied to latest shim and built as usual. Also the full source code can be found here https://github.com/Jetico/shim

Initially GRUB  allows to verify binaries, signed with gpg keys and allows to verify only standard components (linux kernel, etc).  Also security vulnerability related to check_signatures variable exist. We need to verify not only standard components, but also our binaries, which are loaded at the start up time too. That is why we are signing all required binaries with our private key, got from Microsoft. Our shim module verify grub and all other pieces and only in the case when all parts passes verification it starts grub.

**Comment by cyphermox** [comment]
I still don't understand. What is the use of the DGST functions? If things are properly signed, you will not need it -- things are signed, and provided that it is with a trusted key, which you seem to say it would be, then you should not need any code changes there.

Furthermore, though it's not a blocker: use_fb changes are unncessary. You could just as well simply not install fb<arch>.efi on disk and it wouldn't run.

Then we have no way currently of validating your copy of grub -- as I mentioned previously, the patches you apply to grub, if they are applied to the upstream grub, are insufficient to enfore that binaries are appropriately signed.

**Comment by Jetico** [comment]
DGST is required to sign and verify all binaries and any files, other then GRUB. They are signed with OpenSSL dgst application and out private key, got from Microsoft. Since signature cannot be integrated into binary itself and also because we can sign and verify any file with such approach. For example list of all files we need to verify stored in the efi_boot.lst which is also signed. In opposite case anybody can substitute any of the files we are loading. So this is the way we guaranty consistency of the system at boot time. And that is why we do not need  similar functionality from GRUB and any of its patches.

Also I added our signed grub binary https://github.com/Jetico/shim-review/blob/master/grubx64.efi

**Comment by cyphermox** [comment]
I'm reassigning this to @vathpela; I think I'm missing some context here to be able to review this.

DGST is just digest, is it not? How is that different than how shim already does handle things that are allowed by hash?

**Comment by Jetico** [comment]
Hello
Do you need any comments from me?

**Comment by Jetico** [comment]
Why it takes so long? Almost two months passed since I posted this request.

**Comment by cyphermox** [comment]
Reviews are done by volunteers, we are all busy with normal work tasks. I've assigned this to @vathpela because I do not feel confident in reviewing this, I don't think I understand well enough what is being done to approve it.

Please be patient.

**Comment by Jetico** [comment]
More then 3 months passed already. Will anybody look at this?

**Comment by Jetico** [comment]
5 months passed... Anybody please help!

**Comment by Jetico** [comment]
more then 7 months pased

**Comment by Jetico** [comment]
Almost 8 months passed.

**Comment by Jetico** [comment]
I year anniversary! Congratulations!!!

**Comment by Jetico** [comment]
Dear Mathieu Trudel-Lapierre (@cyphermox),

In April 16, 2019 you kindly wrote:

"Reviews are done by volunteers, we are all busy with normal work tasks. I've assigned this to @vathpela because I do not feel confident in reviewing this, I don't think I understand well enough what is being done to approve it.

Please be patient."

Please note that we have received no comments, requests or questions from Peter Jones (@vathpela) since April, 2019.

Let me say that delaying the review strongly influences our ability to deliver the solution to our customers, who are real people and who suffer from the delay.

On the other hand, there is no so much unusual in our UEFI module and we are always ready to comment any piece of code inside it, as well as to give more general overview of it.

Our company (Jetico) delivers UEFI pre-boot code for Windows for many years. The code was and (continue to be) evaluated and signed by Microsoft. We would not risk our reputation and ask you to review UEFI module that would harm security of our customers.

May I ask you to pay attention to our request again and ask someone to assist Peter Jones (@vathpela) in evaluating our UEFI module?

Best regards,
Sergey Frolov,
Jetico CTO

**Comment by xnox** [comment]
@Jetico 

I'm not a shim-reviewer, but reading this issue, there are still outstanding questions.

Previously it was mentioned
> "DGST is required to sign and verify all binaries and any files, other then GRUB"

However that does not bide by the shim-review policies, as mentioned in other issues in this repository. I.e.

> Why do you need shim signed, rather than having Microsoft sign your own bootloader?
>
> We typically only sign shims when developped in order to chainload grub, for Linux distributions. Without being able to review the next stage bootloader, I'm not in a position to be able to tell whether or not the next stage is secure, and will in fact refuse to load unsigned binaries.

Also, the grub patch mentioned in your submission and the version indicated are incomplete. Stock grub 2.02 without additional secureboot patches is insufficient to enforce loading only trusted and signed code and thus shim signing should not be performed yet.

Please update the submission with answers to the below questions, which are still outstanding based on the previous discussion.

Questions:
 1. How does "GRUB" binary enforce secureboot validation? (2.02 + mentioned patch do not do that)
 1. Why is DGST included in your shim submission?
 1. Which "other than GRUB" binaries are signed, verified and loaded?
 1. How do those "other than GRUB" binaries enforce that unsigned and untrusted binaries are not executed?

**Comment by Jetico** [comment]
Hello

Let me explain where the potential difficulty for you or your colleagues as reviewers may be.

Since only loaders signed by Microsoft can be used in secure boot mode, ideally we need to sign both SHIM and GRUB efi boot loaders to be able to load them in chain.

As you said, GRUB itself does not guarantee that any other files used in the boot process are securely validated. It is the reason why our additional code in the standard SHIM module appeared. Our addition is simple: we utilize our own certificate to sign all the files used during boot process.

Few technical detail. We have a file efi_boot.lst which is signed using DGST and our certificate. The file contains the list of files which is used by GRUB: such as kernel images and our binary 'bcwipe' with related files. Each of these files has its own DGST file that  is used to verify its authenticity.

When SHIM loader starts, it checks authenticity of each file in the list from efi_boot.lst. If all files are valid, then it loads the GRUB loader. Otherwise it finishes with an error.

To summarize: we are using a regular SHIM to perform its usual task to start GRUB boot loader. Exactly as it is in a common case in any Linux distro. The only we add is a simple mechanism that should guarantee that any file used during boot process is not compromised. As you see, our SHIM runs in a usual way with few security improvements to guarantee integrity of the boot process.

Answering your other question, yes, we sent a request to sign our slightly modified SHIM module to Microsoft for signing, as we always do to sign our other EFI module for full disk encryption software for Windows. Microsoft replied that since we need 99% standard SHIM module signed, we should send the request to your community.

We would greatly appreciate any assistance in getting the SHIM module signed.

**Comment by xnox** [comment]
> Hello
> 
> Let me explain where the potential difficulty for you or your colleagues as reviewers may be.
> 
> Since only loaders signed by Microsoft can be used in secure boot mode, ideally we need to sign both SHIM and GRUB efi boot loaders to be able to load them in chain.
> 
> As you said, GRUB itself does not guarantee that any other files used in the boot process are securely validated. It is the reason why our additional code in the standard SHIM module appeared. Our addition is simple: we utilize our own certificate to sign all the files used during boot process.
> 

Unpatched GRUB does not, but rhboot or other vendor grubs do have patches applied to call into shim and use regular signing mechanisms to verify binaries and ensure secureboot operation works correctly. It is preferred to simply use the regular SecureBoot COFF/PE signing, and ensuring that the grub in use has rhboot patches applied that verify secureboot patches of everything grub loads.


> Few technical detail. We have a file efi_boot.lst which is signed using DGST and our certificate. The file contains the list of files which is used by GRUB: such as kernel images and our binary 'bcwipe' with related files. Each of these files has its own DGST file that is used to verify its authenticity.

That still is not enough to harden grub itself, I don't think. Is grub module loading allowed?

Can you point to the binaries and source code of the bcwipe binary?

> 
> When SHIM loader starts, it checks authenticity of each file in the list from efi_boot.lst. If all files are valid, then it loads the GRUB loader. Otherwise it finishes with an error.
> 

...after which grub is free to load things not listed in efi_boot.lst and circumvent SecureBoot?

> To summarize: we are using a regular SHIM to perform its usual task to start GRUB boot loader. Exactly as it is in a common case in any Linux distro. The only we add is a simple mechanism that should guarantee that any file used during boot process is not compromised. As you see, our SHIM runs in a usual way with few security improvements to guarantee integrity of the boot process.
> 

Normal procedure is to use patched grub, which uses existing shim APIs to verify and validate any files it loads. Prevalidating a set of files does not prevent for these signed & validated artefacts to load / chainload additional unsigned ones.


> Answering your other question, yes, we sent a request to sign our slightly modified SHIM module to Microsoft for signing, as we always do to sign our other EFI module for full disk encryption software for Windows. Microsoft replied that since we need 99% standard SHIM module signed, we should send the request to your community.
> 
> We would greatly appreciate any assistance in getting the SHIM module signed.

I am not a shim-review reviewer. If I was, I would want to see your SHIM patches submitted to the shim project and reviewed there, together with design documentation explaining how it all works together.

At the moment your submission is still not obvious or clear. Links to source codes missing. Including how to reproduce and test efi_boot.lst based signing. As part of the review, reviewers normally rebuild all the artefacts from scratch and retest with self signed certificates to ensure the secureboot chain works correctly and attempt to test that implementation boots and fails to boot when tampered with.

You did explain how grub itself is validated, but did not explain how grub validates things from then on. `How does "GRUB" binary enforce secureboot validation?`

**Comment by Jetico** [comment]
SecureBoot COFF/PE signing is available only for EFI PE executables, but our method allows to verify any binary by creating its digest file with the help of certificate, provided by Microsoft to our company. 

In our model GRUB does not perform any validation, but it is also signed by us and should be signed with Microsoft certificate to be loaded by shim, that is the guaranty of its integrity. We are providing universal approach for validating any kind of file and we are using certificate, provided by Microsoft, rather then selfsigned certificate. All code used in validation is listed in the shim.patch file.

In the following repository https://github.com/Jetico/shim-review listed above, you can find all required files, including our code patches. We can also provide bcwipe  binary, but not source code, since it is our private product.

We can also describe procedure of creating digest more detailed if required to reproduce the whole life cycle.

**Comment by Jetico** [comment]
Hello Dimitry ( @xnox ),

May I suggest we should ask your assistance in moving forward with reviewing and signing the module?

Actually what needed is that someone from your community would take a look at small modifications we made in the regular SHIM (https://github.com/Jetico/shim-review) :

1) 7 strings in grub_patch.diff

2) several procedures in  shim.patch like: dgstPrepareKey() DGST_verifyFile(), DGST_verifyAll().

The purpose of the procedures is to be able to verify authenticity of
all types of files used in the boot process, not only COFF/PE files 
with embedded signatures.  

All of that is about 430 lines of code. Of course we can provide as many explanations for the code as needed.

Regarding the "bcwipe" file, it is an engine that erases contents of disks on physical level. Where we use the SHIM is in our product BCWipe TWO utilized by our customers to completely erase all hard drives on computers before re-using (recycling) them. For example, before
donating computers with classified data to something like kindergartens or schools.

So the SHIM is intended not for using it in a regular computer environment, but to securely destroy the environment. Computers with classified data should use highly protected binaries. 

It is the reason why we needed to add these 400 lines of code to the SHIM and why we ask you to evaluate and sign the code if you do not see any dangerous functionality in it.

Best regards,
Sergey Parfenenok
Jetico Inc. Oy

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
