### ISSUE TITLE
shim-15 for RHEL 8

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#55]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/vathpela/shim-review/tree/rhel-8.0
 - [x] completed README.md file with the necessary information
https://github.com/vathpela/shim-review/blob/rhel-8.0/README.md
 - [x] shim.efi to be signed
https://github.com/vathpela/shim-review/blob/rhel-8.0/shimx64.efi
https://github.com/vathpela/shim-review/blob/rhel-8.0/shimia32.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/vathpela/shim-review/blob/rhel-8.0/securebootca.cer
 - [x] any extra patches to shim via your own git tree or as files
Look at the four patches in that same repo
 - [x] any extra patches to grub via your own git tree or as files
It's the normal patchset
 - [x] build logs
https://github.com/vathpela/shim-review/blob/rhel-8.0/build.log

###### What organization or people are asking to have this signed:
Red Hat, Inc.

###### What product or service is this for:
Red Hat Enterprise Linux 8

###### What is the origin and full version number of your shim?
It's shim-15 plus four patches from the shim-16 tree.

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
We're a bigtime major OS vendor.

###### How do you manage and protect the keys used in your SHIM?
They're in an HSM

###### Do you use EV certificates as embedded certificates in the SHIM?
No; they're generated by the Red Hat Product Security team.

###### What is the origin and full version number of your bootloader (GRUB or other)?
It's grub2-2.02-66.el8 , which has the normal complement of secure boot patches plus some other stuff.

###### If your SHIM launches any other components, please provide further details on what is launched
Also fwupdate.

###### How do the launched components prevent execution of unauthenticated code?
They don't launch other code.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
The Red Hat Enterprise Linux kernel includes secure boot patches.

###### What changes were made since your SHIM was last signed?
Four patches from shim-16.

###### What is the hash of your final SHIM binary?
9c4c64b68492106841165edf01ee98bce8355372552a232a9242086d04068b39  shimia32.efi
159bffbe9ce28b840d4ec203f29895ba5ac859e5aa6bf851a71f33bf2f34b4a4  shimx64.efi

**Comment by cyphermox** [comment]
This build is easily reproducible. No issues.

I find this shim acceptable for signing:

```
Step 16/16 : RUN sha256sum /builddir/build/BUILDROOT/shim*/usr/share/shim/*/*/shim*.efi
 ---> Running in 7ff35fc8f986
9c4c64b68492106841165edf01ee98bce8355372552a232a9242086d04068b39  /builddir/build/BUILDROOT/shim-unsigned-x64-15-2.el8.x86_64/usr/share/shim/15-2.el8/ia32/shimia32.efi
159bffbe9ce28b840d4ec203f29895ba5ac859e5aa6bf851a71f33bf2f34b4a4  /builddir/build/BUILDROOT/shim-unsigned-x64-15-2.el8.x86_64/usr/share/shim/15-2.el8/x64/shimx64.efi
```
