### ISSUE TITLE
shim 15+1533136590.3beb971-4 for Debian

### ISSUE THREAD

**Issue by tfheen** [rhboot/shim-review#57]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/tfheen/shim-review/tree/debian-shim-ia32-x64-aa64-15+1533136590.3beb971-4
 - [x] completed README.md file with the necessary information
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/README.md
 - [x] shim.efi to be signed
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shimaa64.efi
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shimia32.efi
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/debian-uefi-ca.der
 - [x] any extra patches to shim via your own git tree or as files
https://salsa.debian.org/efi-team/shim/blob/master/debian/patches/fixup_git.patch
https://salsa.debian.org/efi-team/shim/blob/master/debian/patches/uname.patch
 - [x] any extra patches to grub via your own git tree or as files
https://salsa.debian.org/grub-team/grub/tree/master/debian/patches has the complete list of patches.
 - [x] build logs
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shim_15%2B1533136590.3beb971-4_amd64.log
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shim_15%2B1533136590.3beb971-4_arm64.log
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shim_15%2B1533136590.3beb971-4_i386.log

###### What organization or people are asking to have this signed:
Debian

###### What product or service is this for:
We are a well-know GNU/Linux distribution.

###### What is the origin and full version number of your shim?
https://github.com/rhboot/shim/tree/15 + commits up to https://github.com/rhboot/shim/commit/3beb971b10659cf78144ddc5eeea83501384440c

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Debian is used by lots of people.

###### How do you manage and protect the keys used in your SHIM?
Root CA is sharded between a set of trusted people. Production keys are stored in a HSM.

###### Do you use EV certificates as embedded certificates in the SHIM?
No

###### What is the origin and full version number of your bootloader (GRUB or other)?
grub2 2.02+dfsg1-12

###### If your SHIM launches any other components, please provide further details on what is launched
fwupdate, and it can also launch Linux directly.

###### How do the launched components prevent execution of unauthenticated code?
fwupdate does not launch other code, Linux has secure boot support.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Currently 4.19 with secure boot patches/support.

###### What changes were made since your SHIM was last signed?
Updated to a newer shim version.

###### What is the hash of your final SHIM binary?
SHA256:
```
9b6633dc6138d08152a8945ac9bc45b66480e9d330ab0ac8823bb38267cdf08f  shimia32.efi
da5697e450aeaf82d52e14ebc5e53f4702044bc110980c3b6f37b3ba58c6d19b  shimx64.efi
baa392632d9fdf362f320c35b438ec4db90d6c4bb6a0452e89cc0c1ee5206d8d  shimaa64.efi
```

**Comment by cyphermox** [comment]
Partial rebuild done; also reviewed the shim code in the repo used to build (based on 3beb971) which matches.

I find this shim (x64) acceptable for signing. The same code is used everywhere so I don't expect issues; but I don't have a setup right now to test ia32 or aa64.
```
root@3dec482b6682:/shim# sha256sum shimx64.efi
da5697e450aeaf82d52e14ebc5e53f4702044bc110980c3b6f37b3ba58c6d19b  shimx64.efi
```

**Comment by vathpela** [comment]
I can also confirm the x64 build and find it acceptable for signing:

> root@ef23b292ae11:/shim# sha256sum shimx64.efi
> da5697e450aeaf82d52e14ebc5e53f4702044bc110980c3b6f37b3ba58c6d19b  shimx64.efi

And the aa64 one:
> root@cb82451879aa:/# sha256sum shim/shimaa64.efi
> baa392632d9fdf362f320c35b438ec4db90d6c4bb6a0452e89cc0c1ee5206d8d  shim/shimaa64.efi

Still working on the ia32 one...

**Comment by vathpela** [comment]
The magic is to change the Dockerfile to have:
> FROM docker.io/i386/debian:buster
and then use "setarch linux32 ..." with the build.

That said, I can reproduce the shimia32.efi build as well, and find it acceptable for signing:

> root@bd1c36809a29:/# sha256sum shim/shim*.efi
> 9b6633dc6138d08152a8945ac9bc45b66480e9d330ab0ac8823bb38267cdf08f  shim/shimia32.efi

**Comment by tfheen** [comment]
> The magic is to change the Dockerfile to have: […]

Yes, or use a 32 bit host and it'll automatically DTRT.

Thanks a lot for the speedy approval!

**Comment by tfheen** [comment]
Closing this as it has been processed.
