### ISSUE TITLE
2017-11-03 SUSE

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#6]
Date: Fri, 3 Nov 2017 12:24:37 +0100
From: Johannes Segitz
Subject: Re: [Shim-review] Shim review for SUSE

On Fri, Oct 27, 2017 at 09:44:28AM -0400, Mathieu Trudel-Lapierre wrote:
> It's the right procedure; these include pretty much all the
> information necessary to review shim. If anything is missing, we'll
> ask about it :)

Then lets see how good my first try at this is :)

http://users.suse.com/~jsegitz/files/README.txt
http://users.suse.com/~jsegitz/files/SLES%20ES%20platform-7.4-x86_64-CHECKSUM
http://users.suse.com/~jsegitz/files/SLES%20ES%20platform-7.4-x86_64-DVD.iso
http://users.suse.com/~jsegitz/files/SLES%20ES%20platform-netinst-7.4-x86_64.iso
http://users.suse.com/~jsegitz/files/build-x86_64.log.gz
http://users.suse.com/~jsegitz/files/shim_cert.tar.gz
http://users.suse.com/~jsegitz/files/shim_cert.tar.gz.sha256
http://users.suse.com/~jsegitz/files/shimia32.efi
http://users.suse.com/~jsegitz/files/shimia32.efi.sha256
http://users.suse.com/~jsegitz/files/shimx64.efi
http://users.suse.com/~jsegitz/files/shimx64.efi.sha256

Johannes
--
GPG Key E7C81FA0       EE16 6BCE AD56 E034 BFB3  3ADD 7BF7 29D5 E7C8 1FA0
Subkey fingerprint:    250F 43F5 F7CE 6F1E 9C59  4F95 BC27 DD9D 2CC4 FD66
SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton
HRB 21284 (AG Nürnberg)

**Comment by cyphermox** [comment]
I checked this one, it looked fine to me. Peter also responded in email. AFAIK it's up to Microsoft to sign now.
