### ISSUE TITLE
shim-15 for RHEL 7.7

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#60]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/vathpela/shim-review/tree/rhel-7.7
 - [x] completed README.md file with the necessary information
https://github.com/vathpela/shim-review/blob/rhel-7.7/README.md
 - [x] shim.efi to be signed
https://github.com/vathpela/shim-review/blob/rhel-7.7/shimx64.efi
https://github.com/vathpela/shim-review/blob/rhel-7.7/shimia32.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/vathpela/shim-review/blob/rhel-7.7/securebootca.cer
 - [x] any extra patches to shim via your own git tree or as files
Look at the four patches in that same repo
 - [x] any extra patches to grub via your own git tree or as files
It's the normal patchset
 - [x] build logs
https://github.com/vathpela/shim-review/blob/rhel-7.7/build.log

###### What organization or people are asking to have this signed:
Red Hat, Inc.

###### What product or service is this for:
Red Hat Enterprise Linux 7.7

###### What is the origin and full version number of your shim?
It's shim-15 plus five patches from the shim-16 tree.

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
We're a bigtime major OS vendor.

###### How do you manage and protect the keys used in your SHIM?
They're in an HSM

###### Do you use EV certificates as embedded certificates in the SHIM?
No; they're generated by the Red Hat Product Security team.

###### What is the origin and full version number of your bootloader (GRUB or other)?
It's grub2-2.02-0.77.el7 , which has the normal complement of secure boot patches plus some other stuff.

###### If your SHIM launches any other components, please provide further details on what is launched
Also fwupdate.

###### How do the launched components prevent execution of unauthenticated code?
They don't launch other code.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
The Red Hat Enterprise Linux kernel includes secure boot patches.

###### What changes were made since your SHIM was last signed?
Four patches from shim-16.

###### What is the hash of your final SHIM binary?
2fd772685ba17fc10f1bc3d73ceb3781b954cd4052f4342e5785d637a9c4b2eb  shimia32.efi
24f966a9ccabf707e819ff121c6d09793c729d30f591bac7d73f75dd968daf0d  shimx64.efi

**Comment by steve-mcintyre** [comment]
Looks fine to me. Trivial nits in the submission:

* your spec file is comedically old! (stil referring to mjg59's site for shim releases)
* your last two patches don't match the sha1 refs in the repo, as the commit messages were updated (code is obviously the same, so meh)
