### ISSUE TITLE
Shim for Newstart Desktop Linux V3

### ISSUE THREAD

**Issue by cxy-uestc** [rhboot/shim-review#62]
Make sure you have provided the following information:

 - [*] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
      https://github.com/cxy-uestc/shim-review/tree/nsdl-shim-x86_64-20190312
 - [*] completed README.md file with the necessary information
      https://github.com/cxy-uestc/shim-review/blob/nsdl-3.0/README.md
 - [*] shim.efi to be signed
      https://github.com/cxy-uestc/shim-review/blob/nsdl-3.0/shim.efi
 - [*] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
      https://github.com/cxy-uestc/shim-review/blob/nsdl-3.0/NSDLca.cer
 - [*] any extra patches to shim via your own git tree or as files
      Normal patch
 - [*] any extra patches to grub via your own git tree or as files
       None
 - [*] build logs
     https://github.com/cxy-uestc/shim-review/blob/nsdl-3.0/build.log

What organization or people are asking to have this signed:
Guangdong Zhongxing Newstart Technology Co. ,Ltd (http://www.gd-linux.com/)

Version of shim:
0.8

Sysdev Submission ID:
Microsoft told us to get approval from the shim review board before submitting it to them.

What product or service is this for:
Newstart Desktop Linux V3

What's the justification that this really does need to be signed for the whole world to be able to boot it:
Newstart is a Linux distro; we'd like to encourage people to boot our OS with secure boot enabled.

**Comment by jprvita** [comment]
A lot of information is missing from this request, please provide all the information listed in https://github.com/rhboot/shim-review/blob/master/ISSUE_TEMPLATE.md on the actual issue description.

From the provided information (grub version 2.02-0.38) it is not clear whether your grub enforces secure boot or not -- please make it clearer where your are getting you grub package from.

It does not look like the provided GPG keys have any signatures on them.

**Comment by cxy-uestc** [comment]
Has been added, please take a review for the pull request. https://github.com/rhboot/shim-review/pull/66
Thank you very much for your suggestions.

**Comment by cyphermox** [comment]
Why is this a build of such an old version of shim? There have been many releases since 0.8 with a ton of new features and bug fixes.

**Comment by cxy-uestc** [comment]
Because such an old version of shim have meet our OS's requirement.  The latest shim has a few questions for us, We are still in research to solve these problems.  Do the latest shim is a must if we use it in our OS?

**Comment by cxy-uestc** [comment]
@cyphermox   Do the latest shim is a must if we use it in our OS?

**Comment by cxy-uestc** [comment]
I look forward to receiving your reply and I will modify my shim version if necessary.

**Comment by cyphermox** [comment]
You should have a very very good reason to use a shim older than the newest one, especially for a new signature request. There are tons of improvements, bug fixes and potential security fixes included in new releases.

What issues do you have with the new shim versions? We can certainly resolve those quickly.

**Comment by cxy-uestc** [comment]
The main issue of the shim version is compiled problem. 
"gcc -ggdb -O0 -fno-stack-protector -fno-strict-aliasing -fpic -fshort-wchar -Wall -Wsign-compare -Werror -fno-builtin -Werror=sign-compare -ffreestanding -std=gnu89 -I/usr/lib/gcc/x86_64-redhat-linux/9/include "-DDEFAULT_LOADER=L\"\\\\grubx64.efi\"" "-DDEFAULT_LOADER_CHAR=\"\\\\grubx64.efi\"" -nostdinc -I/root/rpmbuild/BUILD/shim-15/Cryptlib -I/root/rpmbuild/BUILD/shim-15/Cryptlib/Include -I/usr/include/efi -I/usr/include/efi/x86_64 -I/usr/include/efi/protocol -I/root/rpmbuild/BUILD/shim-15/include -iquote /root/rpmbuild/BUILD/shim-15 -iquote /root/rpmbuild/BUILD/shim-15/build-x64 -DENABLE_HTTPBOOT -mno-mmx -mno-sse -mno-red-zone -nostdinc -maccumulate-outgoing-args -m64 -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI -DNO_BUILTIN_VA_FUNCS -DMDE_CPU_X64 -DPAGE_SIZE=4096 "-DEFI_ARCH=L\"x64\"" "-DDEBUGDIR=L\"/usr/lib/debug/usr/share/shim/x64-15-1.fc30/\"" -DVENDOR_CERT_FILE=\"/root/rpmbuild/SOURCES/fedora-ca.cer\" -DVENDOR_DBX_FILE=\"/root/rpmbuild/SOURCES/dbx.esl\"   -c -o MokManager.o /root/rpmbuild/BUILD/shim-15/MokManager.c
/root/rpmbuild/BUILD/shim-15/MokManager.c: In function 'write_back_mok_list':
/root/rpmbuild/BUILD/shim-15/MokManager.c:1081:19: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1081 |   if (CompareGuid(&(list[i].Type), &X509_GUID) == 0)
      |                   ^~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/shim-15/MokManager.c:1103:19: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1103 |   if (CompareGuid(&(list[i].Type), &X509_GUID) == 0) {
      |                   ^~~~~~~~~~~~~~~
/root/rpmbuild/BUILD/shim-15/MokManager.c: In function 'delete_cert':
/root/rpmbuild/BUILD/shim-15/MokManager.c:1144:19: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1144 |   if (CompareGuid(&(mok[i].Type), &X509_GUID) != 0)
      |                   ^~~~~~~~~~~~~~
/root/rpmbuild/BUILD/shim-15/MokManager.c: In function 'delete_hash_in_list':
/root/rpmbuild/BUILD/shim-15/MokManager.c:1195:20: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1195 |   if ((CompareGuid(&(mok[i].Type), &Type) != 0) ||
      |                    ^~~~~~~~~~~~~~
/root/rpmbuild/BUILD/shim-15/MokManager.c: In function 'delete_keys':
/root/rpmbuild/BUILD/shim-15/MokManager.c:1359:19: error: taking address of packed member of 'struct <anonymous>' may result in an unaligned pointer value [-Werror=address-of-packed-member]"

**Comment by newstart-lb** [comment]
Hello! it has been a month and a half , I want to know if the above problem has been solved. how to do it? @cyphermox

**Comment by xnox** [comment]
@cxy-uestc @newstart-lb I see that the build issue you raised has been fixed in shim master

https://github.com/rhboot/shim/commit/58532e12e9aa207e3c14096f4f5d6f7900130c52

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
