### ISSUE TITLE
shim 15+1533136590.3beb971-7 for Debian

### ISSUE THREAD

**Issue by tfheen** [rhboot/shim-review#67]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/tfheen/shim-review/tree/debian-shim-ia32-x64-aa64-15+1533136590.3beb971-7
 - [x] completed README.md file with the necessary information
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-7/README.md
 - [x] shim.efi to be signed
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-7/shimaa64.efi
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-7/shimia32.efi
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-7/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/debian-uefi-ca.der
 - [x] any extra patches to shim via your own git tree or as files
https://salsa.debian.org/efi-team/shim/tree/debian/15+1533136590.3beb971-7/debian/patches
 - [x] any extra patches to grub via your own git tree or as files
https://salsa.debian.org/grub-team/grub/tree/master/debian/patches has the complete list of patches.
 - [x] build logs
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shim_15%2B1533136590.3beb971-7_amd64.log
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shim_15%2B1533136590.3beb971-7_arm64.log
https://github.com/tfheen/shim-review/blob/debian-shim-ia32-x64-aa64-15%2B1533136590.3beb971-4/shim_15%2B1533136590.3beb971-7_i386.log

###### What organization or people are asking to have this signed:
Debian

###### What product or service is this for:
We are a well-known GNU/Linux distribution.

###### What is the origin and full version number of your shim?
https://github.com/rhboot/shim/tree/15 + commits up to https://github.com/rhboot/shim/commit/3beb971b10659cf78144ddc5eeea83501384440c

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Debian is used by lots of people.

###### How do you manage and protect the keys used in your SHIM?
Root CA is sharded between a set of trusted people. Production keys are stored in a HSM.

###### Do you use EV certificates as embedded certificates in the SHIM?
No

###### What is the origin and full version number of your bootloader (GRUB or other)?
grub2 2.02+dfsg1-18

###### If your SHIM launches any other components, please provide further details on what is launched
fwupdate, and it can also launch Linux directly.

###### How do the launched components prevent execution of unauthenticated code?
fwupdate does not launch other code, Linux has secure boot support.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Currently 4.19 with secure boot patches/support.

###### What changes were made since your SHIM was last signed?
Addition of two patches, one of which is a security fix.

###### What is the hash of your final SHIM binary?
SHA256:
```
820513af8d07db0d2401e9899b96a0891fceeb92495edd9c7c40140ef75b21a1  shimia32.efi
a1974739a314a9d40a28d5ad413207dfe7805eb67ccc463dec9a6a98cc6a2442  shimx64.efi
1875a3480d73b354bdf589cef6c673fb9526cdebe87392551d5529c313f5c9c4  shimaa64.efi
```

**Comment by vathpela** [comment]
I've checked over these three builds:
1875a3480d73b354bdf589cef6c673fb9526cdebe87392551d5529c313f5c9c4  shim-review/shimaa64.efi
820513af8d07db0d2401e9899b96a0891fceeb92495edd9c7c40140ef75b21a1  shim-review/shimia32.efi
a1974739a314a9d40a28d5ad413207dfe7805eb67ccc463dec9a6a98cc6a2442  shim-review/shimx64.efi

I can replicate them as expected, and I find their contents acceptable for signing.
