### ISSUE TITLE
Hiddn Security shim x86_64 2019-05-20

### ISSUE THREAD

**Issue by bjornfor** [rhboot/shim-review#68]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
   hiddn-security/shim-review@hiddn-security-shim-x86_64-20190520 ([direct link](https://github.com/hiddn-security/shim-review/tree/hiddn-security-shim-x86_64-20190520))
 - [x] completed README.md file with the necessary information
   https://github.com/hiddn-security/shim-review/blob/hiddn-security-shim-x86_64-20190520/README.md
 - [x] shim.efi to be signed
   https://github.com/hiddn-security/shim-review/blob/hiddn-security-shim-x86_64-20190520/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
   https://github.com/hiddn-security/shim-review/blob/hiddn-security-shim-x86_64-20190520/hiddn-secure-boot.cer
 - [x] any extra patches to shim via your own git tree or as files
   See the ./patches directory in https://github.com/hiddn-security/shim-review/tree/hiddn-security-shim-x86_64-20190520.
 - [x] any extra patches to grub via your own git tree or as files
   No patches.
 - [x] build logs
   https://github.com/hiddn-security/shim-review/blob/hiddn-security-shim-x86_64-20190520/build.log

###### What organization or people are asking to have this signed:
Hiddn Security AS, https://hiddn.no/.

###### What product or service is this for:
HDDs and SSDs with hardware encryption. For example, this product:
https://hiddn.no/products/safedisk/.

###### What is the origin and full version number of your shim?
Version 15 (https://github.com/rhboot/shim/releases/tag/15), plus 3 patches for
reproducible builds. Patch 1 and 2 are backported from master branch, patch 3
is from shim [PR 169](https://github.com/rhboot/shim/pull/169/).

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
We develop and sell secure storage products on the global market that contains
a pre-boot environment for entering a passphrase to unlock/decrypt. This
pre-boot environment is write protected by our custom firmware/hardware.
Currently our customers are forced to disable Secure Boot, or else the pre-boot
environment gets rejected by the UEFI firmware. Neither we nor our customers
want that!

###### How do you manage and protect the keys used in your SHIM?
The keys are stored on an offline PC/network, with strict access rules.

###### Do you use EV certificates as embedded certificates in the SHIM?
No.

###### What is the origin and full version number of your bootloader (GRUB or other)?
grub-2.04-rc1 (94d9926a664014007130796616210b68e421d54a), from
https://git.savannah.gnu.org/git/grub.git. grubx64.efi is built with embedded
grub.cfg file and shim_lock support.

###### If your SHIM launches any other components, please provide further details on what is launched
No other components are launched.

###### How do the launched components prevent execution of unauthenticated code?
No other components are launched.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Linux 4.4.56, from kernel.org. No patches. (Updating to newer longterm kernel
versions are planned.) Secure Boot is enforced by embedding all our user space
in the kernel initramfs and not load any code from outside. (The complete
bzImage/linux.efi image is less than 4 MiB.)

###### What changes were made since your SHIM was last signed?
None. This is our first submission.

###### What is the hash of your final SHIM binary?
```
$ sha256sum ./result/share/shim/15/x64/shimx64.efi
a4d1c9a7a680fcc1a3e73f9ce28a81fce2b82a868beab7d94a769dfcfd0eca09  ./result/share/shim/15/x64/shimx64.efi
```

**Comment by cyphermox** [comment]
I see a number of things in this submission that are worrying me:

- Grub apparently built with no patches -- a number of patches (kept at https://github.com/rhboot/grub2/commits/grub-2.02-sb) are usually included to enfore Secure Boot. Without them, a grub could load any unsigned binary.
- Kernel without patches: there is a generally-accepted patch set for Secure Boot / Lockdown which enforces that only signed modules can be loaded, etc. This does not feel optional, as one could easily load modules or do any number of things using removable storage if things are missing from the initramfs.
- I see no PGP keys for your security contacts. This is important if there is a need to communicate securely about security issues. Your security contacts should have PGP keys, preferrably cross-signed.

I do not think this is ready for signing. Please provide us with a clear plan to remediate the above points.

**Comment by bjornfor** [comment]
Re. grub: I thought those Secure Boot patches were only needed for grub-2.02 (and older). grub-2.04-rc1 has a new "linux" command that seems to obsolete the never-mainlined "linuxefi" command (referred to in the patches you link to). The new grub has shim_lock protocol support. What more is needed before grub master branch has full Secure Boot support and be accepted here? (I'm asking mostly out of curiosity, since using the linked grub-2.02-sb is no problem.)

Re. kernel: Our kernel is built without support for loadable kernel modules. What more do we need to protect against? Do you have a link to the kernel Secure Boot patch set?

Re. PGP keys: Ok, sorry, I didn't think it was a hard requirement, seeing as there is at least one recent submission that was approved without it. I'll see what we can do.

**Comment by bjornfor** [comment]
Uhm, so... $dayjob is bankrupt! That means I won't be following up on this, unfortunately.

But still, I'm quite interested in knowing your response to my questions about grub and kernel (see my previous message).

**Comment by cyphermox** [comment]
Grub now has a shim_lock verifier, but I'm not sure how well it is integrated into everything. I do not believe it completely addresses the same things as what is covered in the patches. See https://github.com/rhboot/grub2/commits/grub-2.02-sb. There are many patches on top of 2.02, some of these are not applied in 2.04.

As for the kernel, the "lockdown" set of patches is not only for loadable modules, but locks down a few other features of a kernel that could be abused to bypass Secure Boot. I am not familiar enough with these patches to tell more; but see https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/linux-fs.git/log/?h=efi-lock-down.

Closing the issue since there's nothing left for us to do. Sorry about how things turned out.

**Comment by bjornfor** [comment]
Thanks for the info.
