### ISSUE TITLE
2017-10-12 EgoSecure

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#7]
Date: Thu, 12 Oct 2017 15:32:48 +0000
From: Alexey Kalgin
Subject: [Shim-review] Full Disk Encryption from EgoSecure - signing required

Dear Colleagues,

EgoSecure is a European-based security vendor specializing on Endpoint Data Security solutions.
We want to support Secure Boot in our Full Disk Encryption product. Please find our submission using this link:
https://egosecure.com/wp-content/uploads/2017/10/submission.tar

Feel free to contact us in case of any questions.

Best regards,
Alexey Kalgin
Head of Product Management

**Comment by vathpela** [comment]
(@cyphermox and @vathpela have both sent emails not in support of signing this.)

**Comment by julian-klode** [comment]
Closing this review requests as it is from before 2019, and likely not valid anymore. Also note that we just added some new questions, and if you submit a new review request with the current question set, also include a Dockerfile to build the shim to not slow down review.
