### ISSUE TITLE
shim-15 for SLES Expanded Support platform 8

### ISSUE THREAD

**Issue by jsegitz** [rhboot/shim-review#73]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/jsegitz/shim-review/tree/SUSE-shim-x86_ia32-20190718

 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

###### What organization or people are asking to have this signed:
SUSE, https://suse.com/

###### What product or service is this for:
SLES Expanded Support platform 8, provided within the
"SUSE Linux Enterprise Server with Expanded Support" program,
https://www.suse.com/products/expandedsupport/

###### What is the origin and full version number of your shim?
The origin is shim-unsigned-x64-15-2.el8 available through https://git.centos.org/rpms/shim-unsigned-x64/tree/c8

Full version number of our shim: 15-2.el8
Source RPM version: shim-unsigned-x64-15-2.el8 (included with the submission)
Tarball sha256sum:
473720200e6dae7cfd3ce7fb27c66367a8d6b08233fe63f01aa1d6b3888deeb6  shim-15.tar.bz2

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
It is a part of a commercial support offering advertised publicly

###### How do you manage and protect the keys used in your SHIM?
The key is installed in a machine with restricted physical and system access.
Shim binaries do not include private portions of the key.

###### What is the origin and full version number of your bootloader (GRUB or other)?
The origin of GRUB is CentOS git: https://git.centos.org/rpms/grub2/tree/c8
Source RPM is included for reference inside extra-srpms.tar: grub2-2.02-66.el8.src.rpm
Full version: grub2-2.02-66.el8

###### If your SHIM launches any other components, please provide further details on what is launched
N/A

###### How do the launched components prevent execution of unauthenticated code?
GRUB and kernel are patched to enforce Secure Boot.

  Secure Boot enforcing is identical to available with grub2 within
  Red Hat Enterprise Linux 8 and (upcoming) CentOS 8, for example:

  https://git.centos.org/rpms/grub2/tree/c8
  0004-Add-secureboot-support-on-efi-chainloader.patch
  0005-Make-any-of-the-loaders-that-link-in-efi-mode-honor-.patch

  Source RPM is included for reference inside extra-srpms.tar: grub2-2.02-66.el8.src.rpm
  https://users.suse.com/~jsegitz/2019.07_sles_es_8_shim_files/extra-srpms.tar

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

No

###### What kernel are you using? Which patches does it include to enforce Secure Boot?

kernel-4.18.0-80.el8 with lockdown patches identical to the one of Red Hat Enterprise
Linux 8 and (upcoming) CentOS 8, available through CentOS git: https://git.centos.org/rpms/kernel/tree/c8

Source RPM is included for reference inside extra-srpms.tar: kernel-4.18.0-80.el8.src.rpm.
https://users.suse.com/~jsegitz/2019.07_sles_es_8_shim_files/extra-srpms.tar

###### What changes were made since your SHIM was last signed?

Bug fixes have been applied by Red Hat and CentOS:

- Added 0005-MokListRT-Fatal.patch to avoid crashing legacy uefi/non SB machines (from CentOS, 1 patch)
- Fix MoK mirroring issue which breaks kdump without intervention (from shim-16, 4 patches)

###### What is the hash of your final SHIM binary?

shimia32.efi
sha256sum: ed85836835ba3ae06147ef6eb12fa575d45bd0a681be8607ef15fceb744f7edf
hash: 3ad55a88e2a6f564e4bdf281b0089eed83ecc03767448aed577788f3aea0057e

shimx64.efi
sha256sum: d12af14cec64b2373247e1c7b7fd9afd9ef0427c4989bbc9e962e271bbfe5398
hash: 8e5b63b89bfe84a922f655e4f835cb4a7baa4a46c2d8546ece0ed5a3efc33e0c

**Comment by AlexeyPetrenkoOracle** [comment]
It's four months since this review request was submitted without any progress.
This process is clearly dysfunctional and puts all Linux distributions at a serious security risk

**Comment by jsegitz** [comment]
yes, the process is really slow. As far as I understand it, this is done by volunteers. SUSE could help out a bit with the reviews here, but this would only help in a very limited way (currently 56 requests open) and also it smells a bit like conflict of interest if we review other peoples request to get our own requests reviewed ...

**Comment by AlexeyPetrenkoOracle** [comment]
Absolutely. Oracle could help with the reviews too.
I'd say it will smell like collaboration as we all do in open source :)

**Comment by jsegitz** [comment]
@cyphermox @vathpela @nicholasbishop who set up the original list of reviewers? Can additional reviewers be added easily to speed up reviews here?

**Comment by nicholasbishop** [comment]
I think I'm mistagged in the above comment, I am not a reviewer.

**Comment by cyphermox** [comment]
I've attempted to rebuild this binary, but I'm getting something very different. Using the chroot is also a little weird (just like using any other kind of premade tarball) because one can't make sure the build environment wasn't tempered with.

In any case, right now I can't reproduce the same binary. Could you please have a try and tell me if it's just been too long since the submission and now some part of the toolchain gets downloaded and is different?

**Comment by cyphermox** [comment]
To answer the question, yes, reviewers can be added; but there isn't a list per se. We just need people willing to do the work, and hopefully cross-review so people aren't approving their own.

**Comment by jsegitz** [comment]
that's strange, I also get different results. I need to look into this. Due to the chroot we should be using a stable toolchain.

**Comment by jsegitz** [comment]
Sorry for the delay, I was away for a week. Turns out that building in chroot doesn't isolate the build sufficiently. So we switched it to using a container. I updated the files, here is the updated issue checklist:

###### What organization or people are asking to have this signed:
SUSE, https://suse.com/

###### What product or service is this for:
SLES Expanded Support platform 8, provided within the
"SUSE Linux Enterprise Server with Expanded Support" program,
https://www.suse.com/products/expandedsupport/

###### What is the origin and full version number of your shim?
The origin is shim-unsigned-x64-15-2.el8 available through https://git.centos.org/rpms/shim-unsigned-x64/tree/c8

Full version number of our shim: 15-2.el8
Source RPM version: shim-unsigned-x64-15-2.el8 (included with the submission)
Tarball sha256sum:
473720200e6dae7cfd3ce7fb27c66367a8d6b08233fe63f01aa1d6b3888deeb6  shim-15.tar.bz2

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
It is a part of a commercial support offering advertised publicly

###### How do you manage and protect the keys used in your SHIM?
The key is installed in a machine with restricted physical and system access.
Shim binaries do not include private portions of the key.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes

###### What is the origin and full version number of your bootloader (GRUB or other)?
The origin of GRUB is CentOS git: https://git.centos.org/rpms/grub2/tree/c8
Source RPM is included for reference inside extra-srpms.tar: grub2-2.02-66.el8.src.rpm
Full version: grub2-2.02-66.el8

###### If your SHIM launches any other components, please provide further details on what is launched
N/A

###### How do the launched components prevent execution of unauthenticated code?
GRUB and kernel are patched to enforce Secure Boot.

  Secure Boot enforcing is identical to available with grub2 within
  Red Hat Enterprise Linux 8 and (upcoming) CentOS 8, for example:

  https://git.centos.org/rpms/grub2/tree/c8
  0004-Add-secureboot-support-on-efi-chainloader.patch
  0005-Make-any-of-the-loaders-that-link-in-efi-mode-honor-.patch

  Source RPM is included for reference inside extra-srpms.tar: grub2-2.02-66.el8.src.rpm
  https://users.suse.com/~jsegitz/2019.11_sles_es_8_shim_files/extra-srpms.tar

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?

No

###### What kernel are you using? Which patches does it include to enforce Secure Boot?

kernel-4.18.0-80.el8 with lockdown patches identical to the one of Red Hat Enterprise
Linux 8 and (upcoming) CentOS 8, available through CentOS git: https://git.centos.org/rpms/kernel/tree/c8

Source RPM is included for reference inside extra-srpms.tar: kernel-4.18.0-80.el8.src.rpm.
https://users.suse.com/~jsegitz/2019.11_sles_es_8_shim_files/extra-srpms.tar

###### What changes were made since your SHIM was last signed?

This is the initial submission for SLES Expanded Support platform 8.
On top of shim-15, bug fixes have been applied:

- Added 0005-MokListRT-Fatal.patch to avoid crashing legacy uefi/non SB machines (from CentOS, 1 patch)
- Fix MoK mirroring issue which breaks kdump without intervention (from shim-16, 4 patches)

###### What is the hash of your final SHIM binary?

shimia32.efi
hash: b01e4a766aab3be21fb0ad2bfd5b96f98031c66820adaee6a0f3b164b8e081bd
sha256sum: 195041f62e012e62f662b1f77b46e3872d42f659d7b060cf51270d63e078d9c1

shimx64.efi
hash: d66630ec3724ff50d535c468d6dd176a0b307bcc9da85e51f81580894e0c0048
sha256sum: 1877b7ec331978a0a79e350f6011fe2f4eb7cc3097642cc3ab9a0db3f6a6c2b8

**Comment by YustasSwamp** [comment]
This build is reproducible. No issues.

I find this shim acceptable for signing:
```
[sandman@130fc806ba58 x86_64]$ sha256sum usr/share/shim/15-2.el8/ia32/shimia32.efi
195041f62e012e62f662b1f77b46e3872d42f659d7b060cf51270d63e078d9c1  usr/share/shim/15-2.el8/ia32/shimia32.efi
[sandman@130fc806ba58 x86_64]$ sha256sum usr/share/shim/15-2.el8/x64/shimx64.efi
1877b7ec331978a0a79e350f6011fe2f4eb7cc3097642cc3ab9a0db3f6a6c2b8  usr/share/shim/15-2.el8/x64/shimx64.efi
```

**Comment by julian-klode** [comment]
This request seems to have been superseded by a private review in keybase during the boothole review process.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
