### ISSUE TITLE
Nutanix-shim-x86_64-20190820

### ISSUE THREAD

**Issue by piyushmittalntnx** [rhboot/shim-review#76]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/piyushmittalntnx/shim-review/tree/Nutanix-shim-x86_64-20190820
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

###### What organization or people are asking to have this signed:
`Nutanix Inc (https://www.nutanix.com)`

###### What product or service is this for:
`Nutanix AHV (https://www.nutanix.com/products/acropolis/virtualization)`

###### What is the origin and full version number of your shim?
`https://github.com/rhboot/shim/releases/tag/15`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
`Nutanix AHV is used by Nutanix customers on baremetal servers. We are planning to enable secureboot for AHV by following (shim -> grub2 -> kernel) path. It needs to be signed so that any servers using UEFI CA can boot Nutanix AHV.`

###### How do you manage and protect the keys used in your SHIM?
`Keys are stored in protected storage accessible to only the security team and selected build engineers. Usage is audited and alerted.`

###### Do you use EV certificates as embedded certificates in the SHIM?
`No`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`grub2 2.02-0.76.el7`

###### If your SHIM launches any other components, please provide further details on what is launched
`N/A`

###### How do the launched components prevent execution of unauthenticated code?
`We are using rhboot shim and gnu grub2 2.02 both of which enforce secure boot`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`No`

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
`We are using linux-4.19.z with secure boot patches/support.`

###### What changes were made since your SHIM was last signed?
`N/A`

###### What is the hash of your final SHIM binary?
`bbd8e01e9ec9de8a6977c9622045784a273ae3d33439f40446cff54e3ec23f62 shimx64.efi`

**Comment by piyushmittalntnx** [comment]
Hello @vathpela, could you please let us know if the above information looks good. What's the timeline for this review process?

**Comment by cyphermox** [comment]
I have reviewed this but I am unable to reproduce the same binary. There appears to be differences in the section sizes and in various parts of the code. Could you please advise?

The only thing listed in the build instructions is gnu-efi specifically; but the version of binutils used does matter.

**Comment by YustasSwamp** [comment]
Reviewed too. Unable to reproduce.
Advice: avoid using `yum install/groupinstall` as it might bring different toolchains version over the time, so output binary may differ.
Please, use image with preinstalled tools.

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
