### ISSUE TITLE
Xdja_Jinshi-shim-x86_64-20190903

### ISSUE THREAD

**Issue by xdja** [rhboot/shim-review#77]
Make sure you have provided the following information:

 - [X] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
       https://github.com/xdja/Jinshi_shim_review/tree/master/shim-master
 - [X] completed README.md file with the necessary information
https://github.com/xdja/Jinshi_shim_review/blob/master/README.md
 - [X] shim.efi to be signed
https://github.com/xdja/Jinshi_shim_review/blob/master/shimx64.efi
 - [X] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/xdja/Jinshi_shim_review/blob/master/xdja_jinshi.cer
 - [X] any extra patches to shim via your own git tree or as files
None
 - [X] any extra patches to grub via your own git tree or as files
None
 - [X] build logs
https://github.com/xdja/Jinshi_shim_review/blob/master/build.log

###### What organization or people are asking to have this signed:
- 郑州信大捷安信息技术股份有限公司(Zhengzhou Xindajiean Information Technology Co.,Lt)(www.xdja.com)
- Zhengzhou, HeNan, China
- Xindajiean established in 2004, which is a Hi-Tech Enterprise professional on designing Security Chip innovatly, Cloud Security Service Platform R&D, Embed-OS R&D, and providing Mobile&IoT Security Service Safeguard.
- President: Xiantong Ma

###### What product or service is this for:
- JinShi Desktop OS is a U-Disk security OS based on Ubuntu, which runs in USB device isolately to avoid destroying the data in local storage.

###### What is the origin and full version number of your shim?
- https://github.com/rhboot/shim/tree/15
- Version: 15

###### Microsoft Submission ID?
- 14334151916716398   shimx64.cab

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
- Jinshi is a customer-oriented linux-based security OS, only running normally in secure-boot-enable status on any AMD64 device, through which to avoid the hidden danger when customer disable secure boot.
- sequence of booting: shim->grub2->kernel.
- Jinshi would like customers to be able to run Jinshi’s Linux-based system on any amd64(64Bit) device without disabling Secure Boot.

###### How do you manage and protect the keys used in your SHIM?
- The key is stored in the server with restricted physical and system access needed

###### Do you use EV certificates as embedded certificates in the SHIM?
- No, they're generated by the XDJA's jinshi Security team.

###### What is the origin and full version number of your bootloader (GRUB or other)?
- It's grub2-2.02-2ubuntu8.13 , which has the normal complement of secure boot patches plus from Ubuntu.
- http://cn.archive.ubuntu.com/ubuntu/pool/universe/g/grub2/grub2_2.02-2ubuntu8.13_amd64.deb

###### If your SHIM launches any other components, please provide further details on what is launched
- N/A

###### How do the launched components prevent execution of unauthenticated code?
- They don't launch other code.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
- No.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
- grub2:
    http://cn.archive.ubuntu.com/ubuntu/pool/universe/g/grub2/grub2_2.02-2ubuntu8.13_amd64.deb
    No extra patches
- kernel:
    linux-source-5.0.0
    http://cn.archive.ubuntu.com/ubuntu/pool/main/l/linux-hwe/linux-source-5.0.0_5.0.0-27.28~18.04.1_all.deb
    there is no modification on kernal, only modify the config file compiling the kernal ,disable the nvme and SATA driver.

###### What changes were made since your SHIM was last signed?
- No

###### What is the hash of your final SHIM binary?
- a33fbf08dba848ef57377cfb330381b2a700698eee7704841f5a6d4f6717003c  shimx64.efi

**Comment by haobinnan** [comment]
Linux内核默认没有包含安全启动补丁，需要将安全启动补丁加入到你的Linux内核中，否则无法启动。

**Comment by xdja** [comment]
@haobinnan  We kernal is download from ubuntu ,so the kernel is already patched.

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
