### ISSUE TITLE
2017-08-03 WhiteCanyon

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#8]
Date: Mon, 11 Sep 2017 13:18:55 -0600
From: Daniel Pedigo
Subject: [Shim-review] RESEND: WhiteCanyon Shim Review

This is being resubmitted due to a lack of response to our original
submission on 8/3.

Hi all,
We were unaware of this review process and as such were directed here by
Microsoft after submitting our shim.
The linked tarball has a readme with answers to the questions we found
listed here: https://pjones.fedorapeople.org/shim-signing-procedure.html.
Shims: https://orem.whitecanyon.com/downloads/dev/shims.tar.gz
Let me know if we've missed anything.

**Comment by julian-klode** [comment]
Closing this review requests as it is from before 2019, and likely not valid anymore. Also note that we just added some new questions, and if you submit a new review request with the current question set, also include a Dockerfile to build the shim to not slow down review.
