### ISSUE TITLE
shim-15 for Evimetry 3.2.4.1

### ISSUE THREAD

**Issue by blschatz** [rhboot/shim-review#80]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 https://github.com/evimetry/shim-review/tree/schatzforensic-shim-ia32-x64-20191219
 - [x] completed README.md file with the necessary information
 https://github.com/evimetry/shim-review/blob/schatzforensic-shim-ia32-x64-20191219/README.md
 - [x] shim.efi to be signed
 https://github.com/evimetry/shim-review/blob/schatzforensic-shim-ia32-x64-20191219/shimia32.efi
 https://github.com/evimetry/shim-review/blob/schatzforensic-shim-ia32-x64-20191219/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 https://github.com/evimetry/shim-review/blob/schatzforensic-shim-ia32-x64-20191219/sf-secureboot-signing.der
 - [x] any extra patches to shim via your own git tree or as files
Patches copied from https://github.com/rhboot/shim-review/issues/82 and included in source.
 - [x] any extra patches to grub via your own git tree or as files
 See README.md
 - [x] build logs
https://github.com/evimetry/shim-review/blob/schatzforensic-shim-ia32-x64-20191219/build.log

###### What organization or people are asking to have this signed:
Schatz Forensic Pty. Ltd. 
https://schatzforensic.com

###### What product or service is this for:
Evimetry Deadboot v3.2.4.1 
https://evimetry.com/evimetry-imager/

###### What is the origin and full version number of your shim?
Exactly the same as https://github.com/rhboot/shim-review/issues/82 :
From github.com/rhboot/shim; a snapshot from current master:
rhboot/shim@a4a1fbe + patches documented in README.md

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Our linux-based forensic OS is used for forensics on bare-metal 
laptops, servers, and virtual computers. This includes both x64 and ia32 based 
secure boot, in addition to earlier BIOS/CSM and non-SecureBoot UEFI. 

Our kernel includes out of mainline patches supporting write blocking (preventing writes), which necessitate a custom signed kernel, and onwards a shim.

###### How do you manage and protect the keys used in your SHIM?
Key material stored in an offline HSM.

###### Do you use EV certificates as embedded certificates in the SHIM?
No.

###### What is the origin and full version number of your bootloader (GRUB or other)?
Grub 2.04 https://ftp.gnu.org/gnu/grub/grub-2.04.tar.gz + 
current Debian patches https://salsa.debian.org/grub-team/grub/tree/master/debian/patches

The patches are identical to those approved in https://github.com/rhboot/shim-review/issues/67

###### If your SHIM launches any other components, please provide further details on what is launched
Only the above Grub is launched. 

###### How do the launched components prevent execution of unauthenticated code?
The above Grub includes the right patches to prevent unauthenticated execution of 
unsigned kernels. 

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Our kernel is based off Debian's 4.19.67-2 kernel, which includes the Lockdown patches. 

###### What changes were made since your SHIM was last signed?
First time signing.

###### What is the hash of your final SHIM binary?
268f85f2397ec6aa294eed5f628babc1279b553e0fc8c597062dca4602eba77f  shimia32.efi
db25d0f9cdc7e5ca7540f9bae0258466bdd96650e45bc097aa36675371214675  shimx64.efi

**Comment by blschatz** [comment]
Hi @cyphermox: We are now using your exact shim source and Docker based build approach. Would you please let us know if there is anything else that we could do to make the review job easier?

**Comment by jrpark-lge** [comment]
@blschatz, I reproduced the build with provided Dockerfile, and the built shim is identical to the submission.

However, I found some issues:
1. tag schatzforensic-shim-ia32-x64-20190926 does not point your latest commit
2. Line 18 of your Dockerfile produces following error: 
`Step 17/20 : RUN cat /build/tpm-correctness-2 | patch -p1`
`cat: /build/tpm-correctness-2: No such file or directory`
 therefore, tpm-coreectness-2.patch will not be applied.
3. patch tpm-correctness-3.patch is not used anywhere in your Dockerfile

**Comment by blschatz** [comment]
@jrpark-lge : Thanks for reviewing and identifying the issues.

I fixed the following:
1. Dockerfile applies the tpm-correctness-3.patch file (typo)
2. Newly resulting shim binaries updated.
3. Hashes of new shim binaries updated.
4. Tagged as schatzforensic-shim-ia32-x64-20191219

Can I trouble you to re-review? 
Thanks!

**Comment by jrpark-lge** [comment]
@blschatz, No problem!

I reviewed your updates and the build was successful with all patches applied.
I can confirm that reproduced shims are identical to your submission.

**Comment by blschatz** [comment]
Thanks @jrpark-lge  !

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
