### ISSUE TITLE
shim-15-ia32 amd amd64 for FixMeStick

### ISSUE THREAD

**Issue by coreyvelan** [rhboot/shim-review#81]
- [X] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
coreyvelan/shim-review@fixmestick-shim-ia32-x64-20191021
 - [X] completed README.md file with the necessary information
https://github.com/coreyvelan/shim-review/blob/fixmestick-shim-ia32-x64-20191021/README.md
 - [X] shim.efi to be signed
https://github.com/coreyvelan/shim-review/blob/fixmestick-shim-ia32-x64-20191021/shimx64.efi
https://github.com/coreyvelan/shim-review/blob/fixmestick-shim-ia32-x64-20191021/shimia32.efi
 - [X] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/coreyvelan/shim-review/blob/fixmestick-shim-ia32-x64-20191021/fixmestick-codesigning.cer
 - [x] any extra patches to shim via your own git tree or as files
None 
 - [X] any extra patches to grub via your own git tree or as files
None
 - [X] build logs
https://github.com/coreyvelan/shim-review/blob/fixmestick-shim-ia32-x64-20191021/build.log

###### What organization or people are asking to have this signed:
FixMeStick Technologies Inc. (https://www.fixmestick.com)

###### What product or service is this for:
FixMeStick Virus Removal Device (https://www.fixmestick.com/fixmestick/)

###### What is the origin and full version number of your shim?
https://github.com/rhboot/shim/ - Latest commits up to 15-Mar-2019 (a4a1fbe728c9545fc5647129df0cf1593b953bec)

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
FixMeStick wants to employ Secure Boot for building a trusted operating system from Shim to GRUB to the kernel to kernel modules. FixMeStick is a bootable linux OS that mounts local drives, and then scans and removes malware.

###### How do you manage and protect the keys used in your SHIM?
The private key is stored on a hardware token issued by DigiCert.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes.  The shim has the public key of the EV Code Signing key pair (issued by DigiCert).

###### What is the origin and full version number of your bootloader (GRUB or other)?
Grub 2.04 https://ftp.gnu.org/gnu/grub/grub-2.04.tar.gz +
current Debian patches https://salsa.debian.org/grub-team/grub/tree/master/debian/patches

###### If your SHIM launches any other components, please provide further details on what is launched
Our shim only launches GRUB and MokManager

###### How do the launched components prevent execution of unauthenticated code?
n/a

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
Shim only launches GRUB and MokManager, both of which must be signed by the appropriate CV code signing key.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Linux 5.2 with SecureBoot support.

###### What changes were made since your SHIM was last signed?
This is our first submission

###### What is the hash of your final SHIM binary?
9fc2cc4c596a1cf42e68e8ec70199dada7ca568a59f7567283f4e1975bd86d44  shimia32.efi
0b29eb3574fe540f5bb87358226d380fa6f80a59382cc072365e59c0670b90b1  shimx64.efi

**Comment by coreyvelan** [comment]
Hi- I'm following up on this.  Is this still the correct place to get reviewed? It looks like this hasn't been touched since October.

Thanks,
Corey

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
