### ISSUE TITLE
shim 15+1552672080.a4a1fbe-0ubuntu1 for Ubuntu

### ISSUE THREAD

**Issue by cyphermox** [rhboot/shim-review#82]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs

Our submission tree is at: https://github.com/CanonicalLtd/shim-review

###### What organization or people are asking to have this signed:
Canonical Ltd.

###### What product or service is this for:
Ubuntu

###### What is the origin and full version number of your shim?
From github.com/rhboot/shim; a snapshot from current master:
https://github.com/rhboot/shim/commit/a4a1fbe

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Previous Ubuntu shims are signed; now this newer snapshot fixes some bugs since the previous snapshot (https://github.com/rhboot/shim/commit/3beb971b10659cf78144ddc5eeea83501384440c), and adds a couple of patches for bugs fixed in Github issues but not yet integrated in the git tree.

###### How do you manage and protect the keys used in your SHIM?
The key used in our shim is an offline CA key which is only used for signing
operational keys.  Certificate signing is always done from a machine booted
from read-only media, not connected to the Internet.  The private key
information is distributed among designated trusted employees using a Galois
field, which requires that multiple employees be present in order to
reconstitute the private key for use and ensures that an attacker who
managed to gain possession of anything less than the defined number of key
shares would have zero information about the private key.

###### Do you use EV certificates as embedded certificates in the SHIM?
No.

###### What is the origin and full version number of your bootloader (GRUB or other)?
GRUB `2.04-1ubuntu12`, from `https://git.launchpad.net/~ubuntu-core-dev/grub/+git/ubuntu/log/?h=ubuntu`

###### If your SHIM launches any other components, please provide further details on what is launched
Does not load other components.

###### How do the launched components prevent execution of unauthenticated code?
GRUB enforces Secure Boot, using the accepted patches (see github.com/rhboot/grub2); fallback.efi and MokManager are shim components that enforce authenticated code already.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
GRUB bootloaders of previous supported releases of Ubuntu currently still support loading unsigned kernels, on 14.04 and 16.04. The process to remove those is still in progress.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Varying Linux kernel versions; see https://launchpad.net/ubuntu/+source/linux (series 5.3 on 19.10, 5.0 on Ubuntu 19.04, 4.15 on 16.04, etc.) all with lockdown patches applied.

###### What changes were made since your SHIM was last signed?
```
a4a1fbe (HEAD -> master, origin/master, origin/HEAD) Once again, try even harder to get binaries without timestamps in them.
20e731f VLogError(): Avoid NULL pointer dereferences in (V)Sprint calls
cd20ce4 mok: fix missing closing brace in maybe_mirror_one_mok_variable
da62845 fallback: show a countdown menu before reset
81512ea console: Move the countdown function to console.c
8733e2c Remove my .syntastic_c_config, it doesn't belong in the repo.
0a53ee5 Ignore *.hash
741c61a Make EFI variable copying fatal only on secureboot enabled systems
fd7c3bd Remove call to TPM2 get_event_log()
617b900 mok: minor cleanups
aecbe1f mok: also mirror the build cert to MokListRT
4e2d62f shim: only include shim_cert.h in shim.c
29c1148 mok: consolidate mirroring code in a helper instead of using goto
4b27ae0 mok: fix the mirroring of RT variables
9ab0d79 Make sure that MOK variables always get mirrored
cb83c14 Cryptlib: fix build on 32bit ARM
41b9335 Make.default: use correct flags to disable unaligned access for 32 bit ARM
be35276 Makefile: do not run git on clean if there's no .git directory
e9f67aa Fix apparent typo in ARM 32-on-64 code
b3e4d1f Make update.sh use git am
6df7a8f Fix for "Section 0 has negative size" error when loading fbaa64.efi
e563bc3 shim: Prevent shim to set itself as a second stage loader
a625fa5 shim: Properly generate absolute paths from relative image paths
39b8345 Fix the compile error of mkdir wrong directory.
2d0d941 Add mm/fb hashing to TODO, put that and related things under 'Reproducible builds'
```

With the addition of patches:
```
Fix-OBJ_create-to-tolerate-a-NULL-sn-and-ln.patch
MokManager-hidpi-support.patch 
MokManager-avoid-unaligned.patch
tpm-correctness-1.patch
tpm-correctness-2.patch
tpm-correctness-3.patch
```

Please see the patches included in the review git tree; they include rationale.

###### What is the hash of your final SHIM binary?
```
ce7a0a3d718747c7263d099fd1477e363ecfe75bd2f639ee47ac1271ec229d80  shimx64.efi
b6f807d4488f132ab873dcde8edad2875961895e503f263b86ba34958a290618  shimaa64.efi
```

**Comment by martinezjavier** [comment]
I've reviewed the shim and grub patches on this submission and all of them look correct to me.

Also building using the provided Dockerfile generates the expected binaries. I think this shim is acceptable for signing.
