### ISSUE TITLE
shim-15 for LG thin client OS

### ISSUE THREAD

**Issue by jrpark-lge** [rhboot/shim-review#85]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
[jrpark-lge/shim-review@lge-shim-x64-20191122](https://github.com/jrpark-lge/shim-review/tree/lge-shim-x64-20191122)
 - [x] completed README.md file with the necessary information
`https://github.com/jrpark-lge/shim-review/blob/lge-shim-x64-20191122/README.md`
 - [x] shim.efi to be signed
`https://github.com/jrpark-lge/shim-review/blob/master/shimx64.efi`
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
`https://github.com/jrpark-lge/shim-review/blob/master/cert.der`
 - [x] any extra patches to shim via your own git tree or as files
 - [x] any extra patches to grub via your own git tree or as files
 - [x] build logs
`https://github.com/jrpark-lge/shim-review/blob/lge-shim-x64-20191122/build-log-shimx64.txt`

###### What organization or people are asking to have this signed:
LG Electronics, Inc.

###### What product or service is this for:
LGE's Thin client OS for LGE or third-party thin client devices and PCs

###### What is the origin and full version number of your shim?
Shim 15 from commit https://github.com/rhboot/shim/commit/a4a1fbe728c9545fc5647129df0cf1593b953bec

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
We want our linux-based thin client OS to be installed on any systems with secure boot support. The systems includes our/third-party thin client products and PCs: our thin client OS is not only for LGE devices, but for the devices customers are using. They should be able to operate our linux thin client OS protected by secure boot.

###### How do you manage and protect the keys used in your SHIM?
It is stored in HSM in highly secured area and only some of trusted administrators can access it.

###### Do you use EV certificates as embedded certificates in the SHIM?
Yes.

###### What is the origin and full version number of your bootloader (GRUB or other)?
We are using grub2, from ubuntu: https://git.launchpad.net/ubuntu/+source/grub2/tag/?h=applied/2.02-2ubuntu8.13
Version is 2.02-2ubuntu8.13

###### If your SHIM launches any other components, please provide further details on what is launched
Our shim does not launch any other components. 

###### How do the launched components prevent execution of unauthenticated code?
Shim launches grub2 and it does not allow unauthenticated codes to be executed.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Linux kernel 4.18 with lockdown patches applied.

###### What changes were made since your SHIM was last signed?
This is our first shim review request.

###### What is the hash of your final SHIM binary?
099855ee14d502bebcd5d7b877802c6613eb87e80ebfbe22dead5178c90c63d0 shimx64.efi

**Comment by blschatz** [comment]
I have reproduced the build using the Dockerfile and confirmed that the built shim matches the one in the review request. Also reviewed the Dockerfile for correctness and confirmed that the build is using only the indicated shim commit.

@jpark-lge - this would have been easier to reproduce if you added the following lines to your Dockerfile:
RUN sha256sum shim-review/shimx64.efi
RUN sha256sum shim/shimx64.efi

**Comment by jrpark-lge** [comment]
@blschatz, thank you for your review, I really appreciate it.
You're right, I forgot there was sha-256 hash in submission template.
I added those two lines to our Dockerfile, commit [a3141](https://github.com/jrpark-lge/shim-review/commit/a3141330a10100843a4d89150d610018fd726c2b).
If there are no other issues, could you please approve our shim?

**Comment by blschatz** [comment]
@jrpark-lge: I don't have the permissions to approve submissions. 

I reviewed yours to help lighten the load on the acceptance team, who appear to be @cyphermox @vathpela @steve-mcintyre @martinezjavier.

**Comment by jrpark-lge** [comment]
@blschatz, I didn't know that but thanks for your help anyways!

@cyphermox @vathpela @steve-mcintyre @marinez,
Could you please crosscheck our submission?

**Comment by blschatz** [comment]
@jrpark-lge : perhaps you could independently review my submission to lighten the load on the acceptance team.

**Comment by jrpark-lge** [comment]
@blschatz, sorry for the delay, I was not in the office. I will review yours soon.

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
