### ISSUE TITLE
2017-11-02 Blancco

### ISSUE THREAD

**Issue by vathpela** [rhboot/shim-review#9]
Date: Thu, 2 Nov 2017 13:26:05 +0000
From: Victor Gonzalo
Subject: [Shim-review] Blancco Technology Group shim review request     (Submission ID: 1965978)

Hi
We are adding secure boot support. In order (naively ;)) to speed up the review processes
we took the shim and grub2 sources from Red Hat github repositories and submitted the
shim binary with our certificate to MS for signing.
A couple of days ago I was accepted into this mailing list. We have prepared the review
material in a tarball that can be found here:
http://download.blancco.com/downloads/blancco_shim_review/blancco_shim_review.tar.xz
Some of it is missing, as we didn't know about this by then, but I'd be happy to answer any
question that may arise.

Thanks a lot

-Víctor Gonzalo
Senior Software Engineer - Blancco Technology Group

**Comment by cyphermox** [comment]
This looks tentatively good once I was able to set up a proper ArchLinux vm.

Their public cert is missing for the build.

**Comment by cyphermox** [comment]
cert was not missing, I just didn't see it.

ab22ee7d8fd3ce31ee37bc480a535177ec9b22420bd60462a87e1863e76adbb5  is acceptable for signing.
