### ISSUE TITLE
SHIM 15 TrulyProtect Thin hypervisor SHIM

### ISSUE THREAD

**Issue by asafal** [rhboot/shim-review#90]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/asafal/shim-review
 - [x] completed README.md file with the necessary information
 - [x] shim.efi to be signed
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
tp.cer
 - [X] any extra patches to shim via your own git tree or as files
none
 - [X] any extra patches to grub via your own git tree or as files
none
 - [X] build logs
build.logs

###### What organization or people are asking to have this signed:
TrulyProtect

###### What product or service is this for:
The shim will load our secure thin hypervisor which builds a secure execution environment,
used to support our products.
TrulyProtect Execution Protection - Endpoint security product 
TrulyProtect Native Decryption - Software encryption product

###### What is the origin and full version number of your shim?
`based on Tag 15 of shim:
51413d1deb0df0debdf1d208723131ff0e36d3a3`

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
We have clients who wish to install our product on physical machines currently using secure-boot, we do not wish to disable secure boot on these machines in order to get our product running

###### How do you manage and protect the keys used in your SHIM?
`Our keys are stored on a hardware token, access to the token is limited to the people listed above.`

###### Do you use EV certificates as embedded certificates in the SHIM?
`Yes, we have an EV Code signing certificate issued by Sectigo (COMOD)`

###### What is the origin and full version number of your bootloader (GRUB or other)?
`Our entire product is the bootloader itself it is self-contained within a single EFI file`

###### If your SHIM launches any other components, please provide further details on what is launched
`Once our product is initialized it will launch Microsoft windows only, or known linux distros such as ubuntu, red hat, centos, etc..., it does so using EFI services and therefore preserving the secure environment.`

###### How do the launched components prevent the execution of the unauthenticated code?
`When we use EFI's LoadImage and StartImage  functionalities to load an existing OS EFI image since we use built-in EFI functions, no unauthorized code can execute.`

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
`No`

###### What kernel are you using? Which patches does it include to enforce Secure Boot?
`No Linux kernel is used`

###### What changes were made since your SHIM was last signed?
`None`

###### What is the hash of your final SHIM binary?
`sha256: de5e86e06c6934478a02e5251df5153492804730cc74f18739c19aec604dbe8f

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
