### ISSUE TITLE
Shim 15 for UOS

### ISSUE THREAD

**Issue by izshtar** [rhboot/shim-review#94]
Make sure you have provided the following information:

 - [*] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
https://github.com/izshtar/shim-review
 - [*] completed README.md file with the necessary information
https://github.com/izshtar/shim-review/tree/uos-shim-x64-20200407/README.md
 - [*] shim.efi to be signed
https://github.com/izshtar/shim-review/tree/uos-shim-x64-20200407/shimx64.efi
 - [*] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
https://github.com/izshtar/shim-review/tree/uos-shim-x64-20200407/uos-uefi-ca.der
 - [*] any extra patches to shim via your own git tree or as files
https://github.com/izshtar/shim-review/tree/uos-shim-x64-20200407/gcc-9-fix.patch
 - [*] any extra patches to grub via your own git tree or as files
None
 - [*] build logs
https://github.com/izshtar/shim-review/tree/uos-shim-x64-20200407/shim-15.g51413d1-7_amd64.log

###### What organization or people are asking to have this signed:
UOS(https://chinauos.com)

###### What product or service is this for:
UOS GNU/Linux

###### What is the origin and full version number of your shim?
shim-15

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
UOS is a linux distribution based on Debian, which need running normally in secure-boot-enable status on any AMD64 device, 
through which to avoid the hidden danger when customer disable secure boot.

###### How do you manage and protect the keys used in your SHIM?
It is stored in HSM in highly secured area.

###### Do you use EV certificates as embedded certificates in the SHIM?
No.

###### What is the origin and full version number of your bootloader (GRUB or other)?
grub 2.02+dfsg1-20

###### If your SHIM launches any other components, please provide further details on what is launched
None

###### How do the launched components prevent execution of unauthenticated code?
Shim launches grub2 and it does not allow unauthenticated codes to be executed.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
Currently 4.19 with secure boot patches/support.

###### What changes were made since your SHIM was last signed?
This is our first shim review request.

###### What is the hash of your final SHIM binary?
fdb7d9e869ddd9128260cddc9a295fc9184dfd98b9530ef748f933172967b560  shimx64.efi

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
