### ISSUE TITLE
SHIM 15 for Deepin

### ISSUE THREAD

**Issue by nohappiness** [rhboot/shim-review#96]
Make sure you have provided the following information:

 - [x] link to your code branch cloned from rhboot/shim-review in the form user/repo@tag
        [nohappiness/shim-review@deepin-shim-x64-20200609](https://github.com/nohappiness/shim-review/tree/deepin-shim-x64-20200609)
 - [x] completed README.md file with the necessary information
        https://github.com/nohappiness/shim-review/blob/deepin-shim-x64-20200609/README.md
 - [x] shim.efi to be signed
        https://github.com/nohappiness/shim-review/blob/deepin-shim-x64-20200609/shimx64.efi
 - [x] public portion of your certificate embedded in shim (the file passed to VENDOR_CERT_FILE)
        https://github.com/nohappiness/shim/blob/15-1/deepin.cert.der
 - [x] any extra patches to shim via your own git tree or as files
        N/A
 - [x] any extra patches to grub via your own git tree or as files
        N/A
 - [x] build logs
        https://github.com/nohappiness/shim-review/blob/deepin-shim-x64-20200609/build.log.20200609

###### What organization or people are asking to have this signed:
Deepin: https://www.deepin.org/en/

###### What product or service is this for:
Deepin V20.

###### What is the origin and full version number of your shim?
shim-15

###### What's the justification that this really does need to be signed for the whole world to be able to boot it:
Deepin is yet another linux distribution based on Debian GNU/Linux. It has been actively maintained since 2011. Deepin has kept in the top 20 on distrowatch for last few years. It is an amazing distribution, and for compatible reason, we here submit our siging request for shim.

###### How do you manage and protect the keys used in your SHIM?
The key is stored in isolated standalone server which is placed in secure area with limited access.

###### Do you use EV certificates as embedded certificates in the SHIM?
No.

###### What is the origin and full version number of your bootloader (GRUB or other)?
GRUB2: 2.02.9.1

###### If your SHIM launches any other components, please provide further details on what is launched
None.

###### How do the launched components prevent execution of unauthenticated code?
Our shim only launches grub2 which with secure-boot support.

###### Does your SHIM load any loaders that support loading unsigned kernels (e.g. GRUB)?
No.

###### What kernel are you using? Which patches does it includes to enforce Secure Boot?
5.3.0 with secure boot supported.

###### What changes were made since your SHIM was last signed?
No.

###### What is the hash of your final SHIM binary?
SHA256:
d56c88deb1cb0d86cdd947d851be78da8c65c97bcbd75d405cfc7f0fe522b0a7  shimx64.efi

**Comment by julian-klode** [comment]
This request has been submitted prior to the BootHole vulnerability. Since then, new questions with new requirements have been added to the templates.

If you still need a newer shim signed, please submit a new issue with the new templates. This should include a Dockerfile that can build your shim binaries so that review does not require manual effort for the building part, see `examples/Dockerfile.ubuntu` for an example.

(this is a semi-automatic message copied to multiple bugs).
